### ISSUE TITLE
Testpage isn't getting blocked despite usage of multiple lists

### ISSUE THREAD

**Issue by Akashic101** [lightswitch05/hosts#100]
I've added the Ads & Tracking and the AMP Hosts-lists to my blocklist, but whenever I use the testpage the image is still showing up. Pihole confirms I am connected to it and i already cleared the cache of my browsers (tested in firefox, chrome and edge on phone and laptop). Both lists are fresh and up-to-date, same with the pi. Am I missing something?

**Comment by lightswitch05** [comment]
Hello @Akashic101. You might be interested in this reddit thread that reports similar issues: https://www.reddit.com/r/pihole/comments/d56wt9/strange_blocklist_problem/

Just make sure you have the latest version of PiHole and restart everything - including the pihole and then try again?

**Comment by Akashic101** [comment]
I ran "pihole -up" and it returned newest version, I restarted my pi and pc and cleared the cache again, but running "pihole -q  block-test.developerdan.com" returns 2 matches found in your blocklist. The image is still not getting blocked. Any ideas?

**Comment by lightswitch05** [comment]
Check your pihole logs. If you are actually using your pihole like you say, then you should see the requests in the logs

**Comment by lightswitch05** [comment]
If you have another DNS server defined on your network - that could cause pihole bypass too. There is no such thing as a primary and secondary DNS, some clients will query both servers: https://discourse.pi-hole.net/t/primary-vs-secondary-dns/1536

**Comment by Akashic101** [comment]
The problem seems really weird. Looking at my log it's only showing up at all when I load it on my Phone in Chrome. Firefox Preview lets it through and is also showing nothing at all in the logs. I test it a bit more on my pc and get back to you then.

**Comment by lightswitch05** [comment]
@Akashic101 oh you are using Firefox Preview. Well that is simple enough, your firefox is bypassing your local DNS. See https://discourse.pi-hole.net/t/support-for-returning-nxdomain-for-use-application-dns-net-to-disable-firefox-doh/23243
