### ISSUE TITLE
Please whitelist "msn.com"

### ISSUE THREAD

**Issue by ndrwy** [lightswitch05/hosts#101]
I ran into an issue where the MSN homepage wouldn't load because `msn.com` is being blocked: https://github.com/lightswitch05/hosts/commit/9c08c5262ed616d3f47f992671924a0d3db5dba1

Thanks for all your work on this list!

**Comment by lightswitch05** [comment]
Thanks for bringing this to my attention @ndrwy ! It was obviously an accidental copy-paste issue when adding the other hosts related to MSN. Its removed now! I'm very sorry about the mistake, thank you again for telling me about it!
