### ISSUE TITLE
Turner sites

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#103]
Hi, 

NBA.com videos do not work with the aggressive list because these scripts are needed for the video player.

```
https://i.cdn.turner.com/ads/adfuel/ais/1.3/nba2-ais.js
https://i.cdn.turner.com/ads/adfuel/adfuel-1.3.5.min.js
```

Test link: `https://www.nba.com/video/2019/09/25/20190925-gametime-kia-mvp-lebron-anthony-davis-candidancy`

`http://www.tcm.com/` and `https://www.adultswim.com/` are totally broken due to the inclusion of `i.cdn.turner.com` as well.

Being that it is an aggressive list, and `i.cdn.turner.com` hosts a mix of legit stylesheets and images and tracking and ad scripts, I guess it should remain on the list. Previous discussion here: https://github.com/lightswitch05/hosts/issues/93

Also: NBA.com is a Turner site, so like CNN, it has an `agility` subdomain used for tracking scripts.

Therefore, please add:

```
agility.nba.com
agility.ncaa.com
agility.eleague.com
agility.tbs.com
agility.cartoonnetwork.com
```

(All of the above are Turner sites) 

Thanks

**Comment by lightswitch05** [comment]
All that looks reasonable. As always, thank you for the very detailed and descriptive request! I’ll add it as soon as I get back to my computer, perhaps early tomorrow

**Comment by lightswitch05** [comment]
@llacb47 they have been added in https://github.com/lightswitch05/hosts/commit/2e21166905dee2014591c8f28930d34f194d4c68 - I also added a couple other trackers found while testing the sites you listed. Thanks again for the useful feedback 👍
