### ISSUE TITLE
[false-positive] guce.yahoo.com

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#106]
@lightswitch05  when blocked i **can not access** my yahoo e-mail. Looks like that `guce.yahoo.com` redirects to `mail.yahoo.com`. If you don't mind remove it from the lists.
Thanks 👍

**Comment by lightswitch05** [comment]
Bummer. I don’t know if I’d exactly call it a false positive. I believe this is a tracking consent host for Yahoo Oath- but breaking yahoo mail is definitely a big deal. I’m away from keyboard at the moment, but I’ll get it fixed as soon as I can.

I’ll also research it more and perhaps move it to the aggressive list. Thanks for the report!

**Comment by dnmTX** [comment]
Everything `Yahoo` is shady as hell if you ask me but as you said braking the mail client is not something that we can overlook. Thanks again bud 😉

**Comment by lightswitch05** [comment]
It is removed now. Unfortunately I didn't have a good record on that one for why I thought it should be blocked. If I see it again, I might add it to the aggressive list. Thanks again for the report @dnmTX!

**Comment by dnmTX** [comment]
> Thanks again for the report @dnmTX!

Anytime.Here to help 😉
