### ISSUE TITLE
Hulu broken after adding blocklist

### ISSUE THREAD

**Issue by herecomethebugs** [lightswitch05/hosts#107]
I want to use your list but after adding it, it breaks hulu. Any thoughts on how to get hulu working again/have you thought about modifying your list to allow hulu?

**Comment by lightswitch05** [comment]
Hello @herecomethebugs. I use Hulu all the time without issue. Can you provide more details? Which list are you using? How are you watching Hulu? What exactly isn’t working?

**Comment by lightswitch05** [comment]
I've confirmed Hulu still works with this list, and other users on Reddit have recently confirmed it too. Closing until further information is given
