### ISSUE TITLE
Mint email links broken by links.mint.com

### ISSUE THREAD

**Issue by mkb2091** [lightswitch05/hosts#108]
As title says, links.mint.com is needed to be able to click links in mint emails(and therefore probably track the user), and as far as I can tell the domain isn't used anywhere else, so the user is able to avoid the tracking by not clicking the links

**Comment by lightswitch05** [comment]
Sounds like a reasonable request. I’ll spend a little time on mint just to very the links host is in fact only link and then make the adjustment 👍

**Comment by lightswitch05** [comment]
Closed by https://github.com/lightswitch05/hosts/commit/18be8ac4e4aa722c518dc9dad90e53a300542f5c
