### ISSUE TITLE
Does db-ip.com deserve being blacklisted?

### ISSUE THREAD

**Issue by AlphaTangoCharly** [lightswitch05/hosts#109]
Hi,

I find 15 occurrences of db-ip.com in
```
# Title: Lightswitch05's ads-and-tracking-extended.txt
# Released: 2019-10-15T12:50:32+00:00 
```

As always when one uses (or used to use) a site extensively and discovers this site is blacklisted, the wondering arises about the pertinence of this blocking.

I'd only wish to know on what basis db-ip.com is blacklisted in above mentioned list. Thanks!

**Comment by lightswitch05** [comment]
Hello @AlphaTangoCharly. That entry was added in part of #98. I have several other ip-geo-lookup services blocked as well. While the service itself might not be a tracker/advertiser, advertisers and trackers use the service to provide two services:

1. Ensure the visitor is in a region that allows tracking (GDPR requirement)
2. Provide location specific targeted advertising

Unfortunately, I added 84 different hosts related to that ticket, so I'm unable to provide you with the exact script that was using it. Again, its not so much the site directly, but more the way its being used by 3rd parties. If this is a site that you make use of, then I would suggest whitelisting it.

I hope that answers your question and thank you for your feedback.

**Comment by AlphaTangoCharly** [comment]
@lightswitch05 , thanks for the information. I'm not surprised that several ip-geo-lookup services are concerned, I've encountered a few myself, perhaps more flagrant than db-ip.com.

I understand your explanation and i'll make no exception for db-ip.com, you're the pro, not me. I was just surprised. I know and use other ip-geo-lookup services and will stick on with those.

Thanks again. Your blacklists most appreciated.
