### ISSUE TITLE
You blocked wowhead.com

### ISSUE THREAD

**Issue by daniel-widrick** [lightswitch05/hosts#11]
dig www.wowhead.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.wowhead.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63608
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.wowhead.com.               IN      A

;; ANSWER SECTION:
www.wowhead.com.        288     IN      CNAME   a005.zamnetwork.inscname.net.
a005.zamnetwork.inscname.net. 3600 IN   CNAME   inscname.net.
inscname.net.           3600    IN      A       0.0.0.0

**Comment by daniel-widrick** [comment]
This appears to be an issue again.

$ dig @8.8.8.8 www.wowhead.com

; <<>> DiG 9.11.0-P5 <<>> @8.8.8.8 www.wowhead.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63822
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.wowhead.com.               IN      A

;; ANSWER SECTION:
www.wowhead.com.        268     IN      CNAME   a191.zamnetwork.inscname.net.
a191.zamnetwork.inscname.net. 599 IN    CNAME   ins-091.inscname.net.
ins-091.inscname.net.   3599    IN      CNAME   a-sg08sl07.insnw.net.
a-sg08sl07.insnw.net.   3599    IN      A       192.33.31.183

;; Query time: 47 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Aug 21 14:06:02 EDT 2018
;; MSG SIZE  rcvd: 155

**Comment by lightswitch05** [comment]
@daniel-widrick the only entry in my list is `a021.ranker.inscname.net` - which is not in your dns entry above. Could you please look at [tracking-aggressive-extended.txt](https://github.com/lightswitch05/hosts/blob/master/ads-and-tracking-extended.txt) and tell me exactly which name is causing you issues?

**Comment by lightswitch05** [comment]
@daniel-widrick I see the issue is insnw.net this time. I've removed it, please let me know if this doesn't fix your problem
