### ISSUE TITLE
Failed Parse of Ad & Tracking List

### ISSUE THREAD

**Issue by gorlilla** [lightswitch05/hosts#110]
ads-and-tracking-extended.txt contains invalid characters located at: 

```
50947:    0.0.0.0 (ohlone.vizu.com

...

58923:    0.0.0.0 (pmi.nui.media
```

**Comment by lightswitch05** [comment]
Wow! Thank you for catching that. I've removed the two entries. I've also created test to ensure that doesn't happen again. Thank you for the report! Fixed in https://github.com/lightswitch05/hosts/commit/06440852a53e09b9deb7ca632fee1ce3739dfb53
