### ISSUE TITLE
Legitimate site blocked

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#112]
```
rakuten.co.jp
```

You have blocked the 6th most popular shopping site in the world. Please remove if possible.

**Comment by lightswitch05** [comment]
Thanks for the report! Looks like this was added in https://github.com/lightswitch05/hosts/pull/104

**Comment by lightswitch05** [comment]
fixed by https://github.com/lightswitch05/hosts/commit/dfee75711ad74fa4350782120be542a5dac01035

**Comment by llacb47** [comment]
Some of them are tracking though

**Comment by lightswitch05** [comment]
@llacb47 yes, but this also isn't a website I use - I can't even read it. I decided to remove them all since I'm unable to verify any of it.
