### ISSUE TITLE
Extra Tracking Protection For tracking-aggressive-extended.txt

### ISSUE THREAD

**Issue by Cybo1927** [lightswitch05/hosts#113]
You can use these to help protect against tracking by popups or IPs (on insecure sites).

! Block insecure (HTTP) popups
/^http:/$popup
! Block insecure (HTTP) popunders on supported adblockers
/^http:/$popunder
! Block IP addresses on insecure domains
^http*:\/\/([0-9]{1,3}\.){3}[0-9]{1,3}$domain=http://

**Comment by llacb47** [comment]
Lol, it's a hosts lists. You cannot use ABP syntax.

**Comment by lightswitch05** [comment]
Thanks for your input @Cybo1927. Unfortunately, the hosts format is drastically limited when compared to other blocking formats like the ones you’ve listed. None of the blocks you listed are compatible with my hosts formatted list. See: https://en.m.wikipedia.org/wiki/Hosts_%28file%29?wprov=sfti1

**Comment by Cybo1927** [comment]
Ah, didn't realizze it was a hosts file like that. Figured it was meant mostly for ad/general content blockers. Great to know though, I'm trying to help the smaller lists block trackers that the main ones (like HP's or Dan Pollock's) don't.
