### ISSUE TITLE
double check/inspect few blocked domains

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#116]
@lightswitch05  i just stumbled on a website that i visited and noticed that some things like reviews,description,details etc. on each product can not be opened. There are few domains from your lists that are blocked: `*.justuno.com` `*.klaviyo.com`  and `*.rejoiner.com` . Can you please double check/test and see if they're false positives just in case.If there is some aggressive telemetry involved just keep on blocking them. I just want to be sure as i'm planning to order some of their products from there in the feature.
Website: https://www.nativecos.com

P.S. Found one there that i believe it's safe to block: `analytics.getshogun.com`
Link for Inspection: `https://analytics.getshogun.com/collector.js?shop=native-deodorant.myshopify.com`

Thanks a bunch @lightswitch05  👍

**Comment by llacb47** [comment]
`analytics.getshogun.com` is in the list already

**Comment by dnmTX** [comment]
> analytics.getshogun.com is in the list already

Yeah,i've noticed that but i'm loading the lists from another repo and for some reason it's missing there.
Already opened a issue there,hopefully will be sorted out soon.
@lightswitch05  never mind on `analytics.getshogun.com`,the rest remains though.

**Comment by lightswitch05** [comment]
Its working for me @dnmTX 

![image](https://user-images.githubusercontent.com/598803/68677858-cf207e80-052a-11ea-8a98-363c0ea56528.png)

I've had several recent updates to whitelist a few things, especially with shopify websites. It sounds like whatever issue you are having has already been fixed and you are just missing the updates. Where are you getting my lists from?

**Comment by dnmTX** [comment]
> I've had several recent updates to whitelist a few things, especially with shopify websites. It sounds like whatever issue you are having has already been fixed and you are just missing the updates.

Very likely,will double check that and get back to you on this one just to confirm

> Where are you getting my lists from?
I guess you forgot about it,you were even member there at one point from what i can remember 😉 
You know i like my lists to be filtered against dead domains and what not,so i keep using it:
https://github.com/Ultimate-Hosts-Blacklist/lightswitch05_hosts_ads-and-tracking-extended

**Comment by lightswitch05** [comment]
I don’t know how I forgot about that PyFunceble project 😆 I had an infant at the time and was severely sleep deprived 😴

**Comment by funilrys** [comment]
Sorry for the behavior. 

It's fixed for good. I just forgot about CNAME and DNAME as a fallback. I was too focused on NS records ...

Cheers.
