### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by daberlin** [lightswitch05/hosts#117]
Hi.
In the "ads-and-tracking-extended.txt" list, "www.adjust.com" is blocked, even though this is just the website of that service, which is imho not used for tracking (afaik the various subdomains and adj.st are used...)

**Comment by lightswitch05** [comment]
Hello, thanks for your comments @daberlin. The actual block in the base list is `adjust.com` - which then gets expanded out into all its various subdomains in the primary extended list. There are certainly subdomains of the adjust.com website that do tracking. Some of which are `api.adjust.com`, `app.adjust.com`, `trk.adjust.com`. Certainly `www.adjust.com` could be an innocent subdomain. But given that this is an ad and tracking company, and this list is to block advertisers and trackers, then I make no attempt to differentiate between the different domains. Certainly I do not want any TCP connections open to anything related to that company - not even their `www` website.
