### ISSUE TITLE
[Question]  IP Address vs host name; which  one is faster?

### ISSUE THREAD

**Issue by kyrios21** [lightswitch05/hosts#118]
Hi Daniel,

I would like to know which one is better,
1. blocking the **host name** using `0.0.0.0 hostname` in hosts file. Or
2. blocking **IP address** using  `iptables -I FORWARD -d IP.ADDRESS -j REJECT` in Firewall.
Which one is faster?
The reason I ask is some trackers use/bought unique domain name and after 1 year expiry, they buy again different domain name coz the older domain name has been listed in several adblock list like  easylist or easyprivacy. To combat with this, they let the domain expiry in 1 year, and buy again new domain name yearly.
So to counter this technique, I wanna block their IP Address as I thought they will rarely change the hosting company.
To illustrate this, please take a look at `8cb0309458c7b35e.com`.
I forgot where I encounter this domain name, but probably in some porn site.
Back to conversation, if we check the IP address of `8cb0309458c7b35e.com`, we will see
its IP address is 51.158.26.130 and 51.158.26.139
And if we check that IP address, we'll find other domain names.
`
2a12be6140880286.com
6631f33cf2a1032b.com
442d9f2ac50ca502.com
`
I do believe those domain names were made for same purpose. And by blocking the IP address via firewall, we have an advantage by new domain names they create later (whatever the names are) , we will block it as well. 
=============
Another example is 
944e66f8683ac43c.com
e376ef28103177cc.com
And their IP address are 51.158.26.75 and 51.158.26.81. And probably 51.89.171.42 as well.

**Comment by kyrios21** [comment]
Case study :
1. writing 2 IP address only in firewall vs writing 17 domain names in hosts file.
`mpqfzyh.com`
2. Will you write the whole 81 domain names?
`ca4ec6874a33a13.com`

**Comment by lightswitch05** [comment]
Hey @kyrios21 - thanks for the thoughtful question. Why not do both? Each methods have their pros and cons. Apps/websites don’t even have to use DNS- they could just hardcode an IP address. IP blocking is certainly more aggressive.

However, I will add that IP blocking can cause many problems if not managed and researched properly. MANY advertisements use CDNs to serve content- those CDN can be used by many different servers. If you end up blocking a CDNs IP address, then you’ve just broke a lot of things that has nothing to do with advertisements.

Of course, there is another downside too. DNS can refer to many different IP addresses for load-balancing/region-targeting/fail-over. So, expanding out DNS to IP addresses could be tricky. Furthermore, with cloud-based providers, you could see IP addresses for a single DNS name changing often- perhaps even daily as infrastructure is rebuilt/deployed just as often as code is. So it would be important to keep you IP addresses updated regularly.

So anyways, I don’t really have an answer for  you. They both have their strengths and weaknesses.

**Comment by kyrios21** [comment]
After thinking for a while, I thought IP Adress blocking is really really agressive.
Afterall, not everyone hosting their website in droplet/VPS.
Mostly are using shared hosting, so 1 IP address can be occupied by many host names.
I will carefully write the IP address blocking in firewall.
