### ISSUE TITLE
False positive(?) www.opinionstage.com

### ISSUE THREAD

**Issue by TorchedPoseidon** [lightswitch05/hosts#119]
Lazy copy paste from https://github.com/anudeepND/blacklist/issues/68, only on this repo it applies to `ads-and-tracking-extended.txt` and it pertains to `opinionstage.com ` in addition to `www.opinionstage.com ` and obviously its @lightswitch05 that has to make the consideration on this repo:

> `adservers.txt `includes `www.opinionstage.com` which is used by some newsblogs for a quick and dirty way to poll readers. [Example (Dutch)](https://www.iculture.nl/nieuws/iphone-11-serie-gps-probleem/), they use it regularly.  
>I'll leave it up to @anudeepND if that's to be considered a false positive or if it falls within the scope of what the list is trying to block.

**Comment by lightswitch05** [comment]
@TorchedPoseidon unfortunately I didn't include great notes on this one when I added it. Also, looking at your example website, I do not see any usage of `opinionstage.com`. I'll leave this open until better examples can be found

**Comment by TorchedPoseidon** [comment]
@lightswitch05 Apparently on their website they use a link to the poll (in the example it's labeled with 'Je kunt de poll ook hier invullen.'), my bad. I first noticed it in their app where they show it inline within the articles. 

It's more or a less a grey area I think and it should depend on the aim of the list in question (i.e. what is it trying to block). Thus far it just seems like a simple polling instrument, but I'm not aware of any potential subdomains that might do more comprehensive tracking or adserving.

**Comment by lightswitch05** [comment]
moved to aggressive list
