### ISSUE TITLE
False positive: cdn.ravenjs.com

### ISSUE THREAD

**Issue by durablenapkin** [lightswitch05/hosts#121]
`cdn.ravenjs.com` is needed as a JS library: https://ravenjs.com/
Family member said a site wouldn't load (some collaboration tool using raven as a dependency) and whitelisting `cdn.ravenjs.com` helped.

Thanks!

**Comment by lightswitch05** [comment]
Please see #58

**Comment by durablenapkin** [comment]
Many thanks for linking that issue and for your rationale.

**Comment by lightswitch05** [comment]
No problem, I also appreciate the feedback. I have certainly messed up and blocked wrong things before, sometimes it takes weeks before anyone notices (or bothers telling me about it).
