### ISSUE TITLE
telecommand.telemetry.microsoft.com

### ISSUE THREAD

**Issue by beerisgood** [lightswitch05/hosts#125]
telecommand.telemetry.microsoft.com is used by Windows Error Reporting and isn't telemetry.

So please unblock it

https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1903-non-enterprise-editions

**Comment by llacb47** [comment]
https://github.com/StevenBlack/hosts/issues/1135#issuecomment-578448539

**Comment by beerisgood** [comment]
@llacb47 This isn't the rep from StevenBlack which don't care about false positives

**Comment by lightswitch05** [comment]
I appreciate the link @llacb47. I’m out of town for a while, so it’s going to be awhile before I can review this request. Just based on the URL I’m inclined to leave it, but I’ll be sure to review it first. Perhaps it belongs to the aggressive list. If anyone else has more details about this host, please share!

**Comment by dnmTX** [comment]
@lightswitch05  would not recommend removal.Even if it's used to serve Error Reporting,no one knows what info has been sent.Since when we started trusting Microsoft.one of the biggest privacy offenders 
...ever???????

**Comment by beerisgood** [comment]
Windows Error Reporting is a legitimate internal Windows feature to report problems with programs/ apps, driver, or other system components.

The user can configure sending this data any time. But blocking it at DNS level, block it always and can't provide the needed information to fix the problems.

Also thanks for mark llacb47's post as off-topic. Would be good if you do the same with dnmTX's post.
He doesn't have any knowledge about such stuff and only troll over threads.

Users can verify which data are send to Microsoft with the [Diagnostic Data Viewer](https://www.microsoft.com/en-us/p/diagnostic-data-viewer/9n8wtrrsq8f7?activetab=pivot:overviewtab) tool. But no, some users start trolling nowadays and spread missonformation which cripple down the system and make serious problems.
Blocking telemetry is fine, but not so important stuff.

I wait for your comeback, @lightswitch05

**Comment by ler762** [comment]
@beerisgood how does one configure Windows Error Reporting to send data at any time when "any time" = "never"?

> Users can verify which data are send to Microsoft ...

"are send" meaning "has been sent" .. in which case it's too late to do anything about it?

> Blocking telemetry is fine, but not so important stuff.

Shouldn't the end-user be the one to decide what information they're willing to share with Microsoft?
Hopefully @lightswitch05 agrees and doesn't remove it.

I'm off to check out the aggressive list to see what else I should be blocking :)

**Comment by beerisgood** [comment]
You can config that from Windows itself. If it's never, it's never sending that data and can't help you.

Yes I mean "has been sent" / in blocking the DNS case: "has been collected".

The enduser can choice between fully telemetry and basic which only use system needed info. You can verify that in the tool.

**Comment by lightswitch05** [comment]
<img width="708" alt="image" src="https://user-images.githubusercontent.com/598803/73221047-889ff080-4125-11ea-821c-502a00ee242e.png">
I don't know how this append, but this is a very topical comment and I do not appreciate whoever got it marked as offtopic

**Comment by lightswitch05** [comment]
> Shouldn't the end-user be the one to decide what information they're willing to share with Microsoft?

I've said other places that I consider this list a default opt-out (as all this data collection should be), and users of the list are encouraged to whitelist anything they want to allow (ie. opt-in)

**Comment by lightswitch05** [comment]
@beerisgood - it looks like you've been actively searching out projects that block this URL. Do you use this hosts file, or are you just reporting back details you know about this URL?

**Comment by lightswitch05** [comment]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/598803/73221474-96a24100-4126-11ea-9bbe-f44ba15c04b5.png">

Well I think we have a consensus. I'm going to leave it. I really like default opt-outs. I do have a windows 10 box that I use rarely, and sometimes after large updates I'll see that some of the tracking crap is re-enabled. I really don't like that. I also really don't like that I even have to opt-out to begin with.

I do appreciate the info @beerisgood - and I hope you feel welcome to open tickets in the future if you find any more hosts you believe to be a false positive. And I hope other people who follow this project will remember that everyone's opinions are welcome. I trust you have the technical abilities to whitelist the host in question on your own.

I also appreciate hearing arguments from both sides - **as long as it stays on topic and doesn't include personal attacks.** The link @llacb47 shared was 100% on topic as I respect Steven's opinion and enjoy using his list. @dnmTX I understand your passionate about these blocklists, but please tone it down a bit and keep your comments on topic. **At the end of the day it is my decision and my decision alone what stays or goes into my lists.**

**Comment by beerisgood** [comment]
> @beerisgood - it looks like you've been actively searching out projects that block this URL. Do you use this hosts file, or are you just reporting back details you know about this URL?

Yes I use this list and report to every list false positives entry I found which aren't telemetry and help to improve the lists.

**Comment by DRSDavidSoft** [comment]
@beerisgood Sorry to barge in, but I wanted to share my two cents.

Personally, I'm not going to whitelist _any_ telemetry domains, unless the service is **opt-in**, not opt-out. I maintain one of those lists that has over 2M+ entries, that is used in both an enterprise environment, my home, and devices for my friends and family.

I'm never going to allow Microsoft telemetry, _unless_ they ask the user for consent first. Sadly, this just isn't the case. I love Microsoft products, but their practice to just don't count the user as someone who can decide whether to use this service or not, in my opinion, is highly annoying and even unethical.

Although I have taken a more aggressive approach, and I even [block crashlytics](https://github.com/StevenBlack/hosts/issues/896), for the sake of privacy. I do not see any reason that any device that I might use should report anything other than what I choose to other servers.

As I've said, that's just my 2 cents.
