### ISSUE TITLE
blocking nrdp.nccp.netflix.com blocks netflix login on LG TV

### ISSUE THREAD

**Issue by ilaughlin** [lightswitch05/hosts#128]
Blocking nrdp.nccp.netflix.com on LG TV blocks netflix log in.  Does not appear to occur on any other TV.  The only modification I made was to whitelist nrdp.nccp.netflix.com, which then allowed netflix log in.

**Comment by lightswitch05** [comment]
Thanks for the report @ilaughlin - but it looks like you have the wrong list. I do not block `nrdp.nccp.netflix.com` in this list. It looks like this list does block that host:

`https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt`
