### ISSUE TITLE
Tubi TV Roku App

### ISSUE THREAD

**Issue by ccbrianf** [lightswitch05/hosts#130]
The following host names are required for the Roku Tubi TV app to work:
cd.adrise.tv
images.adrise.tv
uapi.adrise.tv

**Comment by lightswitch05** [comment]
Thanks for the report @ccbrianf. Here are the ones blocked in Steven Black's host list, which is a default list for the PiHole:

```
   ads.adrise.tv
   frqj.adrise.tv
   paella.adrise.tv
   s.adrise.tv
```

@anudeepND blocks these in his popular list:

```
   c12.adrise.tv
   uapi.adrise.tv
```

And these are the ones blocked in my list (https://github.com/lightswitch05/hosts/commit/06452b71):

```
   adrise.tv
   ads.adrise.tv
   ads-tp.adrise.tv
   api.adrise.tv
   c11.adrise.tv
   c12.adrise.tv
   c13.adrise.tv
   c23.adrise.tv
   c24.adrise.tv
   c3.adrise.tv
   c7.adrise.tv
   c8.adrise.tv
   cdn.adrise.tv
   frqj.adrise.tv
   fvmw.adrise.tv
   i.adrise.tv
   images.adrise.tv
   images02.adrise.tv
   img.adrise.tv
   lhzf.adrise.tv
   paella.adrise.tv
   rbyd.adrise.tv
   s.adrise.tv
   sqxr.adrise.tv
   titan.adrise.tv
   uapi.adrise.tv
   www.adrise.tv
```

Given that these hosts are very clearly advertising hosts and that they are used in other places then the specific app you are having issues with, I intend on keeping them blocked in my list. I'll leave this ticket open for a while in case others wish to comment. Thank you again for opening the ticket, I hope others having similar issues are able to find this ticket to help them solve their problems.

**Comment by ccbrianf** [comment]
Yes, I reported uapi to anudeepND as well.  I have no issue with the hosts blocked by Steven Black or any of the other hosts listed.  I just wanted to report a functionality issue that may effect a large number of users. Thank you for considering it.
--
Brian Ford - Systems Architect
FlightSafety Visual Systems

On Feb 10, 2020, at 7:36 AM, Daniel <notifications@github.com> wrote:

﻿
EXTERNAL EMAIL: STOP and verify sender address, links, and attachments before taking action.


Thanks for the report @ccbrianf<https://github.com/ccbrianf>. Here are the ones blocked in Steven Black's host list, which is a default list for the PiHole:

   ads.adrise.tv
   frqj.adrise.tv
   paella.adrise.tv
   s.adrise.tv


@anudeepND<https://github.com/anudeepND> blocks these in his popular list:

   c12.adrise.tv
   uapi.adrise.tv


And these are the ones blocked in my list (06452b7<https://github.com/lightswitch05/hosts/commit/06452b71>):

   adrise.tv
   ads.adrise.tv
   ads-tp.adrise.tv
   api.adrise.tv
   c11.adrise.tv
   c12.adrise.tv
   c13.adrise.tv
   c23.adrise.tv
   c24.adrise.tv
   c3.adrise.tv
   c7.adrise.tv
   c8.adrise.tv
   cdn.adrise.tv
   frqj.adrise.tv
   fvmw.adrise.tv
   i.adrise.tv
   images.adrise.tv
   images02.adrise.tv
   img.adrise.tv
   lhzf.adrise.tv
   paella.adrise.tv
   rbyd.adrise.tv
   s.adrise.tv
   sqxr.adrise.tv
   titan.adrise.tv
   uapi.adrise.tv
   www.adrise.tv


Given that these hosts are very clearly advertising hosts and that they are used in other places then the specific app you are having issues with, I intend on keeping them blocked in my list. I'll leave this ticket open for a while in case others wish to comment. Thank you again for opening the ticket, I hope others having similar issues are able to find this ticket to help them solve their problems.
