### ISSUE TITLE
aff tracking?

### ISSUE THREAD

**Issue by ler762** [lightswitch05/hosts#131]
Do you consider affiliate tracking OK or think of it as plain old tracking and block it?

for example: ``view-source:https://webflow.com/``

```
<!-- REFERSION TRACKING: BEGIN -->
<script src="//webflow.refersion.com/tracker/v3/pub ...
```

or ``view-source:https://caliwhite.com/``

```
https://cdn.refersion.com/pixel.js?shop=cali-white.myshopify.com ...
```

**Comment by lightswitch05** [comment]
I’ll have to look at these closer when I’m on the computer, but generally speaking I’ll block any kinds of tracking. I avoid blocking link click tracking - I figure if you clicked the the link, the you want it to work. Of course there is also the aggressive lists as well. Thanks for sharing, I’ll update once I spend more time looking into them.

**Comment by lightswitch05** [comment]
Added in https://github.com/lightswitch05/hosts/commit/5c27373c3d747406572c921ddd7b0abcc8203aa4, thanks for the info @ler762!
