### ISSUE TITLE
Multiple websites use "ssl.marfeelcdn.com" as CNAME

### ISSUE THREAD

**Issue by hectorm** [lightswitch05/hosts#132]
Marfeel is an advertising company of which I have no relation, but it seems that some websites use their CDN to serve content and blocking the domain `ssl.marfeelcdn.com` makes them inaccessible, since when blocking ads at DNS level many resolvers (systemd-resolved, Unbound and Knot Resolver are the ones I know with this behavior) will prevent clients from accessing a domain that has a CNAME record pointing to a blacklisted domain.

I open this issue only to inform about this problem and evaluate if it would be convenient or not to remove this domain from the blacklist.

This is the list of websites that I have found with this problem:
  - https://www.ghacks.net
  - https://www.gizchina.com
  - https://www.lainformacion.com

But any website that has followed [these instructions](https://atenea.marfeel.com/atn/marfeel-press/systems-requirements/marfeel-s-content-delivery-network/create-a-cname-in-cloudflare) is affected by this.

**Comment by lightswitch05** [comment]
![image](https://user-images.githubusercontent.com/598803/74869140-72044800-5325-11ea-8a28-9f92f0dcffd0.png)

This is going to get interesting as CNAME blocking becomes more and more common. I understand that PiHole is gong to start supporting CNAME based blocking as well.

At the moment, I'm inclined not to take any action on this. It seems like if I start removing things just based on a CNAME, then the list will quickly become empty - as it takes no effort to setup CNAMES. But I'm going to leave this ticket open for tracking as its certainly a problem and I would appreciate other people's opinions on the issue.

**Comment by lightswitch05** [comment]
for tracking, `ssl.marfeelcdn.com` was added in https://github.com/lightswitch05/hosts/commit/772c2c5e

**Comment by hectorm** [comment]
Just to add more data, I checked the CNAME records of the [top million websites](https://blog.majestic.com/development/majestic-million-csv-daily/) (with and without www) and these are the domains that use the Marfeel CDN:
```
vistanews.ru	ssl.marfeelcdn.com.
www.01net.com	ssl.marfeelcdn.com.
www.abcdiario.com.ar	ssl.marfeelcdn.com.
www.abcnoticias.mx	ssl.marfeelcdn.com.
www.albawaba.com	ssl1.marfeelcdn.com.
www.brandeating.com	ssl.marfeelcdn.com.
www.capetownmagazine.com	ssl.marfeelcdn.com.
www.clickgratis.com.br	ssl.marfeelcdn.com.
www.contextotucuman.com	ssl.marfeelcdn.com.
www.cubanet.org	ssl1.marfeelcdn.com.
www.davidemaggio.it	ssl1.marfeelcdn.com.
www.der-postillon.com	ssl.marfeelcdn.com.
www.diariodemorelos.com	ssl.marfeelcdn.com.
www.diariodocentrodomundo.com.br	ssl.marfeelcdn.com.
www.diariomotor.com	ssl.marfeelcdn.com.
www.diariopopular.com.ar	ssl.marfeelcdn.com.
www.dicasonline.com	ssl1.marfeelcdn.com.
www.efesalud.com	ssl.marfeelcdn.com.
www.elbebe.com	ssl.marfeelcdn.com.
www.elcorreogallego.es	ssl.marfeelcdn.com.
www.elfarandi.com	ssl.marfeelcdn.com.
www.elgoldigital.com	ssl.marfeelcdn.com.
www.elnacional.com.do	ssl1.marfeelcdn.com.
www.elnueve.com	ssl.marfeelcdn.com.
www.elsol.com.ar	ssl.marfeelcdn.com.
www.esdiario.com	ssl.marfeelcdn.com.
www.exclusivadigital.com	ssl.marfeelcdn.com.
www.foot01.com	ssl.marfeelcdn.com.
www.ghacks.net	ssl.marfeelcdn.com.
www.gizchina.com	ssl.marfeelcdn.com.
www.greenme.com.br	ssl.marfeelcdn.com.
www.guineenews.org	ssl.marfeelcdn.com.
www.hibridosyelectricos.com	ssl.marfeelcdn.com.
www.homeremedyhacks.com	ssl.marfeelcdn.com.
www.hoy.com.do	ssl.marfeelcdn.com.
www.ibahia.com	ssl1.marfeelcdn.com.
www.iharare.com	ssl1.marfeelcdn.com.
www.ipadizate.es	ssl1.marfeelcdn.com.
www.jamaicaobserver.com	ssl.marfeelcdn.com.
www.lainformacion.com	ssl.marfeelcdn.com.
www.lakersnation.com	ssl.marfeelcdn.com.
www.lanutrition.fr	ssl.marfeelcdn.com.
www.larepublica.cat	ssl.marfeelcdn.com.
www.libero.pe	ssl.marfeelcdn.com.
www.ma-grande-taille.com	ssl.marfeelcdn.com.
www.manilatimes.net	ssl.marfeelcdn.com.
www.mediterraneodigital.com	ssl.marfeelcdn.com.
www.menprovement.com	ssl1.marfeelcdn.com.
www.mobilegeeks.de	ssl.marfeelcdn.com.
www.moroccoworldnews.com	ssl.marfeelcdn.com.
www.nbamaniacs.com	ssl2.marfeelcdn.com.
www.newsday.co.zw	ssl2.marfeelcdn.com.
www.noticiasaominuto.com.br	ssl.marfeelcdn.com.
www.periodistadigital.com	ssl.marfeelcdn.com.
www.petdarling.com	ssl.marfeelcdn.com.
www.portalraizes.com	ssl.marfeelcdn.com.
www.proceso.com.mx	ssl.marfeelcdn.com.
www.recetasderechupete.com	ssl1.marfeelcdn.com.
www.religionenlibertad.com	ssl.marfeelcdn.com.
www.revistapazes.com	ssl.marfeelcdn.com.
www.riazor.org	ssl.marfeelcdn.com.
www.solobasket.com	ssl.marfeelcdn.com.
www.somosxbox.com	ssl.marfeelcdn.com.
www.sportune.fr	ssl.marfeelcdn.com.
www.stirimondene.fanatik.ro	ssl.marfeelcdn.com.
www.thecanary.co	ssl.marfeelcdn.com.
www.theindependent.co.zw	ssl2.marfeelcdn.com.
www.thelondoneconomic.com	ssl.marfeelcdn.com.
www.theolivepress.es	ssl.marfeelcdn.com.
www.thephoblographer.com	ssl1.marfeelcdn.com.
www.thesouthafrican.com	ssl1.marfeelcdn.com.
www.thestandard.co.zw	ssl2.marfeelcdn.com.
www.tinyhouseblog.com	ssl.marfeelcdn.com.
www.trinidadexpress.com	ssl.marfeelcdn.com.
www.tuxboard.com	ssl.marfeelcdn.com.
www.ubitennis.com	ssl1.marfeelcdn.com.
www.unidivers.fr	ssl.marfeelcdn.com.
www.vanguardia.com.mx	ssl1.marfeelcdn.com.
www.vistanews.ru	ssl.marfeelcdn.com.
www.vortexmag.net	ssl.marfeelcdn.com.
www.wapa.pe	ssl.marfeelcdn.com.
www.wheninmanila.com	ssl.marfeelcdn.com.
www.yucatan.com.mx	ssl.marfeelcdn.com.
www.zmescience.com	ssl1.marfeelcdn.com.
```

[This is the full list](https://github.com/lightswitch05/hosts/files/4252318/result.txt) of all CNAME records.

**Comment by lightswitch05** [comment]
Thank you for the added information @hectorm

**Comment by lightswitch05** [comment]
At the moment, I am not considering CNAME blocks to be actionable because I am not blocking whatever the main domain is. CNAME blocking is beyond what hosts files block, and therefore its on the user of this this to maintain whatever whitelists are necessary to account for CNAME based blocks.

**Comment by p1r473** [comment]
Just ran into this too- I do a deep CNAME package inspection, and couldn't visit lifehacker.com due to this.
Highlighted on my end

**Comment by lightswitch05** [comment]
Alright, `*.marfeelcdn.com` is removed!

**Comment by p1r473** [comment]
Thanks! 
Note- I do whitelist these all on my end- just let you know about the ones I see, as other people may use the lists that may not know how to whitelist
So they are always just suggestions!
