### ISSUE TITLE
urldefense.proofpoint.com false positive

### ISSUE THREAD

**Issue by Obihoernchen** [lightswitch05/hosts#133]
`urldefense.proofpoint.com` is used by some companies to "secure" links in mails.
Therefore, you can't click on any link with this list activated.

Please consider removing it

**Comment by lightswitch05** [comment]
After some research, I do see `urldefense.proofpoint.com` being used on websites within advertising and tracking links. However, its not clear that proofpoint itself is doing any tracking or advertising. I'm good with whitelisting this one. Thank you for opening up the ticket!

**Comment by lightswitch05** [comment]
Removed in https://github.com/lightswitch05/hosts/commit/62997ce68ef09cdb9c23c203d1f91733b3b310e4, thank you again for taking the time to bring this to my attention
