### ISSUE TITLE
optanon.blob.core.windows.net breaks Greek Public TV's webTV

### ISSUE THREAD

**Issue by XhmikosR** [lightswitch05/hosts#135]
Hello!

It seems blocking `optanon.blob.core.windows.net` breaks Greek Public TV (ERT) web TV. For example:

https://webtv.ert.gr/ert3/kosmostonspor/27fev2020-o-kosmos-ton-spor/

In the gray header there's supposed to show a video.

**Comment by lightswitch05** [comment]
Thanks for opening up this ticket @XhmikosR. That host, `optanon.blob.core.windows.net` is used for cookie-consent and likely GDPR requirements. I'm going to leave this ticket open for a bit, but I'm inclined to move it to the aggressive list since it is causing problems.

**Comment by XhmikosR** [comment]
@lightswitch05 can you confirm that if you unblock the aforementioned site you also see a video in the gray header?

**Comment by lightswitch05** [comment]
During my testing, the only thing I had to whitelist was `ipinfo.io`

**Comment by XhmikosR** [comment]
You are right. Sorry for the wrong report, it just seemed to work after some testing. `ipinfo.io` is not in your blocklist AFAICT so I'm gonna close the issue.

Thanks for the fast replies!

**Comment by lightswitch05** [comment]
Its in my aggressive list @XhmikosR - incase you use that one

**Comment by XhmikosR** [comment]
Oh, I only use "light" lists so this seems to be coming from:

```
 Match found in https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt:
   ipinfo.io
```

**Comment by lightswitch05** [comment]
Yes, I use that list too, its a good one, but it sounds like you'll want to whitelist that host.
