### ISSUE TITLE
Block Malicious Website Margefrick.com

### ISSUE THREAD

**Issue by Bryantdl7** [lightswitch05/hosts#137]
[margefrick.com](http://margefrick.com) is a redirect site used by popup ads. It will redirect you through multiple sites, landing you on a page trying to get you to download a browser addin or do a survey. 

Depending on the source, it can also spam your browser with login warning to pretend to be a virus.

**Comment by lightswitch05** [comment]
@Bryantdl7 can you give me some more information about that website? For example, provide me with another website that is using `margefrick.com` for ads/links?

**Comment by Bryantdl7** [comment]
I was able to get a pop up while trying out the site https://distillvideo.com/

There’s many more redirects that can happen from this site as I ended up finding out it’s a malicious site in itself it seems, but the site always gives redirects to other scammy sites.

See video attached:

**Comment by lightswitch05** [comment]
Added by https://github.com/lightswitch05/hosts/commit/9ba573c7a8ab39650712d6460d80489332d60f61
