### ISSUE TITLE
Request of reasons that 163.com was blocked

### ISSUE THREAD

**Issue by CodeKiller2** [lightswitch05/hosts#139]
@lightswitch05 

Virus Total reported 163.com is Ultimate Hosts suspicious.

And I found that it was present in three lists. One of them is your list - ads-and-tracking-extended.

Therefore, could you please provide some detailed reasons of this blocking? And what can I do to make you remove 163.com from the list?

Thank you!

**Comment by lightswitch05** [comment]
Added in https://github.com/lightswitch05/hosts/commit/d9b0b050

> Added 126.com from spam email.

**Comment by lightswitch05** [comment]
A lot of comments on the virus total link backs up my above thoughts: https://www.virustotal.com/gui/url/73315ad9015cce7d03c7ee77d7d1986b1307e3fda0ec5b8fc4fa8ff565f190c2/community

**Comment by lightswitch05** [comment]
It looks like `dm.mail.163.com` was the host that the email was linking to and I decided to add `163.com` root based on that and the virustotal results.
