### ISSUE TITLE
Bogus domain at line 23 of ads-and-tracking-extended.txt

### ISSUE THREAD

**Issue by StevenBlack** [lightswitch05/hosts#14]
Hi Daniel, have a look at [line 23](https://github.com/lightswitch05/hosts/blob/master/ads-and-tracking-extended.txt#L23) of `ads-and-tracking-extended.txt`.

`0.0.0.0 3c492da9f102528cdf3922aebf4dab0556b91ae1`

**Comment by lightswitch05** [comment]
Thanks Steven, not sure how that got in there. Removed by https://github.com/lightswitch05/hosts/commit/6a74d7709df5c5a57365ece15ecc74e6682e1569
