### ISSUE TITLE
blogs.360.cn

### ISSUE THREAD

**Issue by scafroglia93** [lightswitch05/hosts#141]
This is the offical blog of 360 security team 
https://twitter.com/360coresec

company -> qihoo

**Comment by lightswitch05** [comment]
Thanks for the report, I will investigate as soon as I get some availability.

**Comment by lightswitch05** [comment]
This was added in https://github.com/lightswitch05/hosts/commit/1a080d3b

Looks like I got the idea to block them from here: https://old.reddit.com/r/Android/comments/ektg8u/chinese_spyware_preinstalled_on_all_samsung/

I think this is something that belongs in the aggressive list instead - so I'll it there.

**Comment by scafroglia93** [comment]
I agree that Chinese apps do datamining but the blog has no problems

**Comment by lightswitch05** [comment]
fixed by https://github.com/lightswitch05/hosts/commit/5a1cda875db5c024b2fe9505854e9732637869f4

Thank you for your comments @scafroglia93!
