### ISSUE TITLE
False Positive: reddit.app.link

### ISSUE THREAD

**Issue by p1r473** [lightswitch05/hosts#144]
On ads-and-tracking-extended.txt 
Domain: reddit.app.link
This domain is used for opening reddit.com browser links in the mobile app.

**Comment by lightswitch05** [comment]
Hello @p1r473 - thank you for opening this ticket.

* `app.link` was originally added by this commit: https://github.com/lightswitch05/hosts/commit/e37627ba
* It was automatically expanded to include `reddit.app.link`. I agree that this is too aggressive, so I will move all of `app.link` into the aggressive list.

**Comment by lightswitch05** [comment]
Fixed by https://github.com/lightswitch05/hosts/commit/f781a4d309eff341136d0d7c72f490569b43bc29

**Comment by lightswitch05** [comment]
oh man, its back! Ugh.... looks like this was auto-added by my new tools. Thanks for letting me know @p1r473 - it looks like `app.link` made it back to the primary list again - I think something went wrong when migrating from my old system to the new system. I'll get this fixed again.

**Comment by lightswitch05** [comment]
Fixed again, thanks!
