### ISSUE TITLE
Some hosts

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#148]
Hi, 

here are some hosts I extracted from this file `https://github.com/ampproject/amphtml/blob/master/ads/_config.js`.

`https://pastebin.com/RyjNDhwr`

FYI there are probably some duplicates that are already in your list, and some hosts that should not be added (like `yastatic.net` or `www.google.com`).

**Comment by lightswitch05** [comment]
I did a quick lookover adding the obvious ones and comparing a few with a couple other trusted lists.
