### ISSUE TITLE
Spot.im breakage

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#149]
Hi, please remove these domains or move them to the aggresive list.

```
launcher.spot.im
api-2-0.spot.im
static-cdn.spot.im
images.spot.im
publisher-assets.spot.im
```

The inclusion of these domains breaks the comment sections on:
```
https://metro.co.uk/2020/03/23/ok-zoomer-zoom-worlds-new-favourite-social-network-12443418/#metro-comments-area
https://www.engadget.com/2020-01-10-gm-hummer-ev-report.html#comments
https://www.seattlepi.com/coronavirus/articleComments/good-news-about-novel-coronavirus-15141530.php
```

and assuredly many more articles.

**Comment by lightswitch05** [comment]
Looks like that was added by https://github.com/lightswitch05/hosts/commit/d9a8b85f

Super lame addition on my part. I'm good with trimming it down to logical subdomains.

**Comment by lightswitch05** [comment]
reduced by https://github.com/lightswitch05/hosts/commit/365fda054f969e309a2b04e686065fbaa935d30a
