### ISSUE TITLE
sendgrid.net

### ISSUE THREAD

**Issue by ArmynC** [lightswitch05/hosts#150]
So I got an E-Mail from an automatically GitHub report system and when I click to see the stats, it goes through this service `||sendgrid.net^`. Is this un-safe enough? [An example report](https://sendgrid.com/wp-content/uploads/pdf/Expert-Insights-Sample.pdf).

**Comment by lightswitch05** [comment]
This is a email tracking company. You are welcome to whitelist them on your side if you use their services.

**Comment by ArmynC** [comment]
Ok, I understand. Thanks!
