### ISSUE TITLE
Can you do a version of your list in AdguardHome

### ISSUE THREAD

**Issue by xxsxx47** [lightswitch05/hosts#151]
Hello There , Hope you are doing fine.

Adguardhome is like pihole 
https://github.com/AdguardTeam/AdGuardHome

here is a tool they made to make a conversion easier
https://github.com/AdguardTeam/HostlistCompiler

Thank you.

**Comment by lightswitch05** [comment]
Hello @xxsxx47. I had a quick look at the links. From what I saw, it looks like my list should already be compatible- it’s just a simple hosts formatted list. Is there anything in particular you are having issues with?

**Comment by xxsxx47** [comment]
There is no problem at all , just thought it wasn't compatible with adguardhome it first tried it now and its working fine .

Thank you much @lightswitch05 .
