### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#152]
Hi, 

please remove `0.0.0.0 stats.gc.apple.com`. `*.gc.apple.com` domains are used for Game Center on iOS and MacOS.

This domain is used for game stats (synchronization of high scores, achievements, etc). I cannot find this domain listed anywhere, but if you have an iOS device you should be able to verify this (high scores will not sync).

Tangentially related links:
```
http://www.mark-anderson.me/blog/gamed-wants-to-connect-to-staticgcapple-make-this-go-away
https://apple.stackexchange.com/questions/245483/little-snitch-does-restricting-address-port-for-an-application-disable-future-c
```

**Comment by lightswitch05** [comment]
Thanks for the report. I don’t play games on my phone- but still see this domain making requests- so I think it might be more then just high scores. But I’m good with moving it to the aggressive list. 👍

**Comment by lightswitch05** [comment]
Moved to aggressive list in https://github.com/lightswitch05/hosts/commit/a59587cd55ab712463108007eb99f78f4ee58a81

**Comment by llacb47** [comment]
Here's some evidence from Burp suite. These requests were made when I opened the game Doodlejump.

![image](https://user-images.githubusercontent.com/16567977/78071144-f907ff80-736a-11ea-8cb6-59864601fb8f.png)

**Comment by lightswitch05** [comment]
Nice info, thanks for the followup @llacb47 !
