### ISSUE TITLE
Firebase inclusion?

### ISSUE THREAD

**Issue by RejZoRSheep** [lightswitch05/hosts#154]
I've noticed quite a bit of Firebase (Google) entries in my NextDNS gateway for mobile devices logs that are not blocked by lightswitch05 list used there:

firebaseinstallations.googleapis.com
firebaselogging.googleapis.com
firebaselogging-pa.googleapis.com

Are these excluded on purpose (not a part of lightswitch05 scope) or just not included yet?

**Comment by lightswitch05** [comment]
Just not included. I'm not sure `firebaseinstallations.googleapis.com` fits in my list. 

> The Firebase Installations API (currently in limited beta release) provides identifiers, authentication scheme, and GDPR deletion for installations of Firebase applications. Many Firebase services depend on the Firebase Installations API in order to identify app installs and/or authenticate client requests to their servers.

I'll add the other two now

**Comment by lightswitch05** [comment]
Thanks for the info! Added by https://github.com/lightswitch05/hosts/commit/32bf226ba131aee6c6895948443e100750b61d82
