### ISSUE TITLE
False Positive: financialprovider-logos.platform.intuit.com

### ISSUE THREAD

**Issue by p1r473** [lightswitch05/hosts#158]
* False positive?

This domain is used for showing logos of financial providers on the Mint platform. With this domain blocked, the logo doesn't show up.
![image](https://user-images.githubusercontent.com/9235633/79177983-0218b800-7dd2-11ea-9c91-8aa832bbd371.png)

* New domains to block?

Log into Mint and go to https://mint.intuit.com/settings.event?filter=all Next to the Financial Institutions,  the logos will not display with this domain blocked.

**Comment by lightswitch05** [comment]
I was thinking these were also used for the in-app ads like credit card offers. After double checking, it seems all those come from `offcnt.intuit.com`. I'm good with removing this block. Thanks for the report!

**Comment by lightswitch05** [comment]
Fixed in https://github.com/lightswitch05/hosts/commit/d2fa900830fe9f92b7d8113d4b70b3fbc9660450

**Comment by p1r473** [comment]
Thanks! Appreciated
