### ISSUE TITLE
Add Title: lightswitch05/<list> to each list

### ISSUE THREAD

**Issue by lightswitch05** [lightswitch05/hosts#16]
Adding `Title: lightswitch05/<list>` within a comment in a list will allow for a pretty display in uBlock origin

**Comment by lightswitch05** [comment]
closed by 0c836d328ac7ba1a19f7c440a2d5c8eb068d1ceb

**Comment by dnmTX** [comment]
@lightswitch05  you interested adding some livecams-advertisement(who knows what other shit they provide) domains. XHamster is using them for advertisement.I know it's probably not the typical domains you dealing with(it's basically on the porn side,but can't be added to the porn extension,no point) so i'm  asking first.They still ads though,nevertheless.Let me know.

**Comment by dnmTX** [comment]
@lightswitch05  thanks. If you don't mind i'll paste them here(they're not that many).A little history: basically not all of them are "in use" but you block couple that are and and it's loading others.That's how i managed to track most of them.Here you go:

`# stripcdn (xhamster-livecam-ads)
0.0.0.0 c-eu1.stripcdn.com
0.0.0.0 c-eu2.stripcdn.com
0.0.0.0 c-eu3.stripcdn.com
0.0.0.0 c-eu4.stripcdn.com
0.0.0.0 c-eu5.stripcdn.com
0.0.0.0 c-eu8.stripcdn.com
0.0.0.0 b-eu4.stripcdn.com
0.0.0.0 b-eu5.stripcdn.com
0.0.0.0 b-eu6.stripcdn.com
0.0.0.0 b-eu8.stripcdn.com
0.0.0.0 b-eu9.stripcdn.com
0.0.0.0 b-eu10.stripcdn.com
0.0.0.0 b-eu15.stripcdn.com
0.0.0.0 c-us1.stripcdn.com
0.0.0.0 c-us2.stripcdn.com
0.0.0.0 c-us3.stripcdn.com
0.0.0.0 c-us4.stripcdn.com
0.0.0.0 c-us5.stripcdn.com
0.0.0.0 c-us8.stripcdn.com
0.0.0.0 hls.stripcdn.com
0.0.0.0 hls-us2.stripcdn.com
0.0.0.0 img.stripcdn.com
0.0.0.0 img-eu.stripcdn.com
0.0.0.0 ns1.stripcdn.com
0.0.0.0 ns2.stripcdn.com
0.0.0.0 ns3.stripcdn.com
0.0.0.0 ns4.stripcdn.com
0.0.0.0 ns1.edgecastdns.net
0.0.0.0 ns2.edgecastdns.net
0.0.0.0 ns3.edgecastdns.net
0.0.0.0 ns4.edgecastdns.net
0.0.0.0 p0.stripcdn.com
0.0.0.0 p1.stripcdn.com
0.0.0.0 p-us1.stripcdn.com
0.0.0.0 video-thumbs.stripcdn.com
0.0.0.0 p-eu4.stripcdn.com
0.0.0.0 cs905.wac.systemcdn.net
0.0.0.0 st.stripcdn.com
# optional (can be added as it's super annoying)
0.0.0.0 go.xhamsterlive.com
0.0.0.0 xhamsterpremium.com`

👍

**Comment by lightswitch05** [comment]
@dnmTX I added all except `xhamsterpremium.com` since that one seems to block an actual service instead of just ads. Just open a ticket if you need further changes 👍 

Just a heads up, if someone complains about these domains breaking things over at https://github.com/StevenBlack/hosts - then I'll have to move them to my aggressive list which isn't included in steven's project

**Comment by dnmTX** [comment]
@lightswitch05 

> Just a heads up, if someone complains about these domains breaking things over at https://github.com/StevenBlack/hosts - then I'll have to move them to my aggressive list which isn't included in steven's project

No worries.No one would miss those suckers. 😀

**Comment by dnmTX** [comment]
@lightswitch05  you can add `ssc.independent.co.uk`. Yahoo(probably others as well) are using it to redirect to `*.scorecardresearch.com` domains,which i'm guessing are either tracking or telemetry(you have some in your lists).Found it on Yahoo.

**Comment by lightswitch05** [comment]
@dnmTX yup, `ssc.independent.co.uk` is just a redirect to `independent.co.uk.ssl.sc.omtrdc.net`. I'll add both in my next update


```
ssc.independent.co.uk.	7200	IN	CNAME	independent.co.uk.ssl.sc.omtrdc.net
```

**Comment by dnmTX** [comment]
@lightswitch05  yep,it's redirect but it's good to be blocked as well.Thanks for adding it.
This is the link that Yahoo was using to redirect to `sb.scorecardresearch.com`:
https://ssc.independent.co.uk/b/ss/indepdev/1/H.27.5--NS/0?c25=8537456

**Comment by dnmTX** [comment]
@lightswitch05  what's with `syndication.twitter.com`? How bad is it? Reason i'm asking is i got like 100 blocked request while browsing Yahoo for a couple minuets.The problem is that many blocked request for that short of a time are just filling up the dns cache and there is no option under windows not to cache the blocked ones. Eventually browsing starting to slow down unless you clean the cache.

**Comment by lightswitch05** [comment]
I think its just ads. You might want to look into getting a PiHole. Its a lot easier and more efficient then these hosts blocks, especially on windows

**Comment by dnmTX** [comment]
I'm using my router for that(it has dnsmasq).dnsmasq doesn't cache the blocked ones but Windows does,regardless.

**Comment by lightswitch05** [comment]
Oh I understand what you mean. It must be annoying to lose your cache like that. But with your router having dnsmasq, your latency for any cached ones must be in the single millisecond range. Thats pretty fast. Also, browsers have a cache of their own for a couple minutes regardless of what the DNS timeout settings are and the system

**Comment by dnmTX** [comment]
It's ok.I'll remove them on my end.
Yeah,with dnsmasq everything is flying fast,using several hosts files(almost 100.000 blocked domains) and there is not even a slight slow down.
Windows is set to cache the negative request for at least 15 min and you can't change or disable it.That's where the problem is.

**Comment by XelNika** [comment]
@lightswitch05 
Blocking *.stripcdn.com breaks xhamsterlive.com completely. They don't just serve live cam ads, they serve the cam video streams too. Perhaps they belong in a porn list instead?

**Comment by lightswitch05** [comment]
@XelNika sound fair enough to me. @dnmTX you have any comments before I make this change?

**Comment by dnmTX** [comment]
Well....not that i'm happy about it so i'll leave it to you @lightswitch05  to decide.
@XelNika just to clarify,the reason i asked to be added here is because they serve banner ads and are extremely aggressive.And no,they don't belong to **a porn lists** as again....they do serve ads.
@lightswitch05  i'll follow up on this and if you decide to remove them i'll add them to my personal list. It's not a big deal to me,it's just,whoever is using the lists here will be exposed to those ads from now on.

**Comment by XelNika** [comment]
> i asked to be added here is because they serve banner ads and are extremely aggressive

I understand, but a hosts list is a very coarse way to block content. If you use a browser extension like uBO, you could fix the banner ads while still allowing the domains on their parent sites with an ABP-style filter along the lines of `||stripcdn.com^$domain=~xhamsterlive.com|~stripchat.com`.

> And no,they don't belong to a porn lists,such a lists block the entire site(s),not just the ads in them.

Well, as I said, some of them (specifically b-eu*.stripcdn.com in my case) are clearly serving the cam feeds on xhamsterlive.com and stripchat.com. You could argue that it makes more sense to block xhamsterlive.com and stripchat.com if you just wanted to block the porn, but stripcdn.com does in fact serve porn. Are _all_ the domains you listed serving ads? Perhaps we could find a middle ground?

**Comment by lightswitch05** [comment]
I did a search of other hosts, and mine is the only blocking this. I have no doubt it’s being used to serve ads as well as content. It’s a CDN, and those are often used to serve both. I’m just on my phone at the moment, so no changes yet, but I’m still under the impression it should be removed from the list. CDNs make this stuff difficult.

**Comment by dnmTX** [comment]
It looks like it's a live or death situation for @XelNika to not be able to watch live porn cams so just remove them. For such a thing,in this case porn cams(and all the garbage that comes with it) i'll definitely not gonna waist mine or anyone else's time debating over it.
Live is too short,i'll just add them to my personal list and be done with it.
@lightswitch05  thanks for the great job you doing here,your lists here are the most relevant to me.
Keep up the good work man and enjoy the weekend 👍

**Comment by XelNika** [comment]
> It looks like it's a live or death situation for @XelNika to not be able to watch live porn cams

Poe's law.

> If you find something in a list that you believe is a mistake or **breaks functionality**, please open a ticket and I'll consider removing it

I found broken functionality and I reported it. This isn't really about my Asian midget camgirl fetish, it's about improving the list.

**Comment by dnmTX** [comment]
Hey @XelNika you **WON**,those domains will be removed.Move on,go watch your porn fetish and keep on believing that your "contribution" improving anything.
