### ISSUE TITLE
Possible false positive pdst.fm

### ISSUE THREAD

**Issue by lightswitch05** [lightswitch05/hosts#160]
see: https://github.com/anudeepND/whitelist/issues/137

**Comment by lightswitch05** [comment]
`cdn.pdst.fm` was added due to `https://cdn.pdst.fm/ping.min.js` coming from `https://www.joinhoney.com/`

**Comment by lightswitch05** [comment]
@sew3521 can you provide me more details about your issues with `pdst.fm`? Is it with `pdst.fm` exactly? Or is it with a subdomain like `cdn.pdst.fm`? Its certainly being used for tracking. Can you provide me with details on how to reproduce the issue you are having?

**Comment by sew3521** [comment]
Hey @lightswitch05 ,
I just looked at my Pi-Hole logs and it looks like the domain that is being requested is pdst.fm. I have since Whitelisted it on my end and all my podcasts are downloading without issue again.

**Comment by lightswitch05** [comment]
@sew3521 thanks for the info. I'll whitelist the root domain `pdst.fm` and leave the tracking domain `cdn.pdst.fm` blocked.

**Comment by lightswitch05** [comment]
Fixed in https://github.com/lightswitch05/hosts/commit/103e3421999a1b52bc4cb730f4a79f20ea34b589
