### ISSUE TITLE
Inclusion of adserver.livenetlife.com

### ISSUE THREAD

**Issue by RejZoRSheep** [lightswitch05/hosts#162]
Noticed a lot of these entries in my logs that don't seem to be blocked by lightswitch05. Please check if it's eligible for inclusion.

There seem to be a lot of connections to:
adserver.livenetlife.com
bin.livenetlife.com
engine.livenetlife.com
engineX.livenetlife.com (where X is a number)

But I don't think these are a problem. I also can't seem to quite figure out yet what app or service is connecting to these exactly, but there is a lot of entries in the logs. adserver one is pretty obvious tho.

**Comment by lightswitch05** [comment]
Who knows where you are seeing it from, but I've found it on `http://videolectures.net/`. Not a great website, doesn't even support `https` properly and requires flash to run. I've found `http://engine.livenetlife.com/Ping.aspx`.

I'll add `engine.livenetlife.com` and `adserver.livenetlife.com`
