### ISSUE TITLE
intercomcdn.com / intercom.io

### ISSUE THREAD

**Issue by p1r473** [lightswitch05/hosts#167]
Hi, 
I belive intercomcdn.com/intercom.io is a false positive
Intercom provides in-app "chat support" for many companies/apps. Many websites that have a "chat with support" or help feature utilize Intercom to deliver customer service.
Without access to these comains , the support pages are very broken
To test, download the Koho app, go to chat with support, and see all of the broken pages in the app.

**Comment by lightswitch05** [comment]
I think intercom is a bit tricky since they serve a lot of different purposes. I'm 100% sure they do tracking. Perhaps its a better fit for aggressive.... anyone else want to chime in?

**Comment by anudeepND** [comment]
Yes, they track visitors (I have setup intercom chat for a client). You can read more about tracking here:

https://www.intercom.com/help/en/articles/320-tracking-user-data-in-intercom

https://www.intercom.com/help/en/articles/216-track-events-in-intercom

**Comment by p1r473** [comment]
Whitelisted on my end

**Comment by zappe** [comment]
> Yes, they track visitors (I have setup intercom chat for a client). You can read more about tracking here:
> 
> https://www.intercom.com/help/en/articles/320-tracking-user-data-in-intercom
> 
> https://www.intercom.com/help/en/articles/216-track-events-in-intercom

Maybe only blacklist those domains they use for tracking?
Right now everything Intercom is blocked.

**Comment by p1r473** [comment]
I agree with Zappe, same as the other domains such as maxmind, i think blocking every subdomain is a bit extreme, when we can just blacklist the tracking domains (just geoip-js.maxmind.com from #163).

**Comment by lightswitch05** [comment]
Thanks for the feedback everyone. My last comment on this ticket was asking for feedback and I really appreciate it. I’m not the one who closed this ticket. I haven’t had the time to investigate and make a decision on it yet.

I’m making a lot of progress on my new API to help me manage this list. Between that and other personal things going on, my time in front of a computer is very limited and I can only do so much from my phone.

Besides it being completely off topic for this ticket, I currently have 0% interest in removing things from the aggressive list.

**Comment by lightswitch05** [comment]
That is great that nextdns is using a tracker to provider support. I hate those chat bot windows everywhere, but I've been convinced to move these to the aggressive list.

**Comment by crssi** [comment]
>That is great that nextdns is using a tracker to provide support.

Totally agree with you. I also do not understand, since they state that they do not track anything.

I do not insist to make any changes, I am just reporting what I see.

Cheers

**Comment by lightswitch05** [comment]
Moved to the aggressive list.

Nextdns probably:
> We don't track you! (but we allow 3rd parties to do whatever they want - be sure to read their privacy policy that you've implicitly agreed to just by visiting our website!)

**Comment by lightswitch05** [comment]
Actually.... looking at NextDNS's privacy policy: https://nextdns.io/privacy

I'm pretty sure they are in violation of GDPR for not listing what 3rd parties they use and what services they provide. I don't live in the EU, but if someone is using NextDNS and lives in the EU, I think their rights are being violated. The website is also using cookies, and I don't see any cookie banner warnings. Not that I think NextDNS is doing anything shady - but for a company that has access to your entire DNS history to be integrating with 3rd parties and not disclosing what those 3rds parties are and what services they provide, that is certainly not good in terms of GDPR.
