### ISSUE TITLE
*.monday.com

### ISSUE THREAD

**Issue by erikvb** [lightswitch05/hosts#168]
There are a number of blocks on monday.com and its subdomains, rendering https://monday.com/ useless (project management site)

**Comment by lightswitch05** [comment]
Thanks for the report @erikvb! I’m unfortunately away from the computer for a few days, but I’ll get this fixed as soon as I am able to

**Comment by lightswitch05** [comment]
Removed @erikvb! Thank you again for the report, sorry about the late response.
