### ISSUE TITLE
Additional FB Domain missing

### ISSUE THREAD

**Issue by jorong1** [lightswitch05/hosts#169]
Hi I read your intro but I have found one extra URL for FB/IG that slipped through.
Here is the Pi-Hole logs from yesterday
> A	scontent.fyto1-1.fna.fbcdn.net	OK (forwarded)	IP (291.7ms)	
AAAA	scontent.fyto1-1.fna.fbcdn.net	OK (forwarded)	IP (290.5ms)

which resolves to
> scontent.fyto1-1.fna.fbcdn.net.	3 IN	A	209.148.160.17

To reproduce my steps are:
1. Connect to Toronto, Canada IP
2. Open IG/FB Android App
3. Check Pi-Hole DNS logs

But that URL does not appear as often as other FB/IG URLs. Since I had facebook-extended.txt loaded, maybe FB used this URL as a workaround.

Thank you for all your efforts on theses lists, they are invaluable.

**Comment by lightswitch05** [comment]
Thanks! I’ll get it added as soon as I can

**Comment by lightswitch05** [comment]
Added! Thanks again for the report @jorong1 !
