### ISSUE TITLE
Blocking discordapp.page.link prevents discord invitation acceptance

### ISSUE THREAD

**Issue by crssi** [lightswitch05/hosts#172]
Blocking discordapp.page.link prevents accepting discord invitation.

Cheers and thank you

**Comment by lightswitch05** [comment]
Hi @crssi, thanks for the report. It looks like I do not block `discordapp.page.link`, but I do block the root domain `page.link`. After some research, I agree this is too aggressive and should be moved to the aggressive list. I’ll make this change in my next update. Thanks again for the report!

**Comment by crssi** [comment]
Thank you for taking care. 😄
