### ISSUE TITLE
Additional WhatsApp Domain

### ISSUE THREAD

**Issue by simonlenton** [lightswitch05/hosts#173]
I appreciate that you're not generally looking for this type of issue to be raised; however, in the same vein as #169, I've discovered a whatsapp domain that isn't listed in the facebook-extended list. 

From Pihole:
> A | wa.me | OK (forwarded) | IP (0.5ms)
> AAAA | wa.me | OK (forwarded) | IP (0.4ms)

Which resolves to:
> ;; ANSWER SECTION:
> wa.me.                  33      IN      A       157.240.14.52

Using dig to investigate further, the NS for the domain are:
> ;; AUTHORITY SECTION:
> wa.me.                  300     IN      SOA     a.ns.whatsapp.net. dns.whatsapp.net.  [...]

To reproduce:
Using the whatsapp FAQ example (linked below)
[Click to Chat](https://wa.me/15551234567?text=I'm%20interested%20in%20your%20car%20for%20sale)

Further information on this from whatsapp:
[WhatsApp's click to chat feature](https://faq.whatsapp.com/en/android/26000030/)

And looking up on a Whois tool:
https://whois.domaintools.com/wa.me

Genuinely appreciate your lists!

**Comment by lightswitch05** [comment]
This is great @simonlenton! I’ll get it added as soon as I’m able. The non-suggestions comment is really about Ad and tracking hosts since they take so much time to verify. I am very happy to take suggestions for the Facebook and AMP hosts lists. Thanks again!

**Comment by lightswitch05** [comment]
Added, thanks for the contribution!
