### ISSUE TITLE
False positive CNAME

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#174]
Hi,

the inclusion of `mi.edgekey.net` in this list blocks visiting any McClatchy newspaper site on PiHole v5.0, which introduces the feature of CNAME blocking.

The following domains have a CNAME of `mi.edgekey.net`:
```
bellinghamherald.com
bnd.com
bradenton.com
centredaily.com
charlotteobserver.com
elnuevoherald.com
fresnobee.com
heraldonline.com
heraldsun.com
idahostatesman.com
islandpacket.com
kansas.com
kansascity.com
kentucky.com
ledger-enquirer.com
macon.com
mcclatchydc.com
mercedsunstar.com
miamiherald.com
modbee.com
myrtlebeachonline.com
newsobserver.com
sacbee.com
sanluisobispo.com
star-telegram.com
sunherald.com
thenewstribune.com
theolympian.com
thestate.com
tri-cityherald.com
```

Thanks.

**Comment by lightswitch05** [comment]
Huh. Added in: https://github.com/lightswitch05/hosts/commit/057cee1987478df5db8d12bf9e627477d3d4ae46

Not a helpful message. I have mixed feelings about CNAME blocking, but I’m fine with removing this one.

**Comment by lightswitch05** [comment]
removed, thanks!
