### ISSUE TITLE
False positive minutemaidcdn.com

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#176]
Hi, please remove these false positives:

```
minutemediacdn.com 
assets.minutemediacdn.com 
error-page.minutemediacdn.com 
images0.minutemediacdn.com 
images1.minutemediacdn.com 
images2.minutemediacdn.com 
media.minutemediacdn.com 
media3.minutemediacdn.com 
static.minutemediacdn.com 
widgets.minutemediacdn.com 
```

It is a CDN for Minute Media (`https://www.minutemedia.com/`) and blocking it breaks:

-images and layout on `https://www.mentalfloss.com/article/49935/10-very-costly-typos` and all mental floss articles
-images on `https://www.thebiglead.com/roundup` and all subcategory pages on the site
-layout and images on `https://www.90min.com/`

**Comment by lightswitch05** [comment]
Thanks, looks like you are right. Added in 610a42ddf59f53a71ac2ea337de3c18a02f327db

**Comment by lightswitch05** [comment]
Fixed, thanks for the report!
