### ISSUE TITLE
CNAME issues

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#178]
Hi, there are some CNAMEs included in your list causing breakages/false positives.

Related: https://github.com/lightswitch05/hosts/issues/132 (I encountered this as well)

`dualstack.brightcove.map.fastly.net` is CNAME of `manifest.prod.boltdns.net`
`dualstack.us-eu.brightcove.map.fastly.net` is CNAME of `house-fastly-signed-eu-west-1-prod.brightcovecdn.com`
`brightcove.map.fastly.net` is CNAME of `f1.media.brightcove.com`

`cloudenhanced.qualtrics.com.edgekey.net` is CNAME of `google.qualtrics.com`, `education.co1.qualtrics.com`, etc.

**Comment by lightswitch05** [comment]
I'm good with removing the the brightcove ones. But to me, it looks like the `qualtrics.com` blocks is valid. Can you explain to me what is wrong with blocking it?

**Comment by llacb47** [comment]
Voluntary surveys:
`https://google.qualtrics.com/jfe/form/SV_3eNnjG89r4ObBfn`
`https://education.co1.qualtrics.com/jfe/form/SV_1B9R7XJa9dXaQBv`

**Comment by lightswitch05** [comment]
I removed `*.brightcove.map.fastly.net` and `*.marfeelcdn.com`.

`qualtrics.com` does a lot of tracking on a lot of websites as a 3rd party. I think is going to have to be an `opt-in` deal where you need to whitelist it on your side if you want to fill out the survey. We can leave the ticket open for a while to see if anyone else wants to add their opinion.

**Comment by ACMEd** [comment]
Recently, I also had to fill out a form which was on a `*.qualtrics.com` sub domain.
Is there any evidence that these subdomains serve 3rd party tracking?

**Comment by lightswitch05** [comment]
Yes, there is a LOT of evidence of that: https://publicwww.com/websites/%22siteintercept.qualtrics.com%22/

**Comment by lightswitch05** [comment]
Perhaps I will leave the siteintercept junk in the main list and move the other domains to the aggressive list. They are certainly a well known 3rd party tracker.

**Comment by ACMEd** [comment]
What I mean is, is there any evidence that the subdomains _which are used for forms_ serve 3rd party tracking? For example, `*.az1.qualtrics.com` appears to only be used for forms, not for serving content in the third party.
https://publicwww.com/websites/%22az1.qualtrics.com%22/
Of course, this means figuring out which subdomains aren't used for this purpose.

**Comment by lightswitch05** [comment]
Moved all qualtrics domains that don't match `'*siteintercept.qualtrics.com'` to the aggressive list.

**Comment by llacb47** [comment]
> Moved all qualtrics domains that don't match `'*siteintercept.qualtrics.com'` to the aggressive list.

Awesome, thank you.

**Comment by ler762** [comment]
> Moved all qualtrics domains that don't match ...

``siteintercept.qualtrics.com`` sites are in both the normal and aggressive lists:

```
$ grep 'siteintercept.qualtrics.com$' ads-and-tracking-extended.txt | wc -l
694

$ grep 'siteintercept.qualtrics.com$' tracking-aggressive-extended.txt | wc -l
694
```

**Comment by lightswitch05** [comment]
Ok fair enough, what I said wasn’t 100% correct. What I actually did was move all the domains to the aggressive list- and then cloned the siteintercept ones back to the main list.

**Comment by ler762** [comment]
> Ok fair enough, what I said wasn’t 100% correct. What I actually did was
> move all the domains to the aggressive list- and then cloned the
> siteintercept ones back to the main list.

Are the normal and aggressive lists supposed to be unique?
In other words, if I'm using both lists do I need to de-duplicate when
combining them?

**Comment by lightswitch05** [comment]
@ler762 if you are using the list with a Pihole, then it is de-duping it for you, no need for you to do anything else.

**Comment by ler762** [comment]
> @ler762 if you are using the list with a Pihole, then it is de-duping it for
> you, no need for you to do anything else.

Nope - using the list with privoxy, so I need to de-dup everything myself.

**Comment by lightswitch05** [comment]
That sucks. Follow #191, I’ll see what I can do.

**Comment by ler762** [comment]
> That sucks. Follow #191, I’ll see what I can do.

Thank you!  I was wondering how to tell if a host belonged in the
normal or aggressive list..
