### ISSUE TITLE
dualstack.brightcove.map.fastly.net dualstack.us-eu.brightcove.map.fastly.net

### ISSUE THREAD

**Issue by p1r473** [lightswitch05/hosts#180]
Hey Dan,
These domains are in the aggresive list.
Just FYI, they are blocking New York Post embedded videos
I have whitelisted on my end, justalerting you FYI.
Thanks, and keep up the great work.

**Comment by llacb47** [comment]
https://github.com/lightswitch05/hosts/commit/5ed0dca25cb9ed692b49685f6782eea4192b7e00

**Comment by lightswitch05** [comment]
Already fixed

**Comment by p1r473** [comment]
Thank you sir!
