### ISSUE TITLE
amzn.to

### ISSUE THREAD

**Issue by p1r473** [lightswitch05/hosts#181]
Hi Dan,
amzn.to is Amazon's URL shortener service.
However, it is on your aggresive list. I have whitelisted on my end, but just thought I'd let you know FYI.

**Comment by lightswitch05** [comment]
Added in 1b54d4767f9c71e5238218c7462dc99057bd9e20

Notes: Added amzn.to to the aggressive list, its being used by an app on my phone - perhaps Rise Up

I think I’ll keep it for now since it’s already aggressive.

**Comment by p1r473** [comment]
Thanks Dan, no prob!
