### ISSUE TITLE
Windows 10 endpoint false positive

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#182]
Hi,

please remove these domains from your list.
```
0.0.0.0 dmd.metaservices.microsoft.com
0.0.0.0 download.dmd.metaservices.microsoft.com
0.0.0.0 origin-download.dmd.metaservices.microsoft.com
0.0.0.0 packages.dmd.metaservices.microsoft.com
```

They are used for device metadata on Windows. 

See: `https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints#device-metadata`

Related:
```
https://github.com/anudeepND/blacklist/issues/33
https://www.istartedsomething.com/20090605/admiring-windows-7s-high-resolution-device-icons/
```

**Comment by XhmikosR** [comment]
@lightswitch05 it seems `packages.dmd.metaservices.microsoft.com` is again in the list through `packages.dmd.metaservices.microsoft.com.akadns.net`
