### ISSUE TITLE
False Positive:  download.db-ip.com #qbittorrent ip geo-location data

### ISSUE THREAD

**Issue by rugabunda** [lightswitch05/hosts#184]
This website offers clients geo-ip data to determine the country associated with an IP; For example, Qbittorrent connects to this domain on startup to download the GOIP list if "resolve peer countries" is enabled under advanced settings; qbittorrent can then associate IP addresses with countries for personal security. It does not pose a privacy or security threat to clients, it can actually help people to implement security or geographically isolated blocking.  

Qbittorrent downloads a small file for offline use that includes all the data necessary  and does not send any data to download.db-ip.com

**Comment by lightswitch05** [comment]
I'm good with moving the `download` subdomain to the aggressive list

**Comment by lightswitch05** [comment]
Fixed, thanks for the report and detailed explanation!

**Comment by rugabunda** [comment]
> 
> 
> Fixed, thanks for the report and detailed explanation!

Greatly welcome, thank you for creating such an awesome list! Keep up the great work!
