### ISSUE TITLE
Queryly's search function

### ISSUE THREAD

**Issue by ACMEd** [lightswitch05/hosts#185]
Blocking `www.queryly.com` breaks the search function on websites that use it.
https://publicwww.com/websites/%22www.queryly.com%22/
Also see "Our customers" at https://www.queryly.com/

[CNBC](https://www.cnbc.com/) is a bit different because it requires both `fm.cnbc.com` and `api.queryly.com` in order for it's "search quotes" bar to work. (See AdAway/adaway.github.io#83)

Queryly states [on their own website](https://www.queryly.com/) that they perform analytics, so it should stay on the aggressive list at a minimum.

**Comment by lightswitch05** [comment]
Yeah I felt this was a bit aggressive when I added it, but I also wasn’t seeing any broken functionality. Just from a quick test, this website shows up as using them and the search is working fine:


https://www.popularwoodworking.com/?s=Test

I’m fine with moving the `www` subdomain to the aggressive list, but I would like to verify a broken site first that isn’t as already messed up as CNBC is.

**Comment by lightswitch05** [comment]
Looks like the `www` and `api` subdomains are both needed on https://www.fastcompany.com

**Comment by lightswitch05** [comment]
Removed `queryly.com`, `api.queryly.com`, `search.queryly.com`, and `www.queryly.com`.

**Comment by ACMEd** [comment]
Do you plan on adding those domains to the aggressive list?

**Comment by lightswitch05** [comment]
I wasn’t planning on it

**Comment by lightswitch05** [comment]
@ACMEd sorry, I missed the part where you asked about `fm.cnbc.com`. I just looked at it and its loading `https://fm.cnbc.com/applications/cnbc.com/resources/search/cnbc-queryly-search-2020_R02.js` - per this ticket, its required, so I will remove it from the list.
