### ISSUE TITLE
telemetry-in.battle.net

### ISSUE THREAD

**Issue by MajsterMechazod** [lightswitch05/hosts#186]
I noticed this in my logs. It just seems telemetry. Blocking this doesn’t cause any problems with the game client or any Blizzard game. 

Please add to the list possible.

**Comment by lightswitch05** [comment]
I generally like to be able to test new requests, and since I do not have Blizzard, I cannot test this one. However, given the name, it seem obvious enough. Will be included in my next update. Thanks!

**Comment by beerisgood** [comment]
Telemetry isn't bad by default.
Without they can't get necessary data to fix problems

**Comment by lightswitch05** [comment]
@beerisgood you are welcome to opt-in to whatever Telemetry you believe is useful.

Per your Github profile, you live in Germany, so you have strong government regulations about what type of data can be collected and how it can be used. Given GDPR requirements, you have a reasonable expectation that Telemetry will not be sold, 'enriched' with more data from other sources, and then used to target you. Here in the USA, we have no such protections.

**Comment by beerisgood** [comment]
Valid points.
Fully agree with you

**Comment by p1r473** [comment]
Agreed, add this domain to block!

**Comment by lightswitch05** [comment]
Thanks for your comment @p1r473 - I agree too - it was added in 7208252cb66ca8877484e606e2afefc34dc71eb1

**Comment by MajsterMechazod** [comment]
@lightswitch05 - **Goodbye Ads** added `geo.battle.net`. What do you think to add to your list?
