### ISSUE TITLE
Anvato false positive

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#187]
Another anvato false positive: `anvato-api-config.s3.amazonaws.com`

This breaks playing videos in the NBC apple tv app. Related: https://github.com/lightswitch05/hosts/issues/89

**Comment by lightswitch05** [comment]
Added in 7e4199609c9ca18463bc01f8d93f4fc8e6c75e4a - Aug 2018! Removing in next update. Thanks for the report!

**Comment by llacb47** [comment]
forgot `www.anvato-api-config.s3.amazonaws.com`
