### ISSUE TITLE
Guce domain breakage

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#188]
This domain `guce.huffpost.com` breaks visiting `huffpost.com`, because of how Verizon Media
 have set up their stupid cookie consent system. On any Verizon Media
 site, on your first visit from that IP/device in a year (?), you will be redirected to the `guce` subdomain. If you are in a place with no privacy laws, you will be redirected back to your destination. If you are in EU, you will be redirected to `consent.yahoo.com` to give consent for cookies to be placed. Otherwise you will not be able to visit any Verizon Media sites. This is hard to reproduce, as they keep track of it server-side I think.

Other sites where this may occur:
```
aol.com
aol.ca
aol.co.uk
engadget.com
compuserve.com
isp.netscape.com
huffingtonpost.ca
huffingtonpost.co.uk
huffingtonpost.com.au
rivals.com
techcrunch.com
verizonmedia.com
yahoo.com
```

**Comment by lightswitch05** [comment]
Thanks for the info, I'll keep an eye on it. Maybe someone else will have some more information to provide

**Comment by llacb47** [comment]
`aol.co.uk` is even worse, it redirects to `https://guce.advertising.com/collectIdentifiers`...

Stupid Verizon

**Comment by lightswitch05** [comment]
Thanks for the follow up @llacb47 - really A+ feedback. So the ask here is to whitelist both `guce.advertising.com` and `guce.huffpost.com`?

**Comment by llacb47** [comment]
Yep, think so

**Comment by lightswitch05** [comment]
Whitelisted!

**Comment by llacb47** [comment]
Thanks!
