### ISSUE TITLE
Consider removing experience.tinypass.com from main list

### ISSUE THREAD

**Issue by pkactual** [lightswitch05/hosts#189]
The main list includes experience.tinypass.com which is used for logins on some major sites - one example is The Economist (https://www.economist.com/). Without tinypass it bumps you back out of your account.

Per your request above, I did a bit of digging and found it was removed from another ad blocking list for similar reasons:

https://github.com/AdAway/adaway.github.io/commit/8f0be57656ae152f2a1f8a1961d73b1fd1595aae

For your consideration, Cheers, -Pk

**Comment by lightswitch05** [comment]
hmmm, how sure are you that `experience.tinypass.com` is the one causing the issue? I see `sstats.economist.com` on the login page - which isn't directly blocked in my list (yet) - but its just a CNAME for `economist.com.102.122.2o7.net` - which is in my list. So if you are using a blocker that is able to blocked CNAME's, then its the same as having `sstats.economist.com` in the list. `sstats.economist.com` is on the actual login page.

**Comment by llacb47** [comment]
I'm pretty sure it's tinypass. Tinypass is used for paywalls and subscriptions. That `2o7` domain is Omniture tracking. Personally I block tinypass as it blocks a ton of paywalls.

**Comment by lightswitch05** [comment]
Yes, I agree that Tinypass is generally required, but this is the first time I've ever heard of `experience.tinypass.com` being needed. I believed that was solely a telemetry/analytics subdomain and was safe to block without side effects.

I might add all of Tinypass to the aggressive list.

**Comment by llacb47** [comment]
Related: #66 #98

**Comment by lightswitch05** [comment]
Still not sure what I'm going to do about this one. Lets leave it open and see if anyone else reports the same issue. No offense @pkactual - but you have a new account and this is your very first report of something that I'm not able to independently verify. For reference, it was added to my list in Jul, 2018 (a4a51562d66ae7173fc75ea1b56874a58456dcae) and this is the first time I'm hearing complaints about it.

**Comment by pkactual** [comment]
> Still not sure what I'm going to do about this one. Lets leave it open and see if anyone else reports the same issue. No offense @pkactual - but you have a new account and this is your very first report of something that I'm not able to independently verify. For reference, it was added to my list in Jul, 2018 ([a4a5156](https://github.com/lightswitch05/hosts/commit/a4a51562d66ae7173fc75ea1b56874a58456dcae)) and this is the first time I'm hearing complaints about it.

No offense taken - per your earlier question, I'm confident on The Economist this is the breakage. I could see the log entry and removing that one entry solved the problem. All the other stuff that gets blocked results in empty ad-space, mobile ad breakage, etc. on The Economist but everything else functions.

**Comment by pkactual** [comment]
Looks like they no longer use this on the _main_ login - just for
subscriber services and direct-to-article links. As far as that is
concerned, I'd considered this a closed issue because that workaround is no
less cumbersome than using an AD blocker. So I think we're good to go. -Ali

**Comment by lightswitch05** [comment]
Thanks for the update!
