### ISSUE TITLE
Automatically de-dup domains between the primary and aggressive lists

### ISSUE THREAD

**Issue by lightswitch05** [lightswitch05/hosts#191]
There is some duplicates between the aggressive and primary lists. This isn’t and issue for pihole users, but might cause issues for other blocking tools.

**Comment by lightswitch05** [comment]
After more thought, I think this would take a significant amount of work. My original thought was that I could exclude duplicates with some SQL, but I forgot about the whitelists. If I tried to implement this in SQL only, domains that are whitelisted in the primary list and are not whitelisted in the aggressive list would get removed from the aggressive list. 

Not saying I can’t be done, but it would take a lot of work, and there are a lot more other things I’m more interested in adding to this project. Sorry!

**Comment by ler762** [comment]
It was easy enough for me to sort & de-dup the lists, so no problem.
Thanks anyway!
