### ISSUE TITLE
s81c.com false positive?

### ISSUE THREAD

**Issue by crssi** [lightswitch05/hosts#192]
`s81c.com` looks to be a redirection to `ibm.com`

also when visiting `ibm.com` the page is broken, since the `css` and similar is trying to fetch from `s81c.com`

What is the reason that this domain got on the list?

Thank you and cheers

**Comment by crssi** [comment]
Logo on https://business.weather.com/ says: "The Weather Company, An IBM Business"
It looks like this page is owned by IBM... also https://www.s81c.com/ leads to https://www.ibm.com/

Happy to report to make the list better... cheers

**Comment by llacb47** [comment]
The domain is owned by IBM: http://whois.sc/s81c.com

**Comment by lightswitch05** [comment]
Deleted, thanks again for the report!
