### ISSUE TITLE
WaPo False positive

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#196]
Inclusion of `comments-api.ext.nile.works` breaks comment section on older washington post articles:

```
https://www.washingtonpost.com/local/why-is-confederate-general-albert-pike-memorialized-at-judiciary-square/2016/10/22/9d69f26c-96ed-11e6-bc79-af1cd3d2984b_story.html
https://www.washingtonpost.com/politics/obama-is-increasingly-involved-in-the-2016-presidential-campaign/2016/03/17/0f76e0cc-eb13-11e5-b0fd-073d5930a7b7_story.html
```

**Comment by lightswitch05** [comment]
Added in: 6d44a9ab1a53199a03206225daf551d71ae20f05

Looks like I have the entire domain blocked.

**Comment by lightswitch05** [comment]
Whitelisting is the one thing I can’t do from my phone. I’ll get to this as soon as I can.

**Comment by lightswitch05** [comment]
Whitelisted, thanks!
