### ISSUE TITLE
Google Fonts not working / gstaticadssl.l.google.com

### ISSUE THREAD

**Issue by N1ghtshad0w** [lightswitch05/hosts#197]
gstaticadssl.l.google.com is blocked by this:
https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

This means that all CDN Google fonts used will not work anymore.

This issue was reported before on StevenBlack github page
https://github.com/StevenBlack/hosts/issues/975

**Comment by lightswitch05** [comment]
Please see #136.

I do not block `fonts.gstatic.com`- but if you are using a blocking tool that blocks CNAMEs, like the pihole, then whitelisting `fonts.gstatic.com` will fix it.

**Comment by JobcenterTycoon** [comment]
why not putting this in the Tracking Aggressive list?

**Comment by lightswitch05** [comment]
If I was blocking `fonts.gstatic.com` then I agree it would be aggressive. I am not. What this boils down to an inability for a hosts-formatted file to describe my blocking goals. If you use a blocking tool like the PiHole that automatically blocks based on CNAME values, then you'll need to whitelist `fonts.gstatic.com`. I do not block `fonts.gstatic.com`. I do not wish to block `fonts.gstatic.com`. I cannot tell Pihole to not block `fonts.gstatic.com` but to continue blocking `gstaticadssl.l.google.com`.

**Comment by crssi** [comment]
I see.

Thank you and cheers
