### ISSUE TITLE
Marketo CNAME false positive

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#198]
```
$ dig +noall +answer learn.zenefits.com @1.1.1.1
learn.zenefits.com.     3486    IN      CNAME   zenefits.mktoweb.com.
zenefits.mktoweb.com.   186     IN      CNAME   ab05.mktossl.com.
ab05.mktossl.com.       186     IN      A       104.17.72.206
ab05.mktossl.com.       186     IN      A       104.17.74.206
ab05.mktossl.com.       186     IN      A       104.17.73.206
ab05.mktossl.com.       186     IN      A       104.17.70.206
ab05.mktossl.com.       186     IN      A       104.17.71.206
```

`learn.zenefits.com` is blocked by inclusion of its CNAME `ab05.mktossl.com`, it's a subdomain of zenefits, a human resources company, used for email marketing. When blocked you cannot see images in some emails from zenefits. I think it's a bit aggressive and should be moved. What do you think?

`mktossl.com` is owned by Marketo.

Example URLs:
```
https://learn.zenefits.com/employee-onboarding-guide.html
https://learn.zenefits.com/rs/180-GFH-982/images/teladoclogo.png
```

**Comment by lightswitch05** [comment]
I think these CNAME issues are tricky, I’m sure `learn.zenefits.com` isn’t the only CNAME for the Marketo domain. You say the emails are marketing emails?

**Comment by llacb47** [comment]
Yes
![image](https://user-images.githubusercontent.com/16567977/85429824-48fef880-b54d-11ea-943a-5cbbfd7ac457.png)

**Comment by lightswitch05** [comment]
Moved to aggressive list in https://github.com/lightswitch05/hosts/commit/660085673aa7187b304fc3ee7b40eaf96c5ff051
