### ISSUE TITLE
Amazon Firestick Adult Swim app: Videos not playing

### ISSUE THREAD

**Issue by anudeepND** [lightswitch05/hosts#20]
`amd.cdn.turner.com` is blocked in https://github.com/lightswitch05/hosts/blob/61e8c7271c272a7b232a07b3d9f602a24b8b28c7/ads-and-tracking-extended.txt#L6205. To watch videos in Amazon Firestick Adult Swim app this domain should be whitelisted. It is safe to remove it since it does not do any tracking. 
It is been reported in my [repo](https://github.com/anudeepND/whitelist/issues/46).

**Comment by lightswitch05** [comment]
> It is safe to remove it since it does not do any tracking.

How do you know this?

**Comment by lightswitch05** [comment]
I moved it to my aggressive list in https://github.com/lightswitch05/hosts/commit/0a5dad238f932f5d6e36a7a4d9f97ee3bebb8279
