### ISSUE TITLE
Add domains from cookie vendor list

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#200]
`https://storage.googleapis.com/tcfac/additional-consent-providers.csv`

From https://github.com/uBlockOrigin/uAssets/issues/7624

**Comment by lightswitch05** [comment]
I’ve added some of these lists before

1. https://github.com/lightswitch05/hosts/blob/master/docs/google-vendor-list-proxy.json
2. https://github.com/lightswitch05/hosts/blob/master/docs/optanon-vendor-list.json

It’s kinda risky and is easy to accidentally block a lot of things that shouldn’t be blocked. But there is a lot of good stuff to block in them as well. Certainly not something that should be automated.
