### ISSUE TITLE
static.ada.support

### ISSUE THREAD

**Issue by TheNoobWar** [lightswitch05/hosts#201]
`static.ada.support` is a domain on this list. This domain is a CDN for company support pages as a means of contact. With this domain blocked, it does not display any content for a user to seek assistance in their inquiries.

**Comment by lightswitch05** [comment]
Thanks for the information @TheNoobWar. Can you provide specific links so that I can verify it?

**Comment by lightswitch05** [comment]
Looks like it’s in the tracking-aggressive list. Added in July 2019 in https://github.com/lightswitch05/hosts/commit/e571b28518c686914fabb32323179cd8e848a106

**Comment by lightswitch05** [comment]
Interesting, looks like I’m blocking `*. ada.support`. Being an aggressive block, Im not particularly interested in taking action on this request. But if you can provide some specific examples and I don’t find any tracking logic then I’ll consider removing it.

**Comment by lightswitch05** [comment]
Oh, a simple duck search solves this one:

> Ada's AI chatbot takes its value beyond cost reduction by generating new customer revenue through up-sell and cross-sell. Customer service doesn't have to be a drain on your budget - in fact, Ada changes your customer support from cost to revenue center.

Not going to remove it. I agree that it might be aggressive for some, but it’s already correctly categorized in the aggressive list. My general advice is to not use the aggressive list.
