### ISSUE TITLE
Domains to whitelist Instagram? (Facebook block list)

### ISSUE THREAD

**Issue by gottabeleGIT** [lightswitch05/hosts#202]
After adding the Facebook block list to PiHole, a user on my network reported that they could not access the Instagram mobile app. Which domains would need to be whitelisted to access Instagram? I've tried the `(\.|^)instagram\.com$` and the `(^|\.)instagram\.com$` regex but they don't seem to work...

**Comment by lightswitch05** [comment]
Instagram uses Facebook hosts. I do not believe you can block one without also blocking the other.

**Comment by gottabeleGIT** [comment]
Ah, so I would need to remove the list?

**Comment by lightswitch05** [comment]
Yes, the description of the list:

> A hosts file to block all facebook and facebook related services, including Messenger, *Instagram*, and WhatsApp.

**Comment by gottabeleGIT** [comment]
Gotcha, thanks

**Comment by kzshantonu** [comment]
@lightswitch05 Love the work you do. Would you happen to have a whatsapp and instagram list so I can add it to my allowlist? I'd like to use your facebook blocklist but also allow whatsapp and instagram safely without allowing tracking in those apps

**Comment by lightswitch05** [comment]
Sorry @kzshantonu- I do not have a list for that. I also do not have whatsapp or Instagram, so no way for me to even test that request.
