### ISSUE TITLE
False positive: 163.com

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#203]
False positive: `163.com` and subdomains

It is a web portal and very popular <sup>[1]</sup> Chinese website operated by NetEase (网易).

Example pages: 

```
https://music.163.com/#/song?id=82932
https://tech.163.com/20/0623/18/FFR15O8T00097U7R.html
```

[1] `https://www.alexa.com/topsites/countries/CN`

**Comment by lightswitch05** [comment]
Sorry for the late response. I think I'm going to move these to the aggressive list, I was certainly receiving spam with some questionable links to some of these domains.

**Comment by lightswitch05** [comment]
well, I accidentally deleted them all. Without I'm not going to try to go through them all and reload them. I manually scrolled through the list and re-added a few that looked like they should obviously be blocked.

**Comment by lightswitch05** [comment]
Direct link to the last version with all of the 163.com hosts: https://raw.githubusercontent.com/lightswitch05/hosts/2f5d6a36363ea02c33857edb8cf4560ea052c6ec/docs/lists/ads-and-tracking-extended.txt

**Comment by lightswitch05** [comment]
Fixed in https://github.com/lightswitch05/hosts/commit/8278696a74fa4f025f898c31fa2a0c07ee2e06ba
