### ISSUE TITLE
edge1.certona.net causes canadiantire.ca search results to hang

### ISSUE THREAD

**Issue by ck9ine** [lightswitch05/hosts#204]
https://www.canadiantire.ca

Site loads up fine.  However, once one attempts a search, the search results just hang/no output.

Narrowed it down to "edge1.certona.net" within your blocklist after searching and eliminating through process of elimination through my "blocked domains" log.  

Thanks for all your hard work.

**Comment by lightswitch05** [comment]
Thanks for the report. I'll need to look at it once I'm in front of a computer, looking at my notes for this one (26 May 2020)

> added for https://edge1.certona.net/cd/fed2c611/www.pier1.com/scripts/resonance.js on https://www.pier1.com

**Comment by lightswitch05** [comment]
Looks like `certona.net` is blocked in: `https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt`

**Comment by lightswitch05** [comment]
Blocked Scripts: `https://edge1.certona.net/cd/a691d6e4/canadiantire.ca/scripts/resonance.js`

**Comment by lightswitch05** [comment]
![image](https://user-images.githubusercontent.com/598803/87681586-d00a4f80-c74c-11ea-9dbb-7d35d41f6616.png)

**Comment by lightswitch05** [comment]
Looks like `callCertona` is not providing any actual functionality, but that the `canadiantire.ca` is not doing proper error handling when calling it, breaking the entire page.

**Comment by lightswitch05** [comment]
![image](https://user-images.githubusercontent.com/598803/87683880-92f38c80-c74f-11ea-8b3a-2367f455d586.png)

**Comment by lightswitch05** [comment]
Just a note, when I do not block `edge1.certona.net`, then it causes this request to be made:

`https://www.res-x.com/ws/r2/Resonance.aspx?appid=CanadianTire01&tk=[redacted]&ss=[redacted]&sg=1&pg=[redacted]&vr=5.10x&bx=true&sc=rv1_rr&ev=&ei=&cu=&no=20&language=en&inStockStores=0055&availableStores=0055&ccb=certonaRecommendations&ur=https%3A%2F%2Fwww.canadiantire.ca%2Fen%2Fonline-ordering.html%3Fadlocation%3DLOL_OnlineOrdering_SiteFooter_en&plk=&rf=https%3A%2F%2Fwww.canadiantire.ca%2Fen.html`

this request is also blocked, but its better to have the original source `edge1.certona.net` blocked.

**Comment by lightswitch05** [comment]
I don't intend to remove this block as it appears the broken page is a failure to do proper error handling rather then blocking a legitimate domain

**Comment by ck9ine** [comment]
I appreciate you looking into this.  :)

**Comment by lightswitch05** [comment]
@ck9ine I never heard back from `certona`, but it appears search is working with this still being blocked. Do you mind double checking?

**Comment by ck9ine** [comment]
The search is not working on my end.  As soon as I whitelist edge1.certona.net, the search is okay.  

You mention certona, however, based on your previous comment, I believe you contacted Canadian Tire.  I don't see a big company (for Canada haha) making a change like you described as being a top priority unless the site is "broken" for a high number of users... and I don't think there are a high percentage of Canadians utilizing blocklists.

**Comment by lightswitch05** [comment]
Haha yeah I doubt they fixed anything based on my email, but I'm also unable to reproduce the error anymore. Test on mobile and desktop- search is working fine for me.

**Comment by ck9ine** [comment]
Did some more light testing.  Tried different browsers, including mobile.  Also tried VPN (Canada vs US).  I also experimented with blocking the domain within the Windows Hosts file.  The search did work sporadically.  

Here's what I observed using the browser's "Developer Tools" to track network requests.  When the search function worked, it appeared that the script at "edge1.certona.net" was not being called at all, OR, "edge1.certona.net" did pick up a "true" IP (vs "blocked").  Whether that be some sort of script programming with the site, or poor cache cleaning by me, I didn't have time to explore further.

**Comment by ck9ine** [comment]
Daniel, would you mind testing this again?  I still see the block on "edge1.certona.net" as causing the search to "hang".  I think the reason why the search worked for you may be due to some weird DNS caching issue.  If you have time, maybe you can try a direct block via your computer's HOSTS file.  

As you can tell from my reports, there is an online shopping theme haha.  With Covid, there is an importance that these sites work correctly as they're some of the bigger Canadian-based retailers in the country).  Thanks for your consideration!

**Comment by lightswitch05** [comment]
Hey @ck9ine - I just tested - and yes, its still broken. Unfortunately, this is a [massively popular tracker](https://publicwww.com/websites/edge1.certona.net/) and does not break other websites when block, so I'm not inclined to removed it at this time. I'm not sure how you are using my list, but please find a why to whitelist it on your side.

**Comment by ck9ine** [comment]
Hi, I can confirm now that this domain no longer breaks the search function for me, at least on this originally reported site.

**Comment by lightswitch05** [comment]
Woohoo! That's great news! Thank you so much for taking the time to come back and update the ticket 😀 I really appreciate that. Cheers!
