### ISSUE TITLE
False positive static.lakana.com

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#211]
Breaks styles in weather widget (to the right of title) on `https://www.wfla.com/news/hillsborough-county/tampa-teen-accused-of-being-mastermind-behind-twitter-hack-that-targeted-high-profile-accounts/`

Weather widget iframe source: `https://s3.amazonaws.com/static.baron.web.apps/digitial_wx/pages/n2.adaptive/7day/index.html?initjson=https://s3.amazonaws.com/static.baron.web.apps/digitial_wx/widgets/dcms/5aadecb4-25a6-494e-805c-6e75b4344c3c/live/init.js&initjsonvar=initdata`

Loads CSS from `https://static.lakana.com/nxsglobal/good4utah/theme/images/Weather/NXST_Stations/3-Day_WFLA.css`

I think this domain should be removed, it looks like just a CDN for nexstar news sites.

**Comment by lightswitch05** [comment]
Added in https://github.com/lightswitch05/hosts/commit/e35f2c56dd2e59d6ae4a055a2cab36ee068c9628

I have literally no notes on this one other then it was added on Jul 05, 2018. No other lists are blocking it. I agree this is probably a false positive. Really wish I had better notes from back then. Thanks again for the quality report @llacb47 !

**Comment by lightswitch05** [comment]
Fixed by https://github.com/lightswitch05/hosts/commit/4ff852fc7c9c6327a996c25f8fd14b211ac3c14a
