### ISSUE TITLE
photos-us.bazaarvoice.com 

### ISSUE THREAD

**Issue by ck9ine** [lightswitch05/hosts#212]
Blocking "photos-us.bazaarvoice.com" prevents pictures of products included by the customer within their own reviews on Lowes.com and Lowes.ca

Observed browser requests for blacklist and whitelist using developer tools (network).  Whitelisting immediately allows the pictures to load as expected.

**Comment by lightswitch05** [comment]
Added in https://github.com/lightswitch05/hosts/commit/6f6c14c4d755d69b8ed1fa2a2de6fd1ba100d658

No notes on this one. I'm the only one blocking it.... on mobile right now, but I'm inclined to agree that this is a false positive. Going to remove it. If I see it pop up again, I might add it to the aggressive list. Thanks for the report!

**Comment by lightswitch05** [comment]
Removed in https://github.com/lightswitch05/hosts/commit/d0bede791a1c4f1fa4d21cd793c242f1dfb041b4
