### ISSUE TITLE
Google Fonts not working / gstaticadssl.l.google.com

### ISSUE THREAD

**Issue by adil452100** [lightswitch05/hosts#214]
Hello,
According to my pi-hole installation gstaticadssl.l.google.com is blocked by :

Match found in https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt:
   gstaticadssl.l.google.com 

This would not be a problem but ...

$ dig fonts.gstatic.com
fonts.gstatic.com.	89	IN	CNAME	gstaticadssl.l.google.com.
gstaticadssl.l.google.com. 88	IN	A	172.217.15.99

This means that all CDN Google fonts used will not work anymore.
However, given the name "g static ad ssl" this might be a change that would show more Google ads probably.

This is however very annoying. Though I could just add a custom exception in pi-hole I think I'm not the only one who does not like Google Fonts not working anymore per default.

**Comment by llacb47** [comment]
https://github.com/lightswitch05/hosts/issues/136
https://github.com/lightswitch05/hosts/issues/197
https://github.com/lightswitch05/hosts/issues/213

**Comment by lightswitch05** [comment]
https://github.com/lightswitch05/hosts#common-issues
