### ISSUE TITLE
translate.google.com

### ISSUE THREAD

**Issue by TheNoobWar** [lightswitch05/hosts#216]
Hi there,

`translate.google.com` was found as a false-positive. Alternatively, country specific Google TLDs like `translate.google.ca` work as they are not listed.

`translate.google.com` redirects to Google Translate webpage.

Thank you!

**Comment by lightswitch05** [comment]
Sorry, I'm blocking this on purpose. It's in the aggressive list. Please do not use the aggressive list.

**Comment by lightswitch05** [comment]
I guess should add more details here. The domain is regularly found as as 3rd party tracker on site. I realize it can be extremely useful for some people. I've never seen the other domains used as a 3rd party or I would be blocking them as well.

**Comment by TheNoobWar** [comment]
Fair enough, did not know it contained tracking elements.
