### ISSUE TITLE
(whitelist) u1375320.ct.sendgrid.net

### ISSUE THREAD

**Issue by 3xploiton3** [lightswitch05/hosts#217]
false positive
![image](https://user-images.githubusercontent.com/19517680/89947173-4156f880-dc4e-11ea-8877-d032605cfc3c.png)
u1375320.ct.sendgrid.net

to manage feed from stackshare.io

**Comment by lightswitch05** [comment]
@3xploiton3 this request does not meet the minimum required amount of effort to make a whitelist request. For starters, `u1375320.ct.sendgrid.net` is not in my list and it doesn't look like its a CNAME for something that is in my list.

Per my issue template for false positive requests:

> Prove it. Do your research. I spend a lot of time working on this list, if you think you've found an issue, put the effort into it to prove it to me. Give me links to verify. I added the domain to the list, so I think it should be blocked. The burden of proof is on you.

Not not saying my list isn't the ultimate cause of the issue, but I'm also not seeing anything in the ticket for me to take action on.

**Comment by 3xploiton3** [comment]
http://u1375320.ct.sendgrid.net/ls/click?upn=0BS7ECoGoP0ELKQgqTTETn469A90yHbwHj6ZW2M6VhB9tvjuBFp0Ft7KfurHStQ6tTYmIBO6EM1eIEIon6r6Ld4q7bRQ8kUvMXTUZ-2B5ZYV6aXghEpo2S5m3IkBqiMUfnDjNmiQleYjYUyMtidC-2BMqQ-3D-3DhdrX_SzQ-2Fh8V6zGRSt1MKjqL0jOmwdEwVluWgsVY1inTkbo-2Bi1O2EnCtqR-2F-2F4HIfqFzlcPTn2eHsnHxo3Pg5rinZWw-2BfpepReggDTNaXWJMEG5BY0fGwqoCaAh12hS-2Fc0WTJJrbsfRPEh4-2F2I56K1AjjQXFrFlHqQRV2pBOFlxMQQLvwwF7YkLBVE22A0LruqjqsRjv9tiLZs3c0xDmKCCx0ayViMo5JXBwlBvpiAka04B0A-3D

**Comment by lightswitch05** [comment]
Ok, now you have provided a link that is not blocked in my list. There is nothing for me to help with here.
