### ISSUE TITLE
(whitelist) bukalapak.go2cloud.org

### ISSUE THREAD

**Issue by 3xploiton3** [lightswitch05/hosts#218]
product link to bukalapak.com 
many apps associate with bukalapak will break function

**Comment by lightswitch05** [comment]
Added in https://github.com/lightswitch05/hosts/commit/6b7b8e7bc285a381808aa81411fc6a89a86bc6cf

> Large update including a lot of the bigger blocks from hphosts ATS list

**Comment by lightswitch05** [comment]
`go2cloud.org` looks like trash- but apparently I've never come across a single one of its subdomains, which is really a requirement, so removed. It I see it showing ads, it will be added back.

**Comment by lightswitch05** [comment]
Removed by https://github.com/lightswitch05/hosts/commit/b79d14396c45d2404e476b835e220deb87cb3f6f
