### ISSUE TITLE
Investigate nanoapp.io requests and privacy policy

### ISSUE THREAD

**Issue by lightswitch05** [lightswitch05/hosts#22]
I've seen `ambient-weather-amb.nanoapp.io`. Looks like that is a domain operated by Nanobox. So far its unclear the purpose for the domain, but does have a dashboard that looks similar to New Relic - which is commonly blocked. I've asked on their slack channel for more details and I'm still waiting for a response

![image](https://user-images.githubusercontent.com/598803/46155352-9eb64c00-c266-11e8-9baf-c522a8ab03c2.png)

**Comment by lightswitch05** [comment]
https://nanoboxio.slack.com/archives/C2EUZNV2T/p1538052471000100

**Comment by dnmTX** [comment]
@lightswitch05  can you research `*.atwola.com` domains.This is the AOL's advertisement/telemetry domains. Spotted one on yahoo today `us.y.atwola.com` and it's not on any lists and i'm pretty sure there are many more that still needs to be added.Thank you.

**Comment by lightswitch05** [comment]
@dnmTX sure - I've also seen `us.y.atwola.com` on my pihole, but not sure where it came from. I do have `pixel.ingest.at.atwola.com` in my list already. Any idea which specific pages you saw `us.y.atwola.com` on so I can make sure nothing breaks?

**Comment by lightswitch05** [comment]
@dnmTX nevermind, I see that 'atwola.com' is already in Steven Black's list - but it doesn't have all the subdomains in it. Since the root domain is already in the list, I'm happy to add the rest without needing to research it.

**Comment by dnmTX** [comment]
That's where i found it:
![capture](https://user-images.githubusercontent.com/34774426/46168975-7e36c380-c25f-11e8-92ac-ddfe860ce126.PNG)
 It's all ads/telemetry,nasty stuff.No worries about breaking anything 👍

**Comment by lightswitch05** [comment]
I got a response, seems not to be ads or tracking related

![image](https://user-images.githubusercontent.com/598803/46208957-f2cf3800-c31b-11e8-917e-ce7bd653dba7.png)

**Comment by dnmTX** [comment]
@lightswitch05  can you add:
`beap.adss.yahoo.com`
`beap1.cb.g01.yahoodns.net`
it's the same as `beap.gemini.yahoo.com` which is already added,not sure whoever did it didn't add the rest.From yahoo's source code:
![capture](https://user-images.githubusercontent.com/34774426/46239615-49f6fc00-c360-11e8-8ec2-3f0334738eec.PNG)

**Comment by lightswitch05** [comment]
I added ‘beap.gemini.yahoo.com’ the other day. I didn’t see those others, but I’m happy to add them. Feel free to open new tickets in the future, it makes it easier for me to keep track of things

**Comment by dnmTX** [comment]
> Feel free to open new tickets in the future, it makes it easier for me to keep track of things.
Will do,sorry about that.

**Comment by dnmTX** [comment]
@lightswitch05  `beap.gemini.yahoo.com` is already added in `someonewhocares.org` lists. Just FYI.
