### ISSUE TITLE
sj14.mktossl.com is CNAME for safe.riskiq.com

### ISSUE THREAD

**Issue by mkb2091** [lightswitch05/hosts#220]
safe.riskiq.com is used to display email from RiskIQ in the browser. An example such email is https://safe.riskiq.com/index.php/email/emailWebview?mkt_tok=eyJpIjoiWXpKbE5qUXpNRGxrTldVeCIsInQiOiJKQlRYeURxclJwU1wvemoyODZja2xQNmRMZytxSUdMMUt0Ym1RZ05TY0hUeEFwXC9paHcwaDZZM1wvOVpzbmtSdjJNZTFBS1FSUVljbUFOS2lcLzBSbUhmTTJjek5tYVwveThaa1U2VjJRTnlCd2x6RVZId3R0eXJEWWFZMXphQ0F3S1NBIn0%3D

It is in the ads-and-tracking-extended.txt list

**Comment by lightswitch05** [comment]
Alright, these are getting annoying, see also #198 

I'm going to move `*.mktossl.com` to the aggressive list

**Comment by lightswitch05** [comment]
Moved to aggressive list in https://github.com/lightswitch05/hosts/commit/660085673aa7187b304fc3ee7b40eaf96c5ff051

**Comment by lightswitch05** [comment]
By the way, thanks for the report @mkb2091! I want to make it cleat that the domain was getting annoying, not you or your ticket.
