### ISSUE TITLE
Whitelist labs.alona.co.id

### ISSUE THREAD

**Issue by 3xploiton3** [lightswitch05/hosts#221]
https://github.com/notracking/hosts-blocklists/issues/412  

![](https://i.imgur.com/DeLBA3p.jpg)

**Comment by lightswitch05** [comment]
Please stop opening tickets with no information in them.

> Prove it. Do your research. I spend a lot of time working on this list, if you think you've found an issue, put the effort into it to prove it to me. Give me links to verify. I added the domain to the list, so I think it should be blocked. The burden of proof is on you.

**Comment by 3xploiton3** [comment]
That site online class course

**Comment by lightswitch05** [comment]
I do not block `labs.alona.co.id`.
