### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by e-d-e** [lightswitch05/hosts#226]
Hi,
@lightswitch05 
Can you delete these few please?
Otherwise, important content will not be displayed normally.
```
ad.ettoday.net
api.dable.io
dable.io
```
 thanks!

**Comment by lightswitch05** [comment]
> I spend a lot of time working on this list, if you think you've found an issue, put the effort into it to prove it to me. Give me links to verify. I added the domain to the list, so I think it should be blocked. The burden of proof is on you.
