### ISSUE TITLE
Error in list?

### ISSUE THREAD

**Issue by rssw** [lightswitch05/hosts#227]
Hi, thanks for the great work!

I just happend to notice a long list of domains that seems to be a combination of two domains, such as:
connectivitycheck.android.comopps.cbarsrv.com

I'm assuming this is in error?

**Comment by lightswitch05** [comment]
Yes looks like this is a false sub domain that came from VirusTotal. I'll remove it.

**Comment by lightswitch05** [comment]
Fixed in https://github.com/lightswitch05/hosts/commit/40dc7e6b905fdd4cbf50e6f48321d4f2bb332168 - Thanks!
