### ISSUE TITLE
Yandex.ru false positive

### ISSUE THREAD

**Issue by my-name-is-takeshi-kovacs** [lightswitch05/hosts#228]
Hi there.
I have found using your hosts lists, that it blocks russian search machine Yandex.ru.
It's not a malware website, just a geo oriented search service like Google.
Thanks.

**Comment by lightswitch05** [comment]
I'm not finding `yandex.ru` in any of my lists. I see some subdomains- but that's it.

**Comment by lightswitch05** [comment]
closing until more information is received.
