### ISSUE TITLE
gvt2.com

### ISSUE THREAD

**Issue by jamescridland** [lightswitch05/hosts#232]
You block the following in your https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt list:

```
0.0.0.0 beacons.gvt2.com
0.0.0.0 beacons.gcp.gvt2.com
```

I am also seeing calls to `beacons2.gvt2.com`, `beacons3.gvt2.com` and `beacons4.gvt2.com` in the DNS logs from my installation of Chrome on the Mac.

A Google search (forgive the irony) tells me that there's a `beacons5` as well.

I don't know what these domains are. They don't seem related to advertising as far as I can tell. However, if you're blocking `beacons`, it would seem consistent to block the rest (and, by the looks of things, everything on the gvt2.com domain).

**Comment by kowith337** [comment]
At my side, I found connections attempts only while I update apps from `Google Play Store`, however, legitimate assets (esp. resources of installing/updating apps) mostly connect to `gvt1.com` with many subdomains, so, blocking `gvt2~gtvt5` doesn't occur the main functionality of `Play Store`.

The `beacon` seems to not trusted, it's kind of using for ping and/or phoning home.

FYI: you may include `beacons-handoff.gcp.gvt2.com` CNAME as well.

**Comment by lightswitch05** [comment]
The 1-5 additions will be added in the next automatic update - on mobile right now, so waiting is just easier. I'm not seeing the CNAME being used anywhere though so I didn't add it.

DNS query can be viewed here- no CNAME usage: https://blocklist-tools.developerdan.com/entries/search?q=beacons5.gvt2.com

**Comment by lightswitch05** [comment]
Added in https://github.com/lightswitch05/hosts/commit/2a00182eb8a30085a61f2f60ad4f5e27a3bed64b
