### ISSUE TITLE
Look at this site for ad domains

### ISSUE THREAD

**Issue by lightswitch05** [lightswitch05/hosts#233]
https://morningchores.com/plant-rust/

**Comment by llacb47** [comment]
That's [adthrive](https://help.adthrive.com/hc/en-us/articles/360039737371-What-is-Ad-Block-Recovery-), a quite annoying form of circumvention. You can find it at these blogs also:

```
http://jessifearon.com/
https://damndelicious.net/
https://www.simplywhisked.com/
https://pimylifeup.com/
https://www.thekitchenmagpie.com/
https://linuxhint.com/
```

Longer list: `https://publicwww.com/websites/%22adblock_exp_val%22/`

some domains they use:
```
edvfwlacluo.com
dstik9906m659.cloudfront.net
168logger.com
d2kz60b0gq4lg.cloudfront.net
ads.adthrive.com
lmyiwaakn.com
yyjvimo.com
```

**Comment by lightswitch05** [comment]
Hey @llacb47 - I was going to look those up! Lol, you beat me to it. Been too busy today and didn't want to forget this one. Thanks for looking them up.

**Comment by lightswitch05** [comment]
Added in https://github.com/lightswitch05/hosts/commit/ae28bc14b5857d14d41b3ad4450beb4516a737c7

The CNAME [d3dchvk1ruk2gi.cloudfront.net](https://blocklist-tools.developerdan.com/entries/search?q=d3dchvk1ruk2gi.cloudfront.net) catches the `*.yyjvimo.com` wildcard
