### ISSUE TITLE
www.spiegel.de breakage due to message331.sp-prod.net

### ISSUE THREAD

**Issue by crssi** [lightswitch05/hosts#235]
https://www.spiegel.de does not let you visit a content due to message331.sp-prod.net over a spiegel-de.spiegel.de CNAME/alias.

Cheers and thank you for your work

**Comment by lightswitch05** [comment]
Added here: https://github.com/lightswitch05/hosts/commit/08827469a0a5c0f23bf6d3a7ee5b4e33a3edacda

Non-automatic domains:

* `ccpa.sp-prod.net`
* `dialogue.sp-prod.net`
* `mms.sp-prod.net`

perhaps I'll limit the block to just those

**Comment by lightswitch05** [comment]
changes made - will be in the next release
