### ISSUE TITLE
launch.solarwinds.com

### ISSUE THREAD

**Issue by 3xploiton3** [lightswitch05/hosts#236]
![image](https://user-images.githubusercontent.com/19517680/94751120-db673180-03b1-11eb-9ff3-b9b489e02676.png)

i click unsubscribe from solarwinds, it's blocked by lightswitch05

https://sw1.solarwinds.com/p0q00VmcMR0n65IFmU0Xmw2

**Comment by lightswitch05** [comment]
Ok, whitelist it, unsubscribe, then add it back.

**Comment by lightswitch05** [comment]
Looks like this is being blocked due to `sj07.mktossl.com` CNAME - which is in the aggressive list. Please don't use that list.
