### ISSUE TITLE
 driftt.com and drift.com rules breaks live chat

### ISSUE THREAD

**Issue by crssi** [lightswitch05/hosts#237]
Blocking driftt.com and drift.com breaks live chat provided by same.

Sample domain where chat breaks is https://jumpcloud.com/ <- unfortunate the login is required, but there is also a trial version.

If you need, I can make a screen recording for you.

Cheers

**Comment by lightswitch05** [comment]
I don't want to create an account, is it like a chat-bot chat? Or support chat? Just whitelist it.

**Comment by crssi** [comment]
It is a support chat.

**Comment by crssi** [comment]
Actually you can find more details about at the `https://www.drift.com/`.

Cheers

**Comment by lightswitch05** [comment]
Moved to the aggressive list in the next update

**Comment by lightswitch05** [comment]
https://github.com/lightswitch05/hosts/commit/eb0217d779ac6ebd0118df0836f446cf9b497471
