### ISSUE TITLE
(new)domains to add

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#24]
@lightswitch05  test page: https://gounlimited.to/cju590pcctpr (hurry up on testing this,not sure how long the link will be active)
all the listed domains are either ads or annoyances.Test them and add them please.
**Thank you!**
`static.zdassets.com`
`cf.zdassets.com`
`geniusonclick.com`
`pallsvility.pro`
`celeritascdn.com`
`d3al52d8cojds7.cloudfront.net`

**Comment by lightswitch05** [comment]
@dnmTX that URL link looks fine to me. I'm not able to verify the other domains on the list. I believe `zdassets.com` and `celeritascdn.com` might be generic CDN domains - which could be used to serve anything, not just ads.

**Comment by lightswitch05** [comment]
Turns out I wasn't able to check `celeritascdn.com` because it was on a blocklist on my pi. Since its not in Steven's hosts list, I'll be adding it in my next update

**Comment by lightswitch05** [comment]
Just for reference, its on these lists:

```
 Exact matches for celeritascdn.com found in:
   https://v.firebog.net/hosts/AdguardDNS.txt
   https://v.firebog.net/hosts/Easylist.txt
   https://tspprs.com/dl/ads
```

**Comment by dnmTX** [comment]
@lightswitch05  thanks for checking it.And,yes,i'm using AdGuard myself which also blocked some of those domains.Still,anything you can find suspicious just add it,not everyone who's using the lists have PI or AdGuard so i'd say better safe then sorry.Thank you.
