### ISSUE TITLE
s.pinimg.com

### ISSUE THREAD

**Issue by p1r473** [lightswitch05/hosts#243]
Hi Dan, hope all is well.
Just reporting to you about s.pinimg.com
I know its already on your aggresive list, erego I will be closing this issue as soon as I open it, but I am still logging this incident just for your FYI so you can review if you meant to block this domain
s.pinimg.com breaks pinterest.com completely.
It hosts all Pinterest static images (s. usually for static.)
@lightswitch05

**Comment by lightswitch05** [comment]
Thanks for report @p1r473! This is intentional. Added for `https://s.pinimg.com/ct/core.js` tracking on `https://open.spotify.com/`

**Comment by lightswitch05** [comment]
`window.pintrk.partnerData`
