### ISSUE TITLE
Extremetech.com --> ziffdavis.com.edgekey.net

### ISSUE THREAD

**Issue by ck9ine** [lightswitch05/hosts#244]
Are you able to reach http://extremetech.com?

NextDNS is resolving it to ziffdavis.com.edgekey.net, which is on the blocklist.  
https://imgur.com/JJlGWMJ

**Comment by lightswitch05** [comment]
Interesting. `ziffdavis.com` is an [extremely common block](https://blocklist-tools.developerdan.com/entries/search?q=ziffdavis.com). But `ziffdavis.com.edgekey.net` is [not very common](https://blocklist-tools.developerdan.com/entries/search?q=ziffdavis.com.edgekey.net). This is the first report I've seen about `ziffdavis.com.edgekey.net` breaking things, so lets keep this ticket open and see if anyone else if having issues.

**Comment by llacb47** [comment]
Just ran into this one.

**Comment by dnmTX** [comment]
> ....so lets keep this ticket open and see if anyone else if having issues

`ziffdavis.com.edgekey.net` is a Alias of `www.extremetech.com` and taking into account that NextDNS blocks CNAME's,Aliases as well as wildcard blocking(of the previously mentioned) OF **ANY** listed domain,anyone who's using NextDNS will not be able to reach `www.extremetech.com`:

![Capture](https://user-images.githubusercontent.com/34774426/103591911-1c8e4680-4eb7-11eb-8503-e09ee1685be6.PNG)

**Comment by lightswitch05** [comment]
Will be moved to aggressive list in the next update. Thanks everyone, welcome back @dnmTX

**Comment by lightswitch05** [comment]
Fixed by https://github.com/lightswitch05/hosts/commit/ac2e13e3c5a1611494b6bfa7322236d29737274c
