### ISSUE TITLE
bogus names?

### ISSUE THREAD

**Issue by ler762** [lightswitch05/hosts#245]
Where do you get your list of names from?  Some of the names make me wonder if someone is intentionally blowing up your list - eg

```
$ dig @1.1.1.1 +short ww17.2sshoes.com
9095.searchmagnified.com.
208.91.196.95

$ dig @1.1.1.1 +short ww17ww18.2sshoes.com
103.224.212.219

$ dig @1.1.1.1 +short ww17ww18ww19ww20.2sshoes.com
103.224.212.219

$ dig @1.1.1.1 +short ww17ww18ww19ww20ww212222ww232323ww24242424.2sshoes.com
103.224.212.219

$ dig @1.1.1.1 +short ww1.2sshoes.com
103.224.212.219

$ dig @1.1.1.1 +short ww2.2sshoes.com
103.224.212.219

$ dig @1.1.1.1 +short hahahahahahahahahahah.2sshoes.com
103.224.212.219
```

**Comment by lightswitch05** [comment]
Sorry for the late response @ler762 - holidays are always busy. My list does automatically discover subdomains, as well as remove any domains that no longer respond.

That particular root domain (`2sshoes[dot]com`) is malicious and was added from [this list](https://awakesecurity.com/wp-content/uploads/2020/06/GalComm-Registered-Domains-List-Appendix-A.txt). The list is part of a report: [The Internet’s New Arms Dealers: Malicious Domain Registrars](https://awakesecurity.com/blog/the-internets-new-arms-dealers-malicious-domain-registrars/).

Any domain in my list is periodically scanned for subdomains. I do this using several sources:

* [VirusTotal API](https://developers.virustotal.com/v3.0/reference#subdomains)
* [Certificate Transparency Logs](https://en.wikipedia.org/wiki/Certificate_Transparency#Certificate_Transparency_logs)
* [Common Crawl](https://commoncrawl.org/)

Finally, I constantly resolve these domains and automatically remove them if they become dead. As you've found, some DNS records are actually wild-carded and will have a valid response to any subdomain. This domain is one of those, so it gets a bit more tricky to remove invalid entries. I haven't figured out a way to weed out these bogus subdomains vs. ones you are actually likely to see, but I don't believe it is really causing any trouble either. Once these domains expire and stop resolving, then all the entries would also be removed from the list.

I hope that answers your question?
