### ISSUE TITLE
Blocking "t-mobile.wurfl.io" Breaks T-Mobile Online Bill Pay Page

### ISSUE THREAD

**Issue by JS876** [lightswitch05/hosts#246]
Ran into this issue today while paying my T-Mobile bill. The following domain was blocked, which led to a endless loading page loop:

  | t-mobile.wurfl.io

![Blocked Domain](https://user-images.githubusercontent.com/37991727/103447575-071ce080-4c5b-11eb-9a84-f801de672032.png)

Once I unblocked the domain in Pi-hole, I was able to get the page to load. Initial navigation to the page loads the following domains:

- my.t-mobile.com
- t-mobile.wurfl.io

**Comment by lightswitch05** [comment]
Added `wurfl.io` for `https://wurfl.io/wurfl.js` which is loaded in a variety of websites. That root domain was then expanded to include `t-mobile.wurfl.io`. I'm fine with moving `t-mobile.wurfl.io` to the aggressive list

**Comment by lightswitch05** [comment]
Will be moved to aggressive list in the next update

**Comment by lightswitch05** [comment]
Fixed by https://github.com/lightswitch05/hosts/commit/d1003c177468b0bf7d4dc2ee7f2ff7c3394eb05d
