### ISSUE TITLE
Breaking collegeboard search

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#247]
`sp10044311.guided.ss-omtrdc.net` breaks collegeboard search.

Test on `https://search.collegeboard.org/?word=test&tp=usearch&searchType=site&siteType=default`

**Comment by lightswitch05** [comment]
`_satellite is not defined` - I wish people could actually check their variables being trying to use them.

**Comment by lightswitch05** [comment]
`window,"_satellite.track","cbTrack.widgetsReady"` it fails because they cannot track you

**Comment by llacb47** [comment]
No, the search results are coming from that domain.

**Comment by llacb47** [comment]
Any update?

**Comment by lightswitch05** [comment]
I'm open to removing this one - or maybe putting it into the aggressive list. However, this is a CNAME for `commerce.ss-omtrdc.net` - which I'm not interested in removing without many more reports from a variety of websites

**Comment by lightswitch05** [comment]
I suppose `sp10044311.guided.ss-omtrdc.net` is limited to this single website, so I'm ok with the whitelist request. It will be removed in the next release.
