### ISSUE TITLE
Something in this list causes certain font rendering to fail on certain Google service pages

### ISSUE THREAD

**Issue by oywino** [lightswitch05/hosts#249]
Hi,
With this list active, the following happens on certain Google sites, i.e. Google Translate:
![image](https://user-images.githubusercontent.com/18447119/104136663-deea5b80-5397-11eb-9787-17c7d63507bb.png)

If I disable your list then everything is ok. When I enable the list, the problem is back again.
It also happens on certain pages in the Google Cloud service platform. But I haven't found any other (non-Google) sites to be affected.
I used Adam:ONE to analyse what sites are called by Google Translate, but the result did not help me locate the culprit:

translate.google.no
www.google.com
fonts.gstatic.com
www.gstatic.com
apis.google.com
www.google-analytics.com
ssl.gstatic.com
www.google.no
ajax.googleapis.com

Any help is appreciated.

**Comment by lightswitch05** [comment]
It's probably `fonts.gstatic.com` and maybe not seeing immediate results due to cache

**Comment by lightswitch05** [comment]
See 'common issues' at the bottom of the README

**Comment by oywino** [comment]
> It's probably `fonts.gstatic.com` and maybe not seeing immediate results due to cache

Ok, I'll test that - and if it is, shouldn't you remove it? (I assume it eventually affects all users?)

**Comment by oywino** [comment]
Tested. And I can confirm that whitelisting _fonts.gstatic.com_ solves the issue once the cache is cleared.

**Comment by lightswitch05** [comment]
Thanks for the update. I do not block `fonts.gstatic.com`, so nothing to remove.
