### ISSUE TITLE
domains to add (part 2)

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#25]
@lightswitch05  got those from:
https://github.com/FadeMind/hosts.extras/blob/master/StreamingAds/hosts   (very legit source)
Unfortunately they're not in StevenBlack's lists for some reason.Removed all the duplicates,dead/invalid and anything with **SPOTIFY** in it due to being very controversial(too many complaints in the past about breaking functionality).This is what's left,in my opinion they're all bad and deserve a place in the lists.Please inspect and add.Thank you.

`0.0.0.0 adnxs.comadplexmedia.adk2x.com`
`0.0.0.0 content.bitsontherun.com`
`0.0.0.0 cs126.wpc.edgecastcdn.net`
`0.0.0.0 d2gi7ultltnc2u.cloudfront.net`
`0.0.0.0 d3rt1990lpmkn.cloudfront.net`
`0.0.0.0 d360616xvwhw9g.cloudfront.net`
`0.0.0.0 gtssl2-ocsp.geotrust.com`
`0.0.0.0 redirector.gvt1.com`
`0.0.0.0 securepubads.g.doubleclick.net`
`0.0.0.0 seen-on-screen.thewhizmarketing.com`
`0.0.0.0 server-54-230-216-203.mrs50.r.cloudfront.net`
`0.0.0.0 tracking.tidalhifi.com`
`0.0.0.0 vt.myvisualiq.net`
`0.0.0.0 www.omaze.com`
`0.0.0.0 omaze.com`

**Comment by lightswitch05** [comment]
```
0.0.0.0 adnxs.comadplexmedia.adk2x.com # added
0.0.0.0 content.bitsontherun.com # this looks to be a jwplayer domain - which does do ads and tracking, but is also required to be unblocked for other functionality to work
0.0.0.0 cs126.wpc.edgecastcdn.net # this is a generic CDN provider, without knowing the source I do not feel comfortable blocking it
0.0.0.0 d2gi7ultltnc2u.cloudfront.net # cloudfront domains are also generic CDN providers and I do not feel comfortable adding them without knowing the source myself
0.0.0.0 d3rt1990lpmkn.cloudfront.net
0.0.0.0 d360616xvwhw9g.cloudfront.net
0.0.0.0 gtssl2-ocsp.geotrust.com # This is an Online Certificate Status Protocol server. While it could certainly be used for tracking, blocking it has serious security ramifications that I'm uncomfortable with https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol
0.0.0.0 redirector.gvt1.com # I believe this one gets blocked periodically and causes a ton of broken functionality
0.0.0.0 securepubads.g.doubleclick.net # this one is in mvps.org list - but commented out. They did not provide a reason to comment it out. I've never seen blocking doubleclick break anything, so I am happy to add it
0.0.0.0 seen-on-screen.thewhizmarketing.com # added
0.0.0.0 server-54-230-216-203.mrs50.r.cloudfront.net # another generic CDN service
0.0.0.0 tracking.tidalhifi.com # added
0.0.0.0 vt.myvisualiq.net
0.0.0.0 www.omaze.com # not really sure about omaze so I'm going to hold off on it
0.0.0.0 omaze.com
```

**Comment by dnmTX** [comment]
@lightswitch05  found one more(in one of the inline scripts in `newsweek.com`).Opening a issue just for one domain feels kind of excessive so i'll post it here.There a several already added,i guess this one was missed:
`uat-net.technoratimedia.com`

Thank you !

**Comment by lightswitch05** [comment]
@dnmTX added in https://github.com/lightswitch05/hosts/commit/6eda9275ed097b1d2b9866e70411ffda6450d52f
