### ISSUE TITLE
fundingchoicesmessages.google.com

### ISSUE THREAD

**Issue by 3xploiton3** [lightswitch05/hosts#250]
https://www.musixmatch.com/ its broken

fundingchoicesmessages.google.com

![image](https://user-images.githubusercontent.com/19517680/104257719-a8ecca80-54b0-11eb-9f8e-07cb48a38b01.png)

relate
https://github.com/AdguardTeam/AdguardFilters/issues/71907#issue-782495494

**Comment by dnmTX** [comment]
Just for reference see https://github.com/StevenBlack/hosts/issues/1503. 
I just couldn't find any relation between the two but concidering that NextDNS is involved,everything is possible.

**Comment by lightswitch05** [comment]
Added by #82 - I'm not particularly keen on removing this one based on poor coding practices and failure to check/catch the error

**Comment by lightswitch05** [comment]
Looks like the website is working fine for me
