### ISSUE TITLE
new domains to block: rum counters cdnvideo

### ISSUE THREAD

**Issue by Alex-B-Buf** [lightswitch05/hosts#251]
Hello,

I would like to suggest adding these domains to the block list:

```
plstat01.cdnvideo.ru
plstat02.cdnvideo.ru
rum.cdnvideo.ru
rum2.cdnvideo.ru
rum3.cdnvideo.ru
rum4.cdnvideo.ru
rum5.cdnvideo.ru
rumstat-01.cdnvideo.ru
rumstat-02.cdnvideo.ru
rumstat-03.cdnvideo.ru
```

These are analytics counters that can often be found on various Russian sites with video.
For example: [after playing the video here](https://mir24.tv/news/16443784/vostochnyi-bazar-v-posolstve-afganistana-v-tadzhikistane-proshla-neobychnaya-vystavka) requested `plstat#` subdomains and sometimes `rum#`.

It seems that these are all existing varieties domains with counters, at least that I have come across in a few months.
I think it might be useful in the list.

**Comment by lightswitch05** [comment]
Added, will be in the next release. Thanks @Alex-B-Buf! (sorry about the slow response)
