### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by obeho** [lightswitch05/hosts#253]
Hello,
 
The domains `flipboard.com` & `www.flipboard.com` are in the _Tracking Aggressive_ list, causing the website Flipboard to not resolve. [They](https://en.wikipedia.org/wiki/Flipboard) are a news aggregator company, not a traditional news company. Their app aggregates content from social media, news feeds, etc. I don't see any controversy surrounding them. The domains don't have any tracking/malicious CNAME affiliated.

So I believe this is a false positive and can be removed from the list.

**Comment by lightswitch05** [comment]
Hey @obeho - I added this to the aggressive list because I had an android phone that flipboard was preinstalled on and I could not uninstall it. I would occasionally see it making requests despite it not being used.

I encourage people to not use the aggressive list.

**Comment by obeho** [comment]
I understand that they tied-up with some OEM. My phone too contains some pre-installed apps, like Whatsapp, Youtube. Any pre-installed apps try to call home (else it defeats purpose of the partnership) surping up any data they can from the phone. Their app contains whole load of [trackers](https://reports.exodus-privacy.eu.org/en/reports/162958/) too. I'd assume they do all the data collection through those ad-domains, but not through the `flipboard.com` domain.

I got your point that this _is a aggressive block list for tracking, geo-targeting, & ads_. But Flipboard 'app' & Flipboard 'domain' are not the same. The latter is just a normal domain.

I honestly thought this was in the list by mistake, and opened the ticket coz of this _If you find something in this list that you think is a mistake_

If you still think this domain should be blocked. Cool.

P.S. I use your list on PC on browser, and wondered why flipboard wasn't getting resolved.
