### ISSUE TITLE
Why are Duckdns hosts are blocked (Mine)

### ISSUE THREAD

**Issue by kdpuvvadi** [lightswitch05/hosts#254]
**False positive?**

Prove it. Do your research. I spend a lot of time working on this list, if you think you've found an issue, put the effort into it to prove it to me. Give me links to verify. I added the domain to the list, so I think it should be blocked. The burden of proof is on you. Please review these common issues before opening a ticket: https://github.com/lightswitch05/hosts#common-issues

Even though i use Cloudflare API to change DNS for Home network, i'm still using DuckDNS. Most of my duckdns subdomains are in the aggressive tracking list.  They don't have tracking or ads.

**Comment by lightswitch05** [comment]
Hey @kdpuvvadi. My personal opinion is that a lot of dynamic dns services are plagued with malware. I recommend not using the aggressive list of it is causing issues. 

* https://www.bleepingcomputer.com/news/security/new-norman-cryptominer-uses-dynamic-dns-for-c2-communication/
* https://urlhaus.abuse.ch/url/171414/
* https://blogs.cisco.com/security/dynamic-detection-of-malicious-ddns
* https://continuitycentral.com/index.php/news/technology/5901-neustar-highlights-rise-in-ransom-related-ddos-attacks-extortion-demands-grew-in-2020

**Comment by kdpuvvadi** [comment]
it's not an issue, i was shocked that mine was on the list, it was just Homeassistant instance, looks like i need to move it to Cloudflare then.

**Comment by lightswitch05** [comment]
I can explain that more. I didn't add your sub domains directly. My list automatically populates sub domains of blocked root domains. You can read more https://github.com/lightswitch05/hosts/issues/245#issuecomment-753021128

**Comment by lightswitch05** [comment]
@kdpuvvadi - which domain is it? I can whitelist it for you

**Comment by kdpuvvadi** [comment]
kdpuvvadi.duckdns.com

**Comment by lightswitch05** [comment]
That one isn't in my list 🤷

**Comment by lightswitch05** [comment]
Hmmm... ok nevermind, that one is in my list! I don't know how I missed it. I'll whitelist it now

**Comment by lightswitch05** [comment]
Added the whitelist, it will be removed in the next release. Sorry about the problems it caused

**Comment by thomasmerz** [comment]
@lightswitch05 
> My personal opinion is that a lot of dynamic dns services are plagued with malware. I recommend not using the aggressive list if it is causing issues

I don't like general suspicion for any dynamic dns services… There are many people using this without doing any "evil", but only some are doeing evil stuff. Please let's only block those evil subdomains and not a whole domain annoying possibly many unguilty admins and users!
