### ISSUE TITLE
bill.com is blocked

### ISSUE THREAD

**Issue by emok93** [lightswitch05/hosts#255]
![image](https://user-images.githubusercontent.com/75645944/106896311-04c50080-66b7-11eb-920d-fd9bf4654182.png)

**Comment by lightswitch05** [comment]
I do not block `sg.bill.com`- but I do block `sendgrid.net`. I think this is the fist time I've received a complaint about their root being blocked.

In the mean time whitelist `sg.bill.com` on your side and we can leave this ticket open to see if anyone else is having similar issues.

**Comment by lightswitch05** [comment]
See #150

**Comment by emok93** [comment]
That's what I did. I figure they're using sendgrid to track the click. Thank you!
