### ISSUE TITLE
FP: places.aviasales.ru

### ISSUE THREAD

**Issue by k03mad** [lightswitch05/hosts#256]
Hello,

Entry `0.0.0.0 places.aviasales.ru` blocks airport suggest at search here: https://www.aviasales.ru / https://www.aviasales.com

Example request: https://places.aviasales.ru/v2/places.json?locale=en&max=7&term=lake&types[]=city&types[]=airport

**Comment by lightswitch05** [comment]
This is an old one! I used to have a lot more of their site blocked, but had to adjust it for https://github.com/StevenBlack/hosts/issues/813 - might as well delete this one as well

**Comment by lightswitch05** [comment]
will be removed in the next release, thank you for the detailed ticket and for being patient for my slow response.
