### ISSUE TITLE
FP: pics.avs.io | auth.avs.io

### ISSUE THREAD

**Issue by k03mad** [lightswitch05/hosts#257]
I found a couple more aviasales domains that I don't think should be blocked
refs: https://github.com/lightswitch05/hosts/issues/256

```
pics.avs.io
```

Air carriers images are loaded from this domain
Example link: https://www.aviasales.com/search/MOW0303NYC1
Example images: https://pics.avs.io/99/36/KL@2x.png http://pics.avs.io/120/30/S7.png

```
auth.avs.io
```

Blocks authorization at ru domain: https://www.aviasales.ru/
Top right corner with avatar

**Comment by lightswitch05** [comment]
removed in next update 👍
