### ISSUE TITLE
Search Suggestions - Home Depot iOS App

### ISSUE THREAD

**Issue by adam8833** [lightswitch05/hosts#260]
When doing a search on the Home Depot app on iOS, the suggestions do not populate when typing.  

www.thdws.com is being blocked which is causing it to not function.  Please consider whitelisting.

**Comment by lightswitch05** [comment]
Verified on the website too, `https://www.thdws.com/TA2/search?term=led&e=TYPE_AHEAD_E_PARAM&callback=termCallback`

Will be removed in the next update, thanks for the ticket!
