### ISSUE TITLE
Monoprice.com Customer Reviews 

### ISSUE THREAD

**Issue by adam8833** [lightswitch05/hosts#261]
Consider whitelisting static.www.turnto.com as this blocks customer reviews on monoprice.com

Test by going to https://www.monoprice.com/product?p_id=29474 and then clicking on Customer Reviews.

**Comment by lightswitch05** [comment]
Same issue on `https://www.morebeer.com/products/brewbuilt-icemaster-max-4.html`

**Comment by lightswitch05** [comment]
For now, I'm going to move this one to the aggressive list

**Comment by lightswitch05** [comment]
Change will be in the next release, thanks for the quality ticket @adam8833 !
