### ISSUE TITLE
quantum adlist

### ISSUE THREAD

**Issue by trhr** [lightswitch05/hosts#264]
So, I saw you had been giving these guys shit for some time for stealing open source code. I found proof.

They released their source under the Unlicense, but they stole their installer script from MIT-Licensed hectorm/hblock

Unlicense is _not_ compatible with MIT License. About the only thing not compatible with MIT License is a public domain license. They are definitely shady.

Keep fighting the good fight.

**Comment by lightswitch05** [comment]
Haha thanks @trhr - I'd like to qualify that my goal is for them the give credit to their sources according to their licenses. Otherwise I have no interest in them, the project, or giving anyone a hard time.

**Comment by trhr** [comment]
Agreed. I think if their stuff was licensed correctly, there would be no problem. But if their stuff was licensed correctly, there would be no project. :)

I only found out about it because they're spamming FOSS-related channels and groups with requests for donations for their service... which isn't even FOSS... which, turns out, steals FOSS... but, i wanted to make you aware in case you had some ongoing DMCA takedown or something.

**Comment by hectorm** [comment]
Hi, I came across this issue and I would like to comment that I've opened in their GitLab a request to change the license.

https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/issues/31

If they don't comply I'm willing to submit a DMCA request since it is not nice to steal the work of others, including my own project and sources like this one.

Thanks @trhr for pointing me to this in hectorm/hblock#73.

**Comment by dnmTX** [comment]
> that I've opened in their GitLab a request to change the license.

@hectorm the link you provided doesn't exist anymore(just FYI). 
I just read some of the issues there and i can only say i'm sorry that you guys have to deal with such a ignorance and disrespect.

**Comment by lightswitch05** [comment]
The link no longer works because they already deleted it

**Comment by lightswitch05** [comment]
I just want to add that I don't believe they are using my list anymore, so I don't have any standing on a take down request. I think what they are doing is wrong, but myself or this project isn't related
