### ISSUE TITLE
[FALSE-POSITIVE?] continuum.dds.microsoft.com

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#265]
@lightswitch05 as i'm not sure that you saw my **ping**,just in case i'm posting it here to your attention.
We have a false-positive request at [Ultimate-Hosts-Blacklist](https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues/164),let me know what you think. Thank you 👍 

P.S. Take a look at `cs.dds.microsoft.com` as it was moved to the extra list as well.

**Comment by lightswitch05** [comment]
Thanks @dnmTX - I did see the ping but I haven't been able to sit down and fully research it yet. It will probably be sometime next week.

**Comment by dnmTX** [comment]
Got it. As long as you on top of it it's all good 😉 Will wait for update. Thank you 👍

**Comment by dnmTX** [comment]
@lightswitch05 on another note i just noticed that the images on your website(fron page here as well) are not showing because
they're fetched from `block-test.developerdan.com` which is blocked(listed) in your own list. What's up with that? 🤔 

![Developer Dan's Hosts](https://user-images.githubusercontent.com/34774426/111262062-8af72f80-85f1-11eb-88b1-e69af6632020.png)
![Capture](https://user-images.githubusercontent.com/34774426/111262073-8e8ab680-85f1-11eb-890c-34e7cb1b0b45.PNG)

**Comment by lightswitch05** [comment]
Ha! Those 'images' are my logo, it's supposed to look like that. Your link showing 'block-test' is at the bottom of the page, and is a simple test if you are using one of my lists or not

**Comment by lightswitch05** [comment]
Logo: https://www.github.developerdan.com/hosts/logo.png

Block test: https://block-test.developerdan.com/

**Comment by lightswitch05** [comment]
I really don't want to remove this one. I've never heard any complaints other then this single one you linked to. If there is only 1 failure in `N` number of people using the list, where `N` is significantly large enough, then I would rather that 1 person just whitelist the broken domain then have it whitelisted for `N` people who were previously benefiting from the block.

I'm happy to reconsider if this become a bigger issue.

**Comment by dnmTX** [comment]
>  I've never heard any complaints other then this single one you linked to

@lightswitch05  found three @crazy-max's(will post here so we can keep track):
https://github.com/crazy-max/WindowsSpyBlocker/issues/300
https://github.com/crazy-max/WindowsSpyBlocker/issues/206
https://github.com/crazy-max/WindowsSpyBlocker/issues/190

> I'm happy to reconsider if this become a bigger issue

I'm fine either way,at least,now there is some record here. Thank you 👍

**Comment by WaLLy3K** [comment]
I've had someone note to me that `continuum.dds.microsoft.com` was responsible for the Microsoft "Your Phone companion app" not working properly, as mentioned [here](https://www.reddit.com/r/pihole/comments/drylpk/pihole_and_your_phone_companion_app_microsoft/). This is the only list that [I recommend](https://firebog.net/) which contains it, so I thought I'd +1 here before adding it to my whitelist suggestions. 🙂

**Comment by lightswitch05** [comment]
Thanks for the update @WaLLy3K - it will be removed from this list and added to my aggressive list in the next update 👍
