### ISSUE TITLE
[False Positive] app.powerbi.com

### ISSUE THREAD

**Issue by thexile** [lightswitch05/hosts#267]
app.powerbi.com is domain for Microsoft Power BI and it shouldn't be blocked.

**Comment by lightswitch05** [comment]
Thanks for your input @thexile, but being owned my Microsoft doesn't mean it doesn't not engage in Ads & Tracking. Would you like to provide more information backing up your request?

Per my issue ticket for reporting false positives:

> Prove it. Do your research. I spend a lot of time working on this list, if you think you've found an issue, put the effort into it to prove it to me. Give me links to verify. I added the domain to the list, so I think it should be blocked. The burden of proof is on you.

**Comment by thexile** [comment]
Do you have Power BI account and do you know what it is?

**Comment by lightswitch05** [comment]
I understand that PowerBi is a reporting tool - perhaps like Tableau. What I'm unclear on is if PowerBi has its own data-collection tools, or if it is only for reporting and does not collect any data?

Unfortunately this is one of my older list additions - before I kept proper notes as to why I was blocking each domain - so I cannot really understand why I thought it should be blocked. Original commit: https://github.com/lightswitch05/hosts/commit/3e197ea672051251680cf35284f334a631294345

**Comment by thexile** [comment]
As per my understanding Power BI collects data only if the user uploads to it. Power BI does not collect data in the background without user consent. More documentation from Microsoft can be found here: https://docs.microsoft.com/en-us/power-bi/fundamentals/power-bi-overview

**Comment by lightswitch05** [comment]
I'm convinced to remove this one, thank you for your patience with me.
