### ISSUE TITLE
I need a sample with a different style

### ISSUE THREAD

**Issue by robin98** [lightswitch05/hosts#268]
Hello my friend. I need your help.
The current sample of your blocklist is useless for me. I need a sample **without** 0.0.0.0 in the beginning of the addresses, just simple address in each line of the file.
Where can I get this?

**Comment by lightswitch05** [comment]
Sorry, I only have hosts formatted lists. What tool does not accept hosts format?

**Comment by robin98** [comment]
> Sorry, I only have hosts formatted lists. What tool does not accept hosts format?

I use [Technitium DNS Server]([url](https://technitium.com/dns/)) and this application supports only simple form for it's block list.

**Comment by lightswitch05** [comment]
The documentation is bad, but the screen shot shows it is using Steven Black's hosts project - which is the same format as this project - so it should work fine.
