### ISSUE TITLE
[false-positive] o.aolcdn.com

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#27]
@lightswitch05  what was the reason to block this one? It delivers images/fonts/icons(didn't see any telemetry/ads/tracking crap):
![aolcdn](https://user-images.githubusercontent.com/34774426/47195270-c8700980-d320-11e8-976a-7ef23469da2d.PNG)

Some pages look weird/incomplete without it.As seen here:
https://www.autoblog.com/2018/10/18/2018-audi-r8-v10-plus-competition-package/

**Comment by lightswitch05** [comment]
@dnmTX that domain was used to serve ads on techcrunch.com. The full URL was `https://o.aolcdn.com/ads/adsWrapper.js`. Now they are using `s.aolcdn.com` instead. It looks like this is probably a generic CDN domain that can be used to host anything, so I'll remove it.

**Comment by dnmTX** [comment]
Thanks @lightswitch05  👍
