### ISSUE TITLE
malwaredomains blocklist is dead

### ISSUE THREAD

**Issue by ahoier** [lightswitch05/hosts#273]
malwaredomains is dead?  At least for 6 monthhs or so it seems.......?  my pihole was fetching that list from the beginning but recently noticed the page is now simply 127.0.0.1 localhost

appararntly they've cut ties?  And have no public available list (in the mean time, I just switched my resolver to 1.1.1.2 and 1.0.0.2 for malware blocking instead according to https://cloudflare-dns.com/family/

**Comment by lightswitch05** [comment]
I'm sorry @ahoier - I'm not sure how this relates to my project?

**Comment by ahoier** [comment]
I noticed the malware domains was listed on the homepage? Lol...err what I
assumed was your page lol oops.  The page was at developerdan.com/blocklist
and followed a link to source in GitHub which brought me here. Or so I
think lol.  I could be wrong since I’m new to GitHub

Sorry lol

**Comment by lightswitch05** [comment]
Oh! I understand now, that project is over here: https://github.com/blocklist-tools

I think it's still nice to have the list searchable for historical data, but yes, it's been dead a while now.

**Comment by ahoier** [comment]
Ahh! Good point, perhaps it’s by design then to coincide with the
“blocklist search” feature running on his site then, that totally makes
sense; if that is the case.

**Comment by lightswitch05** [comment]
Yes, I like the historical data. You can see they removed all the domains on November 11/12: https://blocklist-tools.developerdan.com/blocklists/a1e9353e-27a1-4fc6-99d0-b2aac5390a24
