### ISSUE TITLE
New Facebook domain: fb.watch

### ISSUE THREAD

**Issue by Kezxo** [lightswitch05/hosts#274]
Domain:

`fb.watch`

Stumbled on a link like this, it's used for shorter links to videos I believe.

More info: https://urlscan.io/domain/fb.watch

**Comment by lightswitch05** [comment]
Great find! I've been having some technical difficulties with this project the past few days, I'll get this added as soon as I'm able to

**Comment by lightswitch05** [comment]
Will be included in the next release!
