### ISSUE TITLE
blocking Perimeterx breaks Sam's Club App

### ISSUE THREAD

**Issue by sdrapha** [lightswitch05/hosts#276]
First of all, Thanks for the list Daniel!!

I just wanted to bring up the point that: blocking those domains ( perimeterx ) breaks Sam's club app.
![image](https://user-images.githubusercontent.com/25059996/117474170-ab27d880-af28-11eb-9947-bf5fd81f3177.png)
I whitelisted them on my box and the app works for me now, I'm posting here in case anyone comes loking for info.
From my quick research, perimeterx is an anti-bot company ultimately owned by google and It works by AI fingerprinting, so that sucks. But blocking that domain breaks legitimate stuff and apps.
Feel free to close this issue if you want to. I just wanted to bring to your attention.
Thanks

**Comment by lightswitch05** [comment]
Thanks for the fantastic ticket @sdrapha - I'm sure this will be useful to others. I believe this is the first time I've heard of anything breaking for this domain - lets hope it doesn't become a pattern. Lets leave the ticket open for a while to see if anyone else has something to say. If the ticket become stale, I'll eventually close it out.

Thank you again for the great report, I'm glad you've found the list to be useful :)

**Comment by lightswitch05** [comment]
I'm going to close this one out now since no one else has commented on it.
