### ISSUE TITLE
Microsoft Edge profile syncing (edge.activity.windows.com; edge-enterprise.activity.windows.com)

### ISSUE THREAD

**Issue by jgrisham** [lightswitch05/hosts#279]
Microsoft Edge _(at least on Windows)_ currently will not sync browser profiles without access to _(among perhaps others not currently blocked)_:

> edge-enterprise.activity.windows.com
> edge.activity.windows.com

They are currently on the _ads-and-tracking-extended_ list.

Whitelisting these sites allowed syncing to work again.

Thank you for sharing your list publicly!

Reference: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-endpoints

**Comment by lightswitch05** [comment]
Ugh, these Microsoft ones are getting annoying. I'll list them here for tracking: #242 #161 #265 #125

**Comment by jgrisham** [comment]
(at least they document the domain names used by most of their products, unlike many consumer companies)

**Comment by gyCfjSnO** [comment]
This could be closed possibly now you've resolved my other post?

**Comment by gyCfjSnO** [comment]
> Ugh, these Microsoft ones are getting annoying. I'll list them here for tracking: #242 #161 #265 #125

This issue could probably be closed now that you've addressed my issue

**Comment by gyCfjSnO** [comment]
#293

**Comment by lightswitch05** [comment]
Yup, this is resolved now, thanks for the reminder @gyCfjSnO
