### ISSUE TITLE
Blocking api-statcloud.a03.yahoodns.net breaks Yahoo Fantasy Sports

### ISSUE THREAD

**Issue by kellyhirano** [lightswitch05/hosts#28]
Blocking api-statcloud.a03.yahoodns.net breaks Yahoo Fantasy Sports. The "stat" part of the domain is around sports stats for the fantasy game, not tracking. Please remove this to allow the Yahoo Fantasy Sports app to work properly and update player stats. I'm happy to prove this out in any way that would help. Thanks!

**Comment by lightswitch05** [comment]
@kellyhirano thanks for the report, it has been removed

**Comment by kellyhirano** [comment]
Thanks for the quick fix!
