### ISSUE TITLE
13WHAM local news false-positive(s) ?

### ISSUE THREAD

**Issue by peatrick** [lightswitch05/hosts#282]
> **False positive?**
> Prove it. Do your research. I spend a lot of time working on this list, if you think you've found an issue, put the effort into it to prove it to me. Give me links to verify. I added the domain to the list, so I think it should be blocked. The burden of proof is on you. Please review these common issues before opening a ticket: https://github.com/lightswitch05/hosts#common-issues

Only just recently decided I should invest a little time modernizing my tracking lists, as everything I've been running (primarily WaLLy3K stuffs) was from pre-v5.0 era Pi-hole.  Great website, although this [image](https://www.github.developerdan.com/hosts/logo.png) drove me NUTS initially.  Touché.  Regardless, wonderful lists.

Could you help me understand your aversion to 13WHAM, pretty please?  Perhaps you just really detest local _Rochester News, Weather & Sports_ or maybe [this](https://13wham.com/) is a false positive?  
```
Match found in https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt:
   13wham.com
   beta.13wham.com
   client.13wham.com
   events.13wham.com
   li.13wham.com
   m.13wham.com
   ns1.13wham.com
   ns2.13wham.com
   ns3.13wham.com
   ns4.13wham.com
   origin.13wham.com
   rs-stripe.13wham.com
   sli.13wham.com
   test.13wham.com
   www.13wham.com
```
![image](https://user-images.githubusercontent.com/26148066/119551210-5e852f80-bd67-11eb-823a-1760bb4cd5b9.png)

**Comment by lightswitch05** [comment]
Oh boy! That is certainly a false positive.

According to my notes, I added it for `https://13wham.com/api/rest/audience/more?section=13wham.com/buffalo-plus&limit=3` on `https://cbs6albany.com/` - but obviously shouldn't have been added to start with.

Will be removed in the next release. Thank you for the detailed ticket!

**Comment by lightswitch05** [comment]
Oh also, you are not the first one to complain about the image! Muahahahah! I had a much better idea in mind for a project image, but I'm not a graphic artist, so I had to find something within my skill set to create.

**Comment by peatrick** [comment]
> Thank you for the detailed ticket!

Your documentation is stupendous.  I was honestly worried I hadn't included enough of my own research, so your process is obviously working quite well.

You had me running circles, unable to figure out why all those thumbnail images were showing as broken links.  It took me multiple minutes to finally `View page source` and stop chasing my tail.  You had me laughing balls over chasing my own tail in such a manner.  Bravo, sir.  Thanks again for the prompt response and detailed list(s).  Stay safe.
