### ISSUE TITLE
Why is r20.rs6.net blocked?

### ISSUE THREAD

**Issue by lightswitch05** [lightswitch05/hosts#285]
@lightswitch05 what can you tell me about `r20.rs6.net` ? I couldn't open a link yesterday because of it that didn't come from some random website.

_Originally posted by @dnmTX in https://github.com/lightswitch05/hosts/issues/284#issuecomment-857803192_

**Comment by lightswitch05** [comment]
The domain `rs6.net` is owned by Constant Contact. They are a marketing company, looks like they might specialize in email marketing. I believe this domain is specifically a link tracking domain. Here is someone else complaining that its blocked (by Peter Lowe's list) https://community.constantcontact.com/t5/Get-Help/r20-rs6-net-error/m-p/336137

**Comment by dnmTX** [comment]
Sorry,i should've do that 👍

**Comment by lightswitch05** [comment]
Constant Contact's website: https://www.constantcontact.com/

**Comment by dnmTX** [comment]
The link was actually part of email sent to me,from a trusted source and was linking to a pdf. I can send it to your email if you want to see it,but i'm not posting it here.It something that is more personal.

**Comment by lightswitch05** [comment]
Feel free to whitelist it @dnmTX - we can leave this ticket open if you like and we can see if anyone else is having issues. `rs6.net` was added to the list Jun 30, 2020 - and this is the first complaint I've seen about it. Lets see if anyone else is having issues.

**Comment by dnmTX** [comment]
Sure,no problem. Let's leave it open for now and will go from there 👍

**Comment by dnmTX** [comment]
Dan @lightswitch05,as we agreed to send you email about my JavaScript missfortunes.
The thing is,no email of yours is listed here 🤔

**Comment by llacb47** [comment]
@dnmTX it's daniel at his website domain

**Comment by lightswitch05** [comment]
Interesting.... I occasionally get whitelisting/blocking requests via email. I assumed it must be listed on my GitHub profile or something. Anyways, `daniel` (at) `developerdan` (DoT) `com`

**Comment by lightswitch05** [comment]
Thanks @llacb47 - it must be listed somewhere!

**Comment by dnmTX** [comment]
Got it,thank you both 👍 
Off to write email now 😄

**Comment by dnmTX** [comment]
@lightswitch05 just to show you. Even though the domain is blocked the iFrame is still there,sucking up additional memory:

![Capture](https://user-images.githubusercontent.com/34774426/121466427-0bbd9180-c97d-11eb-97cc-f5610ecd640f.PNG)

**Comment by llacb47** [comment]
what comment did you delete?

**Comment by lightswitch05** [comment]
The one with my email address in it. I'm happy for people to email me, but I'd rather keep it at a minimum

**Comment by llacb47** [comment]
oh, sorry
