### ISSUE TITLE
Missing facebook/Oculus domain

### ISSUE THREAD

**Issue by traveltrousers** [lightswitch05/hosts#286]
My Oculus Quest connects to this domain through pihole...

graph.facebook-hardware.com

**Comment by lightswitch05** [comment]
wow, thanks for letting me know! It will be added in the next list update

**Comment by lightswitch05** [comment]
The good news is that it is a CNAME for `star.c10r.facebook.com` - which is blocked in the list, but I'm still adding the domain to the list
