### ISSUE TITLE
Ads and Tracking File

### ISSUE THREAD

**Issue by stevefxp1** [lightswitch05/hosts#288]
Hello,

Thank you for creating and maintaining this list. When I am loading it in Pi-Hole I am noticing an error that says 1 domain invalid. It lists githubusercontent.com as what I believe is the offending domain??

Thanks,
Steve

![Screenshot 2021-06-22 230327](https://user-images.githubusercontent.com/70986226/123028852-154bee00-d3ae-11eb-93b7-bf5c3198cd10.png)

**Comment by lightswitch05** [comment]
Ahhh! Thank you for bringing this to my attention. It should be `xn--gthubusercontent-8rb.com` - it will be fixed in the next update. Thank you again!

**Comment by lightswitch05** [comment]
To provide a bit extra information- the domain is `gíthubusercontent.com` - notice the `í` in git instead of `i`- I do not recommend visiting the domain as it's likely malicious.

**Comment by dnmTX** [comment]
Just checked my router's log:
![DD-WRT (build 40270M) - Syslogd](https://user-images.githubusercontent.com/34774426/123033364-47108500-d3ad-11eb-9ab3-60aee27e45bd.png)
dnsmasq apparently can't read those characters 😄
