### ISSUE TITLE
domains[continuing...]

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#29]
@lightswitch05  if you don't mind to test this one,if it doesn't break anything,add it.Thanks.
Link: https://www.cbsnews.com/live/

`imasdk.googleapis.com`  
![cbs1](https://user-images.githubusercontent.com/34774426/47398534-0a6ec600-d6fa-11e8-9467-e7042716911e.PNG)

Not sure what to make of it.My adblocker is blocking it on some sites,not blocking it on others but it delivers "in player" ads for sure.When i blocked it on the mentioned link above got this error in chrome's dev tools but nothing broke though:
![cbs3](https://user-images.githubusercontent.com/34774426/47398520-004cc780-d6fa-11e8-9bae-12d74f864d21.PNG)
EDIT: On my end,once i blocked it,it seems that the videos started loading faster.

**Comment by anudeepND** [comment]
@dnmTX Interactive Media Ads SDKs. It should be blocked, I already have it in my host file. For more info - https://developers.google.com/interactive-media-ads/

**Comment by dnmTX** [comment]
@anudeepND  oh...i see now.Well..unfortunately because i'm loading your lists from the [Ultimate-Hosts-Blacklist](https://github.com/Ultimate-Hosts-Blacklist/anudeepND_blacklist_ad_server) and it's in the middle of filtering...still,and on my end it's set up to load every tuesday and the domain in question didn't make it...yet to the `clean.list`.That's why i'm missing it so i'll have to reload it tomorrow again when it's finish filtering.
Thank's for pitching in though 👍

**Comment by lightswitch05** [comment]
@dnmTX I could not get that live steam to play with `imasdk.googleapis.com` blocked

**Comment by dnmTX** [comment]
@lightswitch05  thanks for testing it. @anudeepND you mind removing it from your lists as well due to breaks the `cbsnews.com's` player and probably other online players will be affected as well.

**Comment by anudeepND** [comment]
@dnmTX sure. Will look into it...
