### ISSUE TITLE
[to add ???] more Google

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#290]
Dan @lightswitch05 found them when researching something else. 
I can't recall seeing any of them out and about(😄), but the sole fact is that they exist and have proper certification and IP's.
We can wait and leave that issue open just to have some records when the time comes 👍 

![VirusTotal](https://user-images.githubusercontent.com/34774426/125147765-f90cb880-e0f2-11eb-9aab-c4c80dd81852.png)

`google-analytics-cn.com`
`googleadservices-cn.com`
`googlevads-cn.com`
`doubleclick-cn.net`
`*.fls.doubleclick-cn.net`
`googletraveladservices-cn.com`
`googletagservices-cn.com`
`googletagmanager-cn.com`
`googlesyndication-cn.com`
`app-measurement-cn.com`
`gvt2-cn.com`
`2mdn-cn.net`
`admob-cn.com`

**Comment by anudeepND** [comment]
Are these domains specific to China? Because they have a firebase domain with .cn tldr. https://firebase.google.cn/

**Comment by dnmTX** [comment]
> Are these domains specific to China? Because they have a firebase domain with .cn tldr. https://firebase.google.cn/

Naah...that `-cn` stands for something else.I forgot already,to be honest but if you do some research it will show 👍

**Comment by dnmTX** [comment]
Dan @lightswitch05 see if you can add something from here as well:
https://www.linkscollections.com/computers-electronics-and-technology/advertising-networks/

**Comment by dnmTX** [comment]
This,you definitely add:
![adgoogle net](https://user-images.githubusercontent.com/34774426/125357021-a7e80900-e32c-11eb-9ca6-ddf0fce7d0ee.png)

`0.0.0.0 adgoogle.net`
`0.0.0.0 www.adgoogle.net`

**CC @StevenBlack**  You as well 😉 👍

**Comment by lightswitch05** [comment]
Where are these coming from? I've never seen them before, and no other hosts list I know of contains them: [doubleclick-cn.net](https://blocklist-tools.developerdan.com/entries/search?q=doubleclick-cn.net)

**Comment by dnmTX** [comment]
> I've never seen them before, and no other hosts list I know of contains them

Me neither.I was just posting my findings so there is some record. Sooner or later Google will start using them.
We talking about Google here,not some startup.
Anyway,i didn't think that it will annoy you so much so...i'll just close this.
