### ISSUE TITLE
List of invalid domain names

### ISSUE THREAD

**Issue by Prajwal-Koirala** [lightswitch05/hosts#291]
```
0.0.0.0 0.0.0.0cdn.adx1.com
0.0.0.0 0.0.0.0hb.adx1.com
0.0.0.0 0.0.0.0rtb.adx1.com
0.0.0.0 0.0.0.0xml.adx1.com
0.0.0.0 0.0.0.0public21.bravenet.com
0.0.0.0 0.0.0.0s.moatpixel.com
0.0.0.0 0.0.0.0img.sedoparking.com
0.0.0.0 0.0.0.0www.sedoparking.com
0.0.0.0 0.0.0.0www1.sedoparking.com
0.0.0.0 0.0.0.0www2.sedoparking.com
0.0.0.0 0.0.0.0www4.sedoparking.com
0.0.0.0 0.0.0.0cdn-102.statdynamic.com
```

They all have catch-all SSL certificates or catch-all redirects, which means they'll accept any sub-domain, even if it's completely fake, as long as the domain name is correct and links to nothing.

- Get the domain name, then generate a random string and use it as a subdomain check. If it works, it's almost certainly a catch-all.

For instance, I randomly generated the string `vxd50kalrruejc18d486` and then put it in front of the domain name `vxd50kalrruejc18d486.cdn.adx1.com`, which is still legal.

Another example `fgldkjfdlkjhfdlkfghdlkjfdhlfkdnh.sedoparking.com` is still comletely valid.

### Global Cert
```
DNS Name=sedoparking.com
DNS Name=*.sedoparking.com
```

**Comment by lightswitch05** [comment]
Thanks @Prajwal-Koirala - I'm well aware of these wildcard domain issues, unfortunately there isn't a way for me to really know which subdomains in my list are valid and which aren't when the root domain is wild-carded.

I'm happy to add a `0.0.0.0` exclusion filter to solve these specific ones

**Comment by lightswitch05** [comment]
Removed

**Comment by Prajwal-Koirala** [comment]
@lightswitch05 
Take a look at this list, https://github.com/EFForg/privacybadger/blob/master/src/data/cname_domains.json you might want to add this too.

**Comment by lightswitch05** [comment]
Neat, I scrolled through an added a few of the common CNAMEs. Not interested in pulling in the whole list, because privacy badger operates within the browser and can make smart decisions about 1st party vs. 3rd party, but still a neat resource!

**Comment by dnmTX** [comment]
and all those `hostmaster.hostmaster.....` domains are registered in the `127.0.0.0/8` private range and therefore can not enter any system. I'm still not sure why you keeping them.You have like....7000 of them.
Just for example:
![Capture](https://user-images.githubusercontent.com/34774426/125682610-b3ed8d4b-7cfb-47e5-b68a-828e3f1ff3db.PNG)

**Comment by lightswitch05** [comment]
> You have like....7000 of them.

😆 I think that might be a bit of an exaggeration. I do have a system in place to ensure all the entries resolve, but I never considered ensuring they resolve to a non-local address. Interesting idea! I'll have to think about it more.

**Comment by Prajwal-Koirala** [comment]
> > You have like....7000 of them.
> 
> 😆 I think that might be a bit of an exaggeration. I do have a system in place to ensure all the entries resolve, but I never considered ensuring they resolve to a non-local address. Interesting idea! I'll have to think about it more.

Same, but the problem with this is that since they are so easy to change I can launch an attack and than remove all the records and ghost the domain

**Comment by lightswitch05** [comment]
maybe I should just whitelist `^hostmaster\.\S+`?

**Comment by dnmTX** [comment]
> 😆 I think that might be a bit of an exaggeration.

Sorry.....4008 to be exact:
![Capture1](https://user-images.githubusercontent.com/34774426/125684211-9ef39af6-ade7-41c7-b66a-d34117b86e18.PNG)

> maybe I should just whitelist ^hostmaster\.\S+?

That will be the best solution,no doubt 👍 
[result.txt](https://github.com/lightswitch05/hosts/files/6818617/result.txt)

**Comment by lightswitch05** [comment]
Done, it will be in the next release

**Comment by dnmTX** [comment]
> Done, it will be in the next release

Can't you make it whatever resolves in the private range just  to be ignored,or that's just to much of a hassle?

**Comment by dnmTX** [comment]
> Same, but the problem with this is that since they are so easy to change an attacker can launch an attack and than remove all the records and ghost the domain

@Prajwal-Koirala you have a point here but so far that didn't happened. I'm comparing it to another list,which contain similiar entries for a lon long time and all of them resolve in that private range. The thing is that,the curator is hard to argue with so i just stoped using it:
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/hosts
![Capture](https://user-images.githubusercontent.com/34774426/125686318-32c92cef-4af3-40de-b2a6-6a8c544022ad.PNG)

**Comment by Prajwal-Koirala** [comment]
> Done, it will be in the next release

If your adding this than u also might want to add a check where you check if the domain has a parking domain name server or cname

**Comment by dnmTX** [comment]
@lightswitch05  only by doing `nslookup` 👇 
![Capture1](https://user-images.githubusercontent.com/34774426/125719753-608cb5c0-5c55-4607-8e6c-bf3a05c08594.PNG)

**Comment by Prajwal-Koirala** [comment]
Hey @lightswitch05
What is your policy regarding catch-all subdomains that are entirely random?

What is your policy if I own `example.com` and am on one of your lists, and I have a bunch of completely odd subdomains like `gfjkgfhlkjgf.example.com` and `dvlkfdhfld.example.com`, are these still going to be on the list?

**Comment by Prajwal-Koirala** [comment]
@lightswitch05 

Why are u blocking ublock.org?

**Comment by lightswitch05** [comment]
Ublock is in my hate and junk list for being junk. It's not owned by ubllock origin.

**Comment by lightswitch05** [comment]
I'm ok with `thinkqanon.com` staying on the list even if it is for sell

**Comment by Prajwal-Koirala** [comment]
@lightswitch05 
Take a look at this
https://whotracks.me/trackers.html
