### ISSUE TITLE
Pluralsight library not working with s2.pluralsight.com blocked

### ISSUE THREAD

**Issue by SiggiSch** [lightswitch05/hosts#292]
Hi. Great list. Thank you for making it available and for your work.

To the Issue:
Browsing the [pluralsight library](https://app.pluralsight.com/library/) with `s2.pluralsight.com` being blocked, results in an empty page.

I guess you have to be signet-in to see it for yourself.
I could make a screen-cast if that helps to prove the issue.

**Comment by lightswitch05** [comment]
I added this entry on April 12th, 2021. My notes when I added it:

> added for https://s2.pluralsight.com/analytics/analytics-facade.v4.7.11.js on https://www.pluralsight.com/guides/composing-react-components-with-typescript    - I think its only analytics - but it could just be a static server - remove if someone complains

It will be removed in the next release. Thank you for the issue report!
