### ISSUE TITLE
Edge Sync broken by URL on Blocklist

### ISSUE THREAD

**Issue by gyCfjSnO** [lightswitch05/hosts#293]
The following URL breaks Edge Sync (passwords, bookmarks, history etc) as this is the URL for the sync server as confirmed when visiting edge://sync-internals/ in Edge and viewing the Server URL. 

`edge.activity.windows.com`

Also discussed here on Microsoft website - https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-endpoints

**Comment by lightswitch05** [comment]
I've moved `edge.activity.windows.com` and `edge-enterprise.activity.windows.com` to the aggressive list. It will be in the next release. Thanks for the report!

**Comment by gyCfjSnO** [comment]
#279
