### ISSUE TITLE
[WHITELIST] - assets.adobedtm.com

### ISSUE THREAD

**Issue by bakerboy448** [lightswitch05/hosts#295]
# Domain to be whitelisted/unblocked

* `assets.adobedtm.com`

## Where the blocked domain causes problems

* `https://secure.verizon.com/vzauth/UI/Login`

### Screenshot(s)
<details>

![image](https://user-images.githubusercontent.com/55419169/127705478-51b1b1f0-6046-474d-bd76-69817a323c0e.png)
![image](https://user-images.githubusercontent.com/55419169/127705501-24adabc8-e45c-4f81-b2ca-770413e43903.png)

**After Whitelisting the subject domain**
![image](https://user-images.githubusercontent.com/55419169/127705600-96862525-7a9c-451d-bd64-714a7cc724c0.png)
</details>

# Your setup
- **Browser:**
  -  Chrome 92.0.4515.107
- **Ad/content blocker:**
  -  PiHole

From Pihole for posterity
> Exact match for assets.adobedtm.com found in: - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

**Comment by dnmTX** [comment]
Cant't reproduce. Chromium here(90.0....) and domain is blocked on my end.

**Comment by bakerboy448** [comment]
It was annoyingly tricky to catch. Need to clear localdns & use incognito. Then it'll show up

**Comment by dnmTX** [comment]
> It was annoyingly tricky to catch. Need to clear localdns & use incognito. Then it'll show up

What does that tells you? That it's the blocked domain or just one of the many annoying Chrome so called security features.

**Comment by bakerboy448** [comment]
![2B2D79B1-63FB-4398-A70F-10DDEACE0146](https://user-images.githubusercontent.com/55419169/127724200-55f72439-105c-466c-b553-22b95484814b.jpeg)

that it's indeed pihole that was blocking it

**Comment by dnmTX** [comment]
One more time then: Can't reproduce ¯\_(ツ)_/¯

![Screenshot (10)](https://user-images.githubusercontent.com/34774426/127724640-e55ff566-f843-42b2-9fc3-ca51dd035cdf.png)

**Comment by bakerboy448** [comment]
Fair 🤷‍♂️
Let's blame chromium and Verizon  gremlins then?
