### ISSUE TITLE
[False Positive] interrupt.memfault.com

### ISSUE THREAD

**Issue by ahogen** [lightswitch05/hosts#296]
[interrupt.memfault.com](https://interrupt.memfault.com) is a blog about microcontroller development. I'm not sure how that qualifies as ads & tracking.

PiHole reported it being blocked by `ads-and-tracking-extended.txt`

Edit: I see now. You probably take issue with their company product, and therefore block the whole domain, even if their side-blog has largely nothing to do with the tracking in their commercial product.

**Comment by lightswitch05** [comment]
Original commit:

> Expanding already blocked hosts per pihole - aslo a couple new ones from techworld.com. memfault.com is an unknown from my phone.

I think this is just a straight up bogus entry that should have never been added to start with. I tend to be a bit more rigorous with my entries these days. It will be removed in the next release, thanks for the report!

**Comment by kuflierl** [comment]
> Original commit:
> 
> > Expanding already blocked hosts per pihole - aslo a couple new ones from techworld.com. memfault.com is an unknown from my phone.
> 
> I think this is just a straight up bogus entry that should have never been added to start with. I tend to be a bit more rigorous with my entries these days. It will be removed in the next release, thanks for the report!

it seems this was never removed, are you still planing to remove this @lightswitch05 ?
