### ISSUE TITLE
[false-positive] imagesvc.meredithcorp.io

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#297]
**Test site:**  https://www.dailypaws.com/

If you see any images,let me know and i'll close this issue.

**Comment by lightswitch05** [comment]
Thanks @dnmTX 

Added on Wed, 19 May 2021. Notes:

> pihole logs - common block - maybe aggressive? I have not context here

It will be removed in the next release. Sorry about the false positive.

**Comment by dnmTX** [comment]
Thanks 👍 

P.S. There is another `*.meredithcorp.io` entry that it's probably a good idea to be kept so don't remove the `meredithcorp.io` entirely.
