### ISSUE TITLE
False positive: acquisition-1.americanexpress.com [Breaks Pages]

### ISSUE THREAD

**Issue by JS876** [lightswitch05/hosts#298]
I noticed that acquisition-1.americanexpress.com was added to the blocklist. This causes a number of pages on the American Express website to fail to load. 

Replication Steps:

1. Block acquisition-1.americanexpress.com
2. Click "Cards" at top of page
3. Click "View All Credit Cards"
4. Page should fail to load correctly

![image](https://user-images.githubusercontent.com/37991727/130385698-72f38882-648c-4e80-8e4e-31cbdeb13e02.png)
![image](https://user-images.githubusercontent.com/37991727/130385868-bcda0910-d0fc-4d22-867c-f4e78f2e4593.png)
![image](https://user-images.githubusercontent.com/37991727/130385923-b89c744d-51ea-4fe1-861c-3e2aacec9745.png)

**Comment by lightswitch05** [comment]
Thanks for the report and screenshots @JS876 - it will be removed in the next release! Originally added in https://github.com/lightswitch05/hosts/commit/d672dbd65d96a5f9eabf890e74cc5bc8262ba7db
