### ISSUE TITLE
[New Domains] appinfo.garenanow.com statscollection.garenanow.com

### ISSUE THREAD

**Issue by NSABackdoors** [lightswitch05/hosts#302]
I was testing out League of Legends on Garena for the r/leagueoflinux community and saw that these 2 domains weren't being blocked.

Steps to reproduce:

1. Download the Garena installer.
2. Open the Garena installer, Garena will then try to connect to the domains.

I tried installing Garena on a brand new Operating System with the 2 domains blocked and the installer worked perfectly fine. Also logically speaking an installer shouldn't need internet access for such a small application.

Garena is a game library similar to Steam and the Epic Games store except only for a few games. Blocking these domains didn't impact my League install/experience, although I haven't tested out other games. I never had League try to connect to these domains so I'm guessing it's specific to the Garena application.

It also only ever happens when you're installing the application and never happens again in daily use.

Apologies if my knowledge isn't up to par, this isn't really my type of field so I don't have much experience with this.

**Comment by lightswitch05** [comment]
Hey @NSABackdoors, welcome to the project. Thank you for your very detailed instructions on how to reproduce the requests. Also, I really appreciate that you tested it out first.

> Apologies if my knowledge isn't up to par, this isn't really my type of field so I don't have much experience with this.

This was a perfect request, and they will be added in the next update. The one thing I ask is that you let me know if something starts breaking due to either of these blocks. Thanks!

**Comment by lightswitch05** [comment]
Good question @spirillen. I believe the installer in question is Garena PC: https://mobile.garena.sg/gpc
