### ISSUE TITLE
google fonts blocked

### ISSUE THREAD

**Issue by cottton** [lightswitch05/hosts#304]
f.e. at meet.google.com 

pihole:
fonts.gstatic.com
(blocked gstaticadssl.l.google.com)

See problem already described by a dude here: https://github.com/StevenBlack/hosts/issues/975

**Comment by dnmTX** [comment]
https://github.com/lightswitch05/hosts#google-fonts

**Comment by DevShubam** [comment]
This is already written in his “common issues”. 

`I do not block fonts.gstatic.com. However, I do block gstaticadssl.l.google.com. If you are using the Ads & Tracking list and are having issues with fonts.gstatic.com, then you might be using a blocker that blocks based on CNAME. Depending on your blocking tool, you might want to whitelist fonts.gstatic.com to prevent it from getting blocked by gstaticadssl.l.google.com CNAME. See: (ISSUE) #197, #136, #213`

https://github.com/lightswitch05/hosts#google-fonts

**Comment by d1nuc0m** [comment]
@lightswitch05 @pkaeding As this is a recurring issue, I would recommend to modify the readme, adding something like "(...) you might be using a blocker that blocks based on CNAME _(for example PiHole)_"

**Comment by lightswitch05** [comment]
@d1nuc0m PRs for the README/Website are welcome... ;)

**Comment by anhdao1520** [comment]
still not processed, domain gstaticadssl.l.google.com is still blocked
