### ISSUE TITLE
"Connection Refused" when attempting to pull your list using a pi-hole.

### ISSUE THREAD

**Issue by FlareHeart** [lightswitch05/hosts#306]
I love your list, and don't want to live without it. To that end, I have noticed an issue today that is impacting my ability to pull your list into my pi-hole. I am getting "Connection Refused" when I run the gravity update, and a curl on your URL returns an expired certificate. 

I'm not sure if this is something you can fix or not, but I really would like to be able to use your list again. 

Here's some error outputs for you, though I am not sure if it's something you can fix or not:

Curl output:
pi@pi-hole:~ $ curl https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

Excerpt of pihole gravity update: 
  [i] Target: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

**Comment by FlareHeart** [comment]
Nevermind me. Apparently something in my Raspi was out of date. I ran some raspbian updates/upgrades and rebooted and now it's working again.

**Comment by lightswitch05** [comment]
I'm glad you were able to figure it out. The list is hosted on GitHub, so all that is outside of my control anyways 👍

**Comment by FlareHeart** [comment]
I figured it might have been out of your hands, which is why I wasn't sure
if you could fix it, even if it was a true cert issue. I guess I just need
to be more on top of my updates from now on. Sorry to bother you! Thanks
for maintaining this awesome list!

~Trista
No trees were destroyed in the sending of this message, though a
significant number of electrons were terribly inconvenienced.
