### ISSUE TITLE
grnh.se

### ISSUE THREAD

**Issue by p1r473** [lightswitch05/hosts#308]
Hi Dan,
grnh.se is a URL shortener service for greenhouse.io
Based on you not blocking some other URL shortening services, as well as not blocking greenhouse.io, I was wondering if this may have been a false positive
Though I do agree that some URL shortening services may havesome level of click tracking.
This is on ads-and-tracking-extended.txt which may mean you've already increased the threshhold for blocking of this

**Comment by lightswitch05** [comment]
It will be removed in the next update. Thanks again!
