### ISSUE TITLE
CanYouBlockIt.com - Seems no matter which list I use multiple ad types and such make it through

### ISSUE THREAD

**Issue by fatalpuls3** [lightswitch05/hosts#312]
I have applied the Ads and Tracking, AMP Hosts, Hate and Junk lists along with the stock from Pi-Hole, I performed a gravity update and then went on to test with CanYouBlockIt.com in a private browser session no adblock plus enabled.  Multiple ads and sneaky things still make it through.  Am I expected to see this?  Ive even tried a MASSIVE amount of other individual lists to see if any of them help with the test on CanYouBlockIt.com but none are successful either.  Could you please direct me on why this site seems to "fail" the pi-hole test with your lists?

thanks

**Comment by lightswitch05** [comment]
Not all ads can be blocked using domain blocking (pihole), I recommend pairing it with a standard adblocker like uBlock Origin, that will give you the best coverage
