### ISSUE TITLE
blog.logrocket.com is blocked

### ISSUE THREAD

**Issue by pidus** [lightswitch05/hosts#314]
I use this host file in NextDNS. I found `blog.logrocket.com` to be blocked. Is it intentional?
![Screenshot_20211105-182010_Kiwi_Browser](https://user-images.githubusercontent.com/11857051/140512824-f4345910-8684-44b4-ac59-a25d397605a6.png)

Example link: https://blog.logrocket.com/self-hosted-fonts-vs-google-fonts-api/

**Comment by lightswitch05** [comment]
This is just a side-effect of the root domain being blocked. I'm happy to whitelist this one next time I'm at a computer 👍

**Comment by lightswitch05** [comment]
Never mind. It's not on my list. The service you are using automatically blocks subdomains of blocked roots. You'll have to make an exception on your side

**Comment by pidus** [comment]
Thanks for the info.
