### ISSUE TITLE
debugbear.com is blocked

### ISSUE THREAD

**Issue by pidus** [lightswitch05/hosts#315]
It seems `www.debugbear.com` is blocked. Any reason for this?
![Screenshot_20211105-214618_Kiwi_Browser](https://user-images.githubusercontent.com/11857051/140543452-892e91c2-3177-4227-ab1b-9bf399dba9ff.png)
Test URL: https://www.debugbear.com/blog/chrome-extension-performance-2021

**Comment by lightswitch05** [comment]
It's a tracking, see https://www.debugbear.com/docs/api

**Comment by pidus** [comment]
Ah, shame. Their blog is in the same domain so can't be unblocked. :(
I will set up an exception in NextDNS.
