### ISSUE TITLE
Unable to load content - Imgur.com

### ISSUE THREAD

**Issue by gyCfjSnO** [lightswitch05/hosts#321]
Unable to load content on ```imgur.com``` when the domain ```media-lab.ai``` is blocked as website requires access to ```js.media-lab.ai```.

https://www.reddit.com/r/pihole/comments/qtuw8g/imgur_not_working/

**Comment by lightswitch05** [comment]
Last I looked at this, it seemed like it was a lack of proper error handling that was causing the issue. I was hoping they would just fix it, but oh well. Moved to aggressive list in the next update
