### ISSUE TITLE
I need to block only ads , but allow trackers 

### ISSUE THREAD

**Issue by keerthirajap** [lightswitch05/hosts#325]
Hi Team,

Is there any host list available to block only ads but allow tracker.

**Comment by dnmTX** [comment]
Dan see:
https://github.com/StevenBlack/hosts/issues/1819
**and**
https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/issues/632

**Comment by lightswitch05** [comment]
No, sorry, I'm not aware of any.
