### ISSUE TITLE
Add incoming-telemetry.thunderbird.net

### ISSUE THREAD

**Issue by thomasmerz** [lightswitch05/hosts#327]
**New domain to block**

Because I found so many queries in my AdBlocker (Pi-Hole) from my family members which doesn't care to disable telemetry in their Thunderbird instance, please add `incoming-telemetry.thunderbird.net` for **Thunderbird** which is still missing.  
`incoming.telemetry.mozilla.org` for **Firefox** is already included, so it should also include other telemetry domains from Mozilla.

<img width="988" alt="image" src="https://user-images.githubusercontent.com/18568381/146400059-a70b972e-7e8e-4383-87d3-23b8ff0821d1.png">

I'll prepare a PR, so you just will have to review and merge. Kind regards!

**Comment by lightswitch05** [comment]
Thanks for your PR @thomasmerz - unfortunately I'm going to have to decline it. I have an entire management system built for my lists where it is all in a database and subdomains are discovered and added automatically. It also does DNS lookups for all domains regularly and removes and dead entries. This repo is essentially just the output of that system - so adding something to the list would just get overwritten in the next release.

I have however, added the domain you requested to the system and it will be included in the next release later today. Thank you again for your contribution.

**Comment by thomasmerz** [comment]
Hi @lightswitch05 , sorry for asking again, but I can't still find `incoming-telemetry.thunderbird.net` in any of your lists…!? 🤔

**Comment by lightswitch05** [comment]
@thomasmerz It looks like it was added to the primary list on Dec. 16 https://blocklist-tools.developerdan.com/entries/search?q=incoming-telemetry.thunderbird.net

**Comment by thomasmerz** [comment]
@lightswitch05 Ok, I understand and thank a lot 😃 
But I expected this in any list(s) in this repo, too!? Or am I wrong?
https://github.com/lightswitch05/hosts/search?q=incoming-telemetry.thunderbird.net&type=code
> We couldn’t find any code matching 'incoming-telemetry.thunderbird.net' in lightswitch05/hosts

**Comment by lightswitch05** [comment]
It's in there- I don't think their search includes my large block list.

**Comment by lightswitch05** [comment]
From my pihole search:

![image](https://user-images.githubusercontent.com/598803/151194338-51c57cba-1494-473e-bbef-9edb9025a11b.jpeg)
