### ISSUE TITLE
Missing icons on your homepage

### ISSUE THREAD

**Issue by Ubimo** [lightswitch05/hosts#336]
Hi
Is this only on my side, or are there missing icons on your [homepage](https://www.github.developerdan.com/hosts/)?
See [screenshot](https://imgur.com/a/tTPoaK8).

**Comment by lightswitch05** [comment]
Haha no sorry, that's the actual image. The idea is that once everything is blocked using my lists, that's what some websites will look like.

I'm not a graphic designer and it's the best I could come up with for a logo for this project.

**Comment by lightswitch05** [comment]
See: https://github.com/lightswitch05/hosts/blob/master/docs/logo.png

**Comment by Ubimo** [comment]
Oh, ok, I thought my paranoid ass blocked too much, again. :-D
