### ISSUE TITLE
d.admp.io & st-a.props.id need to blocked

### ISSUE THREAD

**Issue by kyrios21** [lightswitch05/hosts#34]
Main domain **admp.io** is blocked at `https://github.com/r-a-y/mobile-hosts/blob/master/AdguardDNS.txt`
but sub-domain **d.admp.io** still passed.
Main domain **props.id** is blocked at yoyo.org but sub-domain **st-a.props.id** still passed.

Check both from `tribunnews.com`

**Comment by lightswitch05** [comment]
Added 👍
