### ISSUE TITLE
False Positive: supervisor.ext-twitch.tv

### ISSUE THREAD

**Issue by jaku** [lightswitch05/hosts#343]
The sub-domain supervisor.ext-twitch.tv is used by extensions created for use on twitch.tv. Every extension that 3rd party developers create are hosted on this domain and is used to load the extension.

While some extensions may end up doing geo-tracking as a "feature" that's on those individual extensions and send that data to their own domains. Perhaps that is enough to block the domain fully by your standards.

**Comment by lightswitch05** [comment]
It will be removed 👍
