### ISSUE TITLE
False positive:  js.media-lab.ai  (imgur.io / imgur.com)

### ISSUE THREAD

**Issue by Sduibek** [lightswitch05/hosts#346]
js.media-lab.ai is blocked by Lightswitch05 - Ads & Tracking within NextDNS lists.

Blocking of this domain breaks all functionality of imgur.com (imgur.io) mobile site on Android using Firefox. 

I've used many lists and Lightswitch05 is the only one that blocks js.media-lab.ai causing the breakage of imgur.

If you're having trouble reproducing the issue, try again in private or incognito mode and also try https://imgur.com/upload rather than the main site. 

Screenshots:
https://imgur.com/a/rmIBvLw

https://imgur.com/a/GxYJiG4

**Comment by lightswitch05** [comment]
Its only in the aggressive list... or you have an old version https://github.com/lightswitch05/hosts/issues/321
