### ISSUE TITLE
False positive: instantcheckmate.com

### ISSUE THREAD

**Issue by Sduibek** [lightswitch05/hosts#349]
Blocked by Lightswitch05 - Ads & Tracking within NextDNS lists.

Data brokers and people-search sites are a gross and deeply concerning industry, but if we want to get our info removed from these sites/databases (and everyone should!), it's necessary to visit the site to do so - and we can't if a filter is blocking the entire site categorically.

**Comment by lightswitch05** [comment]
My stance on these one-off actions is the disable/allowlist on your side, do what you need to do, then re enable it
