### ISSUE TITLE
geniuslinkcdn.com

### ISSUE THREAD

**Issue by ler762** [lightswitch05/hosts#350]
What's your opinion on affiliate links?

Aside from the sketchy nature of affiliate marketing they seem to me to also do tracking, so I like blocking them.

source   https://thehometheaterdiy.com/hdmi-with-ethernet/

which calls  geniuslinkcdn.com/snippet.min.js
which (i think) calls target.georiot.com/

I'd say block  .geniuslinkcdn.com/ and .georiot.com/

**Comment by lightswitch05** [comment]
`*.georiot.com` is already in the list.... I don't normally add affiliate domains unless it does active tracking. I figure if you click the link, then you want it to work. This one is a bit different where it loads immediately regardless of clicking. I'm ok with adding it on at least a trial basis and if people complain then move it to the aggressive list.

**Comment by lightswitch05** [comment]
in the next release
