### ISSUE TITLE
False positive: whisk.com

### ISSUE THREAD

**Issue by Lugiac** [lightswitch05/hosts#351]
**False positive**

It's a recipe manager and planner blocked by "Ads & Tracking" list.
There are roughly 70 subdomains of whisk blocked in the list too, but I am not sure if/which of them are trackers or ads.

**Comment by lightswitch05** [comment]
This has been in the list since 2019 and you are the first one to comment on it. Clearly a false positive. Thanks for the report! It will be removed in the next release.
