### ISSUE TITLE
False positive again: js.media-lab.ai (imgur.io / imgur.com)

### ISSUE THREAD

**Issue by crsag** [lightswitch05/hosts#358]
![Screenshot_20220625-163918](https://user-images.githubusercontent.com/16190789/175771035-cc832953-0d5f-4bd7-8e65-854051ff609c.png)
 
js.media-lab.ai is blocked by Lightswitch05 - Ads & Tracking within NextDNS lists.

#346

**Comment by lightswitch05** [comment]
According to this, it's only in the aggressive list: https://blocklist-tools.developerdan.com/entries/search?q=js.media-lab.ai

**Comment by lyrad87** [comment]
Just noticed this myself,
<img width="263" alt="Screenshot 2022-07-04 at 13 28 30" src="https://user-images.githubusercontent.com/7974733/177145940-600ca8bb-8ab6-44cb-b9b6-c55512cac26a.png">

I have definitely only enabled "Lightswitch05 - Ads & Tracking" in NextDNS and not the aggressive list. I trust your tool above but just in case I double-checked the [list](https://github.com/nextdns/metadata/blob/master/privacy/blocklists/lightswitch05-ads-tracking.json) and the domain `js.media-lab.ai` is, just as you mentioned, not included. However, imgur does not work correctly unless the domain is added to the Allowlist. Not a big deal but it is weird why NextDNS shows the domain being blocked by your list when the domain is not even included. I figure it's not an issue on your side but maybe you have an idea of what is not working as intended. I can raise an issue in their GitHub but they are not responding all the time.

**Comment by muzikherif** [comment]
I have the same issue, imgur broken at mobile.Only works if add to domain allowlist.

**Comment by lightswitch05** [comment]
@dnmTX thanks for helping solve this one

**Comment by yokoffing** [comment]
It is still showing up for me on the regular list on NextDNS.

**Comment by lyrad87** [comment]
Yea, this issue itself was never solved, the issue was just closed due to dnmTX's comment above which may explain why it's not working (aggressive wildcard blocking) but the solution would be to either a) add the domain to the Allowlist or preferably b) have it removed from the list itself.

**Comment by lightswitch05** [comment]
https://github.com/lightswitch05/hosts/issues/356
