### ISSUE TITLE
viva.co.id is heavily injected with ads and tracking

### ISSUE THREAD

**Issue by kyrios21** [lightswitch05/hosts#36]
gu.dyntrk.com
sync.adotmob.com
sync.tidaltv.com
sync.ipredictive.com
logger-01.vty.dailymotion.com
tofu-ssl.dmcdn.net

Please check one of their news, like :
`https://www.viva.co.id/sport/raket/1088173-ratu-ganda-putri-bulutangkis-dunia-dipermalukan-duo-korea`

**Comment by lightswitch05** [comment]
Added 👍
