### ISSUE TITLE
Lemonade.com blocked

### ISSUE THREAD

**Issue by sloccy** [lightswitch05/hosts#360]
**False positive?**

Hello, I haven't really reported a false positive before but figured I should try to help out. The domain www.lemonade.com is a legitimate insurance company. Not sure why it would be blocked other than it has the word "ad" in it.
![lemonade](https://user-images.githubusercontent.com/90802823/179303780-3a387b15-d6cd-4da4-a071-d062615f32ab.PNG)

**Comment by lightswitch05** [comment]
It looks like your list version is very out of date:

https://blocklist-tools.developerdan.com/entries/search?q=lemonade.com

**Comment by dnmTX** [comment]
Dan @lightswitch05 the one with `www.` in the front is still present 💡 
![extended txt](https://user-images.githubusercontent.com/34774426/179338898-ad7a95a3-bccb-4c82-bf91-a5b954391d5c.png)

**Comment by lightswitch05** [comment]
Great catch! I'll get it removed

**Comment by lightswitch05** [comment]
Fixed
