### ISSUE TITLE
Google Analytics console is being blocked. 

### ISSUE THREAD

**Issue by p-patra** [lightswitch05/hosts#361]
https://analytics.google.com is only used to access the Console site. Can be unblocked I guess if it's not doing any tracking?

**Comment by yokoffing** [comment]
Or, you could just allowlist it.

**Comment by lightswitch05** [comment]
No way. Also, see https://github.com/lightswitch05/hosts/issues/356

**Comment by yokoffing** [comment]
> No way.

I was talking to OP. Of course we should allow Google Analytics lmao.

**Comment by lightswitch05** [comment]
I, too, was talking to OP 😜
