### ISSUE TITLE
IEEE Spectrum incorrectly blocked in Lightswitch

### ISSUE THREAD

**Issue by JohnChristianD** [lightswitch05/hosts#362]
Lightswitch (the normal one) is incorrectly blocking spectrum.ieee.org. Using the version on NextDNS.

**Comment by dnmTX** [comment]
@JohnChristianD the mentioned domain is not in the normal list here,neither any of it's CNAME's as NextDNS is usually famous for blocking them.

**Comment by JohnChristianD** [comment]
It says in my logs that it's blocking it. I searched and it's supposedly the CNAME spectrum.ieee.org.cdn.rebelmouse.com that's being blocked.

**Comment by lightswitch05** [comment]
I'm not blocking that. Allowlist it on your side if it's causing issues.

**Comment by JohnChristianD** [comment]
I guess the issue here is NextDNS blocks the subdomains of a root domain and Lightswitch isn't meant to be used like that?
