### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by holequantum** [lightswitch05/hosts#365]
Page.gitlab.com
It is a website hosting service from opensource git system called gitlab just like non opensource github pages. Github.io.
So please remove this. 
Thanks

**Comment by lightswitch05** [comment]
`page.gitlab.com` is not in my list, so it cannot be removed.

The CNAME `ab13.mktossl.com` is only in my aggressive list, which I do not recommend anyone to use.

**Comment by holequantum** [comment]
gitlab.mktoweb.com | Blocked by Lightswitch05 - Ads & Tracking

But it is for gitlab pages not something wrong you can safely remove it.

**Comment by lightswitch05** [comment]
It is not blocked in my list, so nothing to remove.

**Comment by dnmTX** [comment]
Dan @lightswitch05 this is just another case of the insane blocking aggressivness of NextDNS.
`mktoweb.com` is listed and for refference also see https://github.com/lightswitch05/hosts/issues/358#issuecomment-1189371940
👍
