### ISSUE TITLE
False positive: cyberthreatcoalition.org

### ISSUE THREAD

**Issue by vinothvkr** [lightswitch05/hosts#368]
Hi,

0.0.0.0 cyberthreatcoalition.org
0.0.0.0 blocklist.cyberthreatcoalition.org
0.0.0.0 www.cyberthreatcoalition.org

listed domains are blocked in ads-and-tracking-extended.

It provides malware block lists

Thank you.

**Comment by hagezi** [comment]
Hi,

the domain is not claimed. The CyberThreatCoalition service is down for a long time.

> This domain has been mapped to Squarespace, but it has not yet been claimed by a website. If this is your domain, claim it in the Domains tab of your Website Manager.

Regards,
Gerd - https://github.com/hagezi/dns-blocklists

**Comment by vinothvkr** [comment]
Noted. Thanks for your info. Closing the thread.
