### ISSUE TITLE
nbc-2.com - images don't show up and site layout messed up

### ISSUE THREAD

**Issue by AmperAndSand** [lightswitch05/hosts#39]
`http://www.nbc-2.com/story/39429662/man-arrested-for-threatening-to-shoot-up-pennsylvania-polling-place`

The site layout is jumbled up and images don't show up due to the following host names being blocked (present in both ads-and-tracking.txt and ads-and-tracking-extended.txt):
- franklyinc.com
- ngw-static.franklyinc.com

Screenshot:
![screenshot](https://user-images.githubusercontent.com/1404745/48110755-d57d7a00-e288-11e8-9a2c-2cf332ea30d4.png)

**Comment by lightswitch05** [comment]
This is unfortunate. The script has nothing to do with the content. They have lazy loading - but no error handling. When they get a JavaScript error from a blocked tracker - it breaks everything else on the page that requires JavaScript (the lazy loader)

```
        <script src="https://ngw-static.franklyinc.com/assets/8685/app-c0b1f53218264d15306e.js"></script>
        <!-- NOTE: if AppNexus Prebid is enabled, add its script.-->
        
        <script src="https://content.worldnow.com/global/js/_pub/off-platform.ads.min.js?ver=0"></script>
        <script>
          Worldnow.Beacon.set(
            _.mergeWith(franklyDataLayer[0], Worldnow.Beacon.get(), function customizer(dataLayerValue, beaconValue) {
              if (!beaconValue || beaconValue === 'null' || beaconValue === 'undefined' || beaconValue === 'n/a' || beaconValue === 'error not found!') {
                return dataLayerValue;
              }
            })
          );
        </script>
```

`Worldnow.Beacon.set` is the breaking JavaScript - since it is being blocked

**Comment by lightswitch05** [comment]
It does look like it handles some of the CSS and the weather widget too

**Comment by lightswitch05** [comment]
@AmperAndSand removed, thanks for the report
