### ISSUE TITLE
Addition for "Dating Service" List

### ISSUE THREAD

**Issue by 3mg4** [lightswitch05/hosts#395]
> **New domains to block?**
> 
> **I generally do not want these types of requests.** It takes a lot of extra time for me to verify. However, if you think you've found something that is missing: prove it. Give me links with detailed instructions on how to reproduce it. If I cannot reproduce it, then it will not be added.
> -->

A bit confused now, since **your "ReadMe" file states we can post a ticket if we found some missing Services.**
Anyway.

List "Dating Services"
Service to block: [www.lovoo.com](https://www.lovoo.com)
Its a European/German Dating App/Service like Tinder.

How to reproduce:
1. activate "Dating Service" List in pihole or similar
2. Browse to [www.lovoo.com](https://www.lovoo.com)

Thanks, 
Gabriel

**Comment by lightswitch05** [comment]
Thanks! It will be in the next update. Most requests to add things is for the ads and tracking list, those get tricky. Dating list is a lot easier.
