### ISSUE TITLE
cdn.ravenjs.com should be moved to aggresive list

### ISSUE THREAD

**Issue by kyrios21** [lightswitch05/hosts#40]
`seller.shopee.co.id`

**Comment by lightswitch05** [comment]
@kyrios21 this isn’t happening.

What is that url for? Could you provide a few more details?

**Comment by kyrios21** [comment]
Ensure `raven.min.js` is not loaded from memory cache, then you'll see the error (just hour glass with S symbol).
![snap5](https://user-images.githubusercontent.com/30654475/48130111-2065b480-e2be-11e8-9d18-a85a0cf278fd.jpg)

**Comment by AmperAndSand** [comment]
Would like to add here that an issue also occurs with cdn.ravenjs.com on 
`https://www.fanatical.com/`

In the attached screenshot the encircled part of the image doesn't appear if cdn.ravenjs.com is blocked:
![screenshot](https://user-images.githubusercontent.com/1404745/48660290-785ca200-ea9a-11e8-8660-0ff565ca7a71.png)

**Comment by lightswitch05** [comment]
To anyone following this ticket. RavenJS does not host content or necessary JavaScript. If a website breaks because of this block, it is because they have no error handling logic to handle the blocked domain- not that it is needed. The best course of action is to let the various websites know that their website breaks if con.ravenjs.com fails to load.

**Comment by kyrios21** [comment]
I use my own whitelist (and blacklist) before applying the hosts.
I applied on my router.
`curl -o /jffs/hosts http://sbc.io/hosts/alternates/gambling/hosts <<= choose your preferred hosts provider
sleep 5  <<= optional
fgrep -vf /jffs/wl.txt /jffs/hosts > /jffs/hosts.txt <<= remove address which is in my _WL list_ from hosts
sleep 2 <<= optional
cat /jffs/bl.txt >> /jffs/hosts.txt <<= Append my own _BL list_ into hosts
sleep 2 <<= optional
service dnsmasq restart`
So I use _hosts.txt_ instead of _hosts_

**Comment by dnmTX** [comment]
@kyrios21  i'm just curious what you think.This is what i use for my whitelist(it's a small list so far so i'm not sure about the performance hit if it gets bigger):
`for i in `cat whitelist`; do sed -i "/ $i/d" hosts; done`
So which one you'd think will be faster/more efficient?
