### ISSUE TITLE
Request to unblock newrelic.com

### ISSUE THREAD

**Issue by vesterli** [lightswitch05/hosts#400]
I don't believe newrelic.com should be blocked. This is a SaaS telemetry product, not something that serves ads.

**Comment by iam-py-test** [comment]
>  Hostfile blocklist for ads and tracking

Telemetry falls under that category. Also: https://github.com/lightswitch05/hosts/issues/356

**Comment by hagezi** [comment]
https://slayterdev.github.io/tracker-radar-wiki/domains/newrelic.com.html
https://whotracks.me/trackers/new_relic.html
