### ISSUE TITLE
IMDB Android App is showing Amazon Ads

### ISSUE THREAD

**Issue by maulikr** [lightswitch05/hosts#403]
**New domains to block?**

Hi Dan,
I understand you do not take the requests, however I tried to block few domains on my own from query list but the apps kept popping up.
I am posting screenshots showing I am using your adlist (image not visible) but the IMDB android apps shows up Amazon ads.

For reference I am on Android 13 on Pixel 7 Pro.

![messages_0](https://github.com/lightswitch05/hosts/assets/25378380/90392f7e-98af-4546-ac55-af13f192e6ef)
![messages_1](https://github.com/lightswitch05/hosts/assets/25378380/e9aaa3b5-acc1-464e-ac64-001eb8d2100f)

**Comment by lightswitch05** [comment]
I believe these ads are impossible to block without breaking the app, sorry
