### ISSUE TITLE
False Positive: ifthenpay

### ISSUE THREAD

**Issue by luis-oliveira92** [lightswitch05/hosts#407]
Hi, the following domains related to ifthenpay are being blocked right now:

  ifthenpay.com
  api.ifthenpay.com
  backoffice.ifthenpay.com
  carrinhovirtual.ifthenpay.com
  gateway.ifthenpay.com
  helpdesk.ifthenpay.com
  ifshop.ifthenpay.com
  mbway.ifthenpay.com
  sip.ifthenpay.com
  www.ifthenpay.com

Ifthenpay is one of the oldest and most trusted Portuguese payment processors, blocking those domains breaks internet payments.

https://www.bportugal.pt/entidadeautorizada/ifthenpay-lda

**Comment by lightswitch05** [comment]
This has been removed
