### ISSUE TITLE
False Positive newrelic.com

### ISSUE THREAD

**Issue by greenlighttec** [lightswitch05/hosts#408]
https://www.newrelic.com is a valid domain of a monitoring platform such as logic monitor and site24x7, datadog etc. It's listed explicitly as blocked.

Exact match for newrelic.com found in:
 - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

**Comment by lightswitch05** [comment]
I like newrelic but I think it falls into tracking group
