### ISSUE TITLE
False positive SPARTOO

### ISSUE THREAD

**Issue by gissimo** [lightswitch05/hosts#410]
**False positive?**

Hi,
spartoo.* are e-commerce sites and I don't see no reason for them to be blocked.
Thanks!

<img width="1223" alt="image" src="https://github.com/lightswitch05/hosts/assets/22690890/aa084b6b-d0cb-47a0-8301-677f120cf513">

https://spartoo.com

**Comment by lightswitch05** [comment]
Sorry! Removed in next update
