### ISSUE TITLE
Remove niggermania.co

### ISSUE THREAD

**Issue by Sonic5435325** [lightswitch05/hosts#412]
This domain seems to be retired at the moment.

"This Domain is NOT Suspended Anymore"

"This domain has all already been restored and not Suspended anymore. If you are the registrant of the domain please update your nameservers so it resolves to your site."

**Comment by lightswitch05** [comment]
I don't know how I came across this domain, its in the 'hate and junk' list. seems like a good place for it. Please just don't use the list if you don't like it.
