### ISSUE TITLE
s.pinimg.com

### ISSUE THREAD

**Issue by p1r473** [lightswitch05/hosts#413]
Hey Dan,
s.pinimg.com hosts the static images for Pinterest
pinterest.ca shows as a completely blank white page with this blocked
Its in the aggresive list - Im not sure if youve identified any tracking it does.

**Comment by lightswitch05** [comment]
`s.pinimg.com` is regularly used for pixel tracking and javascript tracking - but its also in the aggressive list - so just don't use that list
