### ISSUE TITLE
[FP] gethatch.com

### ISSUE THREAD

**Issue by smed79** [lightswitch05/hosts#418]
Hi, 

seems for me that  `gethatch.com` is incorrectly blocked.

blocked > https://i.imgur.com/n6sogxn.png

unblocked > https://i.imgur.com/L8rW6f8.png

to reproduce, got to 

- `https://www.samsung.com/fr/memory-storage/nvme-ssd/ssd-980-pro-nvme-m-2-pcie-4-0-1tb-mz-v8p1t0bw/`

click the button `OÙ ACHETER` or `WHERE BUY` (_depending on the language of your browser_).

Thank you.

**Comment by ler762** [comment]
On 9/30/23, smed79 wrote:
> Hi,
>
> seems for me that  `gethatch.com` is incorrectly blocked.

Do you think affiliate marketing links should be blocked?

I hate affiliate marketing, so I'd say it's correctly being blocked

> to reproduce, got to
>
> -
> `https://www.samsung.com/fr/memory-storage/nvme-ssd/ssd-980-pro-nvme-m-2-pcie-4-0-1tb-mz-v8p1t0bw/`
>
> click the button `OÙ ACHETER` or `WHERE BUY` (_depending on the language of
> your browser_).

I clicked on one of those links and got this from uMatrix:

uMatrix has prevented the following page from loading:

https://gethatch.com/wtbonline/merch/62192/go?utm_source=hatch&utm_campaign=Samsung+Global&utm_content=65xxxx&region=FR&affiliate_id=52611&prod_id=983270561&core_id=100512603

    without parameters = https://gethatch.com/wtbonline/merch/62192/go
    utm_source = hatch
    utm_campaign = Samsung+Global
    utm_content = 65xxxx
    region = FR
    affiliate_id = 52611
    prod_id = 983270561
    core_id = 100512603
