### ISSUE TITLE
Unable to load comments on ft.com (financial times) on qutebrowser

### ISSUE THREAD

**Issue by n35xdxb0** [lightswitch05/hosts#43]
In order to be able to view comments on ft.com when using qutebrowser (and, I presume, other browsers that use the same blocklist), these two lines need to be whitelisted

data.livefyre.com
cdn.livefyre.com

I haven't encountered the issue on other websites and it's fairly cumbersome to reproduce since you need a paid account to view comments on ft.com. But for anyone that does have an account, I hope this helps.

**Comment by lightswitch05** [comment]
@n35xdxb0 since you have a paid accout it would be great if you could contact their support and let them know. Maybe they will be able to fix it on their website

**Comment by n35xdxb0** [comment]
@lightswitch05 
![imgur-2018_11_12-14 43 10](https://user-images.githubusercontent.com/33785509/48351251-fcbdb800-e689-11e8-90c4-e7441a08018a.png)

**Comment by lightswitch05** [comment]
@n35xdxb0 thank you for the update. I moved it to the aggressive list 👍
