### ISSUE TITLE
Re-evaluate adviserplus.com?

### ISSUE THREAD

**Issue by StevenBlack** [lightswitch05/hosts#48]
Hi Daniel @lightswitch05,

I received the following today.  Can you advise?

> Hi Stephen,
> 
> I'm from the company AdviserPlus.com (IT manager at a HR professional services company). Recently checking our own brand name flagged us on a hosts list (https://github.com/StevenBlack/hosts) where the source seems to be from the lightswitch05 (ad and tracking domains). However the domain listed (adviserplus.com and several subdomains) should not be performing any particular ads or tracking, some of the domains listed are even internal only! So I was wondering how we could go about removing the adviserplus.com domains from the list, or if there is a legitimate issue with ads or tracking with the sites let me know.
> 
> I'm contacting you since you unify data from these sources, unfortunately the user lightswitch05 doesn't seem to have any contact info.
> 
> Thanks in advance for any assistance you can provide.

**Comment by lightswitch05** [comment]
Hey Steven, thanks for forwarding this along. I'm sorry they were able to get in contact with me direct. I removed the domain and subdomains in commit https://github.com/lightswitch05/hosts/commit/7a8e0ea105cd9a35d8fabbefdaa4b8115d39ceb4 - sorry about the false positive.

**Comment by StevenBlack** [comment]
Thanks Daniel!
