### ISSUE TITLE
if you want some more roku's

### ISSUE THREAD

**Issue by jawz101** [lightswitch05/hosts#50]
I did a subdomain lookup on Roku and found several more based what looks like different parts of the world https://github.com/jawz101/MobileAdTrackers/blob/master/roku_test

**Comment by jawz101** [comment]
... caveat.  I recently stopped using this list because, from reports on reddit, blocking *.logs.roku.com might prevent the roku from receiving updates.

https://www.reddit.com/r/pihole/comments/5jqqdw/roku_getting_piholed_multiple_times_a_minute_when/

**Comment by lightswitch05** [comment]
This is interesting, why did you close the issue?

**Comment by jawz101** [comment]
Oh I didn't want to bug you.  I'll keep it open if you want me to

**Comment by lightswitch05** [comment]
Thanks for the info @jawz101 I added them in commit https://github.com/lightswitch05/hosts/commit/52e6b88f16d1053f71fcbbea1cb86c5d3d82849f
