### ISSUE TITLE
re-evaluate yottaa.com?

### ISSUE THREAD

**Issue by StevenBlack** [lightswitch05/hosts#51]
Hi Daniel @lightswitch05,

Just got this from yottaa:

> Hello,
> 
> We run an ecommerce acceleration platform (https://www.yottaa.com <https://www.yottaa.com/>)… as part of this we cache assets on our various CDN domains and use other domains for configuration, etc.  It looks like you have a ton of Yottaa stuff in your list to be blocked
> 
> Over the weekend we had a customer of ours get the CSS blocked by your ad blocker due to this...
> 
> Can you whitelists our *.yottaa.net <http://yottaa.net/>  and *.yottaa.com <http://yottaa.com/> domains or remove them from your lists as part of your software distribution?
> 
> Happy to discuss.

Any insight?

**Comment by lightswitch05** [comment]
Thanks for the info Steven. I see that this was completely breaking carters.com - I'm surprise my hadn't brought this to my attention yet. Its fixed now, I removed all entries except for `qoe-1.yottaa.net` - which appears to be a tracking only
