### ISSUE TITLE
Subsites of clickbank.net getting through somehow

### ISSUE THREAD

**Issue by Zydico25** [lightswitch05/hosts#52]
Sites such as hop.clickbank.net are getting through the blocklists on Pihole even though clickbank.net itself is blocked.  See the below URL for example iframe advertisements on the right hand side.  If clicked, they redirect when they should not be able to.

https://www.shtfpreparedness.com/new-prepping-start/

**Comment by dnmTX** [comment]
@Zydico25  as far as i see @lightswitch05  doesn't have any `*.clickbank.net` sub/domains in any of his lists.
I'm little bit confused here.Is your post a proposal to block all those domains or like....criticism that not enough are listed and more needs to be added cause some of them are going trough or......?

**Comment by lightswitch05** [comment]
@Zydico25 I'm willing to consider adding clickbank.net and its subdomains to my list if you can tell me more about it. What website did you discover it on? Is it ads or tracking?

**Comment by dnmTX** [comment]
@lightswitch05  he posted example in his post(bottom).Everything on the right side of that link is hosted by  `*.clickbank.net` and it looks shady as hell.

**Comment by lightswitch05** [comment]
@Zydico25 I've added a bunch of hosts from the website you gave above. While hosts files do not actually support wildcard, I extend lists as well as I can. I added a bunch of `hop.clickbank.net` subdomains and they should continue to expand

**Comment by Zydico25** [comment]
Sorry for the late reply.  We're ending Q4 at the office so my plate has been full this week.  

@dnmTX I didn't intended for my post to be criticism.  I thought the node list hosted here had entries for clickbank.net already which is why I posted here about site calls getting past the blocks.  It's my mistake for not realizing this node and subsites were not already included.  I guess, in a sense, it was a request to add them since I didn't realize they weren't already there.  Btw, your comment about the iframes on the right of the website being "shady as hell" describes them perfectly.  

@lightswitch05 Thank you for reviewing the site and adding the subdomains you did.  I hope to contribute more in the future.

**Comment by dnmTX** [comment]
@Zydico25  all good and btw,i meant it "criticism" in a good way 👍
