### ISSUE TITLE
Consider removing tags.tiqcdn.com

### ISSUE THREAD

**Issue by ErichRitz** [lightswitch05/hosts#53]
I use the Steven Black hosts file.  After using the hosts file, I noticed that selecting deals for the "BankAmeriDeals Cash Back Deals" no longer worked (https://promo.bankofamerica.com/deals/) when trying to enable deals on my credit card.  I determined that the domain tags.tiqcdn.com was responsible, and after adding that domain to my whitelist, the deals page started working again.

The "MVPS hosts file" imported by Steven Black also references tags.tiqcdn.com, but it is commented out with the comment "affects Intel.com/Shaw".

As I mentioned, for now I simply have tags.tiqcdn.com in my whitelist, but this issue would affect other Bank of America customers who utilize the BankAmeriDeals feature on their credit card and use this hosts file.

* Specifically, the Firefox Console reports the following two messages:
Loading failed for the <script> with source “https://tags.tiqcdn.com/utag/bofa/main/prod/utag.sync.js”.
Loading failed for the <script> with source “https://tags.tiqcdn.com/utag/bofa/main/prod/utag.js”.

**Comment by lightswitch05** [comment]
Thanks for the info @ErichRitz. This is a tricky one, since its blocking legitimate ads (and likely tracking) - but in this case you want want the ads. I'll leave the ticket open for a few days while I consider it, but I do believe this host is used in a lot more areas where blocking would be preferred.

**Comment by ErichRitz** [comment]
Sounds good.  If the host is mainly bad I agree leaving it blocked is probably better.  Hopefully people with the same issue can find this thread.

I have an idea, but it might take a few days before I can test it out.  I have a home server for personal use, and am wondering if I host those two files (utag.sync.js and utag.js) myself and point tags.tiqcdn.com to my own server, if the website will still work.  That way tags.tiqcdn.com will still be blocked for everything else.

**Comment by lightswitch05** [comment]
@ErichRitz the links you gave are https. Unless you also generate a self-signed wildcard cert and except it on your devices, then trying to redirect the scripts will not work. Its possible - but a lot of work

**Comment by lightswitch05** [comment]
From sling.com:

`https://tags.tiqcdn.com/utag/dish/sling/prod/utag.js`

**Comment by lightswitch05** [comment]
Also on ups.com

`https://tags.tiqcdn.com/utag/ups/maestro/prod/utag.js`

**Comment by lightswitch05** [comment]
Also on creditkarma: `https://tags.tiqcdn.com/utag/creditkarma/main/prod/utag.js`

For now I've decided this should remain blocked. Its on a lot of different websites and for the most part blocking does not break anything. Thanks for your input @ErichRitz don't hesitate to open another ticket of any other issues you may have

**Comment by dnmTX** [comment]
@lightswitch05  just confirming the issue as i'm in Bank of America as well and as @ErichRitz  already mentioned it's not possible to go to the rewards page(it doesn't load).Personally it doesn't bother me cause i'm barely using that feature but others,i'm guessing might not be very happy.Anyways,up to you,if i feel the need i'll whitelisted on my end.

P.S. Almost forgot.....**MARY CHRISTMAS AND HAPPY NEW YEAR AND KEEP UP THE GOOD WORK MAN.YOU ARE VALUABLE HERE !!!!**  👍

**Comment by ErichRitz** [comment]
@dnmTX for me the Rewards page loaded, but clicking on a deal had no response. So if I want to click on a deal I temporarily whitelist the site. At all other times I leave the site blacklisted.
