### ISSUE TITLE
[difference] ads-and-tracking(extended)

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#59]
@lightswitch05  sorry to see you pulling out from the @StevenBlack's lists.Your lists is very relevant to me and i'm not dropping it from my end for sure and i hope that you'll continue maintain it.
Need to know the difference between the two lists so i can decide which one to use.I'm kind of leaning on the non extended one as it is smaller and by the look of it will provide similar protection but would like to hear your opinion of course.

**Comment by lightswitch05** [comment]
Hey @dnmTX, the extended one is the one that was in Steven's project, so if you keep using it is should be the same

**Comment by dnmTX** [comment]
@lightswitch05 i know that,but now that it isn't anymore i have a choice to make and was hoping on some input from you.

**Comment by lightswitch05** [comment]
I recommend the extended version if you do not have any issues with large hosts files. If you have issues with large hosts files, like on windows, you might be better off using the base list

**Comment by lightswitch05** [comment]
Also, if you are using these lists with uBlock origin, the base list would be fine there as well. Since uBlock origin automatically blocks any subdomain of a blocked root - then it really has no need of the extended list

**Comment by dnmTX** [comment]
It's all in my router. Using dnsmasq as it is proven very reliable.I guess i'll load the regular one and will go from there.Thanks for the input,and keep on fighting the good fight 👍 
Closing.....

**Comment by DPTJKKVH** [comment]
Sorry to see you go as well. I wholeheartedly disagree with Steve on sentry.io. I personally witnessed how he was swayed by Sentry on the pure basis of them reaching out to them and saying "pretty please!". His project is great but he is way too quick with removing entries and easily sweet talked.

I hope I can continue to use your list in the future.

**Comment by DPTJKKVH** [comment]
Thanks. I was afraid I had to import your list manually. With the update.json it's a piece of cake. :)

**Comment by DPTJKKVH** [comment]
@lightswitch05 I see no donation information neither on your profile nor your home page. There is a button for EFF donations however. Would you like if I donate some money to them in your honor instead?

**Comment by lightswitch05** [comment]
Yes, if you wish to donate, I support both EFF and PiHole projects. EFF is tax deductible, PiHole is not
