### ISSUE TITLE
invalid domains

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#62]
@lightswitch05  you have some [INVALID](https://github.com/Ultimate-Hosts-Blacklist/lightswitch05_hosts_ads-and-tracking-extended/blob/master/output/hosts/INVALID/hosts) once present.Mine as well remove them.
Close this when done.Thanks.

**Comment by lightswitch05** [comment]
@dnmTX hello. The `wpad` domains were added in response to this blog post https://pi-hole.net/2018/09/10/mitigate-a-new-cert-vulnerability-598349-with-an-entry-in-etc-hosts/

So unless someone complains that they are causing them issues, I intend to leave them. Any information why `-x3.vindicosuite.com` is being flagged?

**Comment by dnmTX** [comment]
> The wpad domains were added in response to this blog post https://pi-hole.net/2018/09/10/mitigate-a-new-cert-vulnerability-598349-with-an-entry-in-etc-hosts/

Good job.Glad to know that you're on top of things 👍 

> Any information why -x3.vindicosuite.com is being flagged?

@funilrys is the one who can answer that but if i have to guess it's probably the dash `-` in the front and if you do just basic nslookup you got this:

`C:\Windows\system32>nslookup -x3.vindicosuite.com
*** Invalid option: x3.vindicosuite.com
Default Server:  DD-WRT
Address:  192.168.1.1`
Therefore if dnsmasq can't read it i don't think that domain can do any harm on my end.

**Comment by lightswitch05** [comment]
In your command, `nslookup` is reading the `-` as an option instead of part of the domain. `dig "-x3.vindicosuite.com"` runs fine - although it doesn't get an answer. Its not an active domain, but as far as I can tell it is valid

**Comment by dnmTX** [comment]
Also ` com.tenjin.ios.api` was rendered invalid previously,not sure why it was skipped on that last filtering.
Just FYI.

**Comment by funilrys** [comment]
@lightswitch05 @dnmTX 
I asked the co-author of Bind9 long time ago how can I check those ([cf](https://twitter.com/nuthaven/status/1018555763029991429))  after I got some headache...

I get the following ....
```
$ dig -q -x3.vindicosuite.com
dig: '-x3.vindicosuite.com' is not a legal IDNA2008 name (string start/ends with forbidden hyphen), use +noidnin
```

**Comment by lightswitch05** [comment]
I guess my version was including the quotes in the lookup. I’ll update my validation regex to exclude domains starting with a `-`. Thanks @funilrys

**Comment by lightswitch05** [comment]
Closed by https://github.com/lightswitch05/hosts/commit/adb09a6a93bf84249a8456276a38256f097d8188

**Comment by funilrys** [comment]
@dnmTX `com.tenjin.ios.api` ==> `.api`  not in [Root Zone Database](https://www.iana.org/domains/root/db) which we parse into `iana-domains-db.json` so `INVALID`.

**Comment by funilrys** [comment]
@lightswitch05 You can (also) program on top of PyFunceble and only run a Syntax check instead of a availability check .... :smile_cat: 

Here is an example ([from the documentation](https://pyfunceble.readthedocs.io/en/latest/usage.html#from-a-python-script-or-module)):
```python
from PyFunceble import syntax_check as PyFuncebleDomainSyntax
from PyFunceble import ipv4_syntax_check as PyFuncebleIPv4Syntax

print("google.com", PyFuncebleDomainSyntax(domain="google.com"))
print("216.58.207.46", PyFuncebleIPv4Syntax(ip="216.58.207.46"))

print("forest-jump", PyFuncebleDomainSyntax(domain="forest-jump"))
print("257.58.207.46", PyFuncebleIPv4Syntax(ip="257.58.207.46"))
```

**Comment by dnmTX** [comment]
Looks like dnsmasq already implemented a [FIX](https://dnsmasq-discuss.thekelleys.org.narkive.com/a6sflufS/cert-vulnerability-vu-598349) for the `wpad` issue so i guess i'm all set there 😄
