### ISSUE TITLE
'partner.shareaholic.com' written twice

### ISSUE THREAD

**Issue by kyrios21** [lightswitch05/hosts#67]
I found these
`0.0.0.0 partner.shareaholic.compartner.shareaholic.com`
`0.0.0.0 partner.shareaholic.com`
Could it be miss-type? `partner.shareaholic.com` written twice in the 1st line?

**Comment by lightswitch05** [comment]
Hey @kyrios21 - yes, this is wrong. I use VirusTotal to help expand domains that I have blocked. Unfortunately, sometimes VirusTotal has junk like this in it.

![image](https://user-images.githubusercontent.com/598803/52180885-74970c80-27b9-11e9-9d39-62d290f91565.png)

I can add this specific one to a whitelist, but I'm not sure of a more general solution at this time.

**Comment by dnmTX** [comment]
So how is this working with VirusTotal? You saying that even if you remove it from the lists VT will add it on the next update? Does VT scanning your lists first or....?

**Comment by lightswitch05** [comment]
I have I a whitelist that runs after VirusTotal to remove things that are junk. I meant that while I can remove this specific one, there are 36 other domains that have the same duplication error. However, I just came up with a way to remove these duplicates 😄 updating soon

**Comment by lightswitch05** [comment]
Closed by #68. Thanks for giving me the motivation to do something about this 👍
