### ISSUE TITLE
Some brightcove entries break Politico video

### ISSUE THREAD

**Issue by neeez** [lightswitch05/hosts#7]
See video on: https://www.politico.com/story/2018/07/15/trump-putin-russia-summit-helsinki-722255 (scroll down).

Whitelisting entries:

players.brightcove.net
edge.api.brightcove.com
secure.brightcove.com

unbreaks the video player and doesn't cause other adverse effects. 

Thanks!

**Comment by lightswitch05** [comment]
This is sad news, brightcove is trash. My availability is limited the next few days, but I will review and remove those domains as time allows. Thanks for the report 👍

**Comment by lightswitch05** [comment]
I removed them in https://github.com/lightswitch05/hosts/commit/132c9636163c822158c98a4572b3bb5d38a8d7d8 Thanks again for the report!
