### ISSUE TITLE
domains

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#73]
Link for test(safe,it's a file sharing site): `https://gounlimited.to/lru3bivs28yc`

`0.0.0.0 geniusonclick.com`
`0.0.0.0 superonclick.com`
`0.0.0.0 discovernative.com`
`0.0.0.0 commercialvalue.org`
`0.0.0.0 mystighty.info`
`0.0.0.0 tracking.wpnetwork.eu`
`0.0.0.0 pushmejs.com`
`0.0.0.0 static.zdassets.com`......
....and anything else you can find. Thank you !!!!

P.S. Try not to block the Player though and hurry up on this one as i'm not sure how long the link will be active.

**Comment by lightswitch05** [comment]
Thanks for the list @dnmTX - it will be a little while before I'm able to get to them but I'll update this ticket as soon as I can

**Comment by dnmTX** [comment]
Whenever you can then.If the test link doesn't work let me know so i can give you another one. Thanks.

**Comment by lightswitch05** [comment]
I added all of them except for `static.zdassets.com` - I believe it might be used for generic hosting services

**Comment by dnmTX** [comment]
Thank you 👍
