### ISSUE TITLE
ad blocks

### ISSUE THREAD

**Issue by FBN7nbF4t7e2Y** [lightswitch05/hosts#74]
Hello these websites have ads that can be blocked

* `2.beeg.com` - ads on NSFW site `beeg.com`
* `vacaneedasap.com` a pop-up / redirect website
* `xhamser.com` this is a typo website that redirects to several sites

**Comment by lightswitch05** [comment]
I'm going to leave this one open for a while in case anyone else cares to verify them and ensure nothing useful breaks

**Comment by dnmTX** [comment]
**xhamser.com:**
`xhamser.com` - doesn't open anything so without link for test i can't do nothing else but...
`www.xhamser.com` - AVAST blocked the connection right away so i didn't want to go further:
![avast](https://user-images.githubusercontent.com/34774426/52538167-e250b480-2d34-11e9-9b17-e49d9228f380.PNG)
I'd say block them both,in my opinion they're both malicious.

**vacaneedasap.com:**
`vacaneedasap.com` it's already blocked in [quidsup's lists](https://gitlab.com/quidsup/notrack-blocklists/blob/master/notrack-blocklist.txt) which should be enough to block it here if you want but again...no test link so i can't confirm.
![tracker](https://user-images.githubusercontent.com/34774426/52538236-b84bc200-2d35-11e9-8b3b-0b0fc9f2271c.PNG)

**2.beeg.com:**
`2.beeg.com` - i couldn't find such a domain to be present there but i found `a2.beeg.com` which is the one that delivers ads and it's activated by inline script:
![a2 beeg](https://user-images.githubusercontent.com/34774426/52538261-37d99100-2d36-11e9-9280-0738f514b113.png)
Nothing breaks so i'd say it's safe to block if you want.
Also found one more there which is good to be blocked in another ad script: `adenabler.com`
![adenabler](https://user-images.githubusercontent.com/34774426/52538284-8c7d0c00-2d36-11e9-8f65-9ca6b42b6251.PNG)

I hope this helps.

**Comment by lightswitch05** [comment]
Thanks for the great write up @dnmTX!. Also thank you @FBN7nbF4t7e2Y for the info, in the future it would be helpful to provide URLs so that we can also verify the ads and tracking.

**Comment by lightswitch05** [comment]
Added in commit https://github.com/lightswitch05/hosts/commit/803e607fb0e38534ed5beb25a730744fc387cf7e
