### ISSUE TITLE
Running Script

### ISSUE THREAD

**Issue by eldervamp** [lightswitch05/hosts#75]
Hello. Im having trouble running your script. Im running the latest python 3 for windows. Installed the requirements. When i try to run the update i get a error saying line 45 secrets.json file not found error.

**Comment by lightswitch05** [comment]
Great question @eldervamp! My documentation is out of date. Also, I don’t have any error handling for that issue because I got lazy and I think you might be the first person to ever try to run it! So, here is how to get up and going, you are very close!

1. Creat a few account with virustotal.com
2. go to your account section and get your free API key
3. Create a `secrets.json` file in this repo with these contents, be sure to set your own API key in the file


```
{
        "virustotal_api_key": "PUT_YOUR_API_KEY_HERE"
}
```

Re-run! Let me know if you have more issues

**Comment by eldervamp** [comment]
Thanks for the fast response :). Used the info your provided and now it works. TY

**Comment by lightswitch05** [comment]
Glad you got it working. Just a heads up, a full list update is extremely slow, hours long. I have it setup to run weekly and I update this repo with the results.

**Comment by dnmTX** [comment]
@lightswitch05  get your things in order,more clientele is coming every day 😉

**Comment by lightswitch05** [comment]
Just some info on why it’s so slow. The free VirusTotal API has a rate limit of something like 4 API calls a minute so I had to introduce rate limits in the part is the code that talks to VirusTotal to ensure the script doesn’t get blocked. It’s bearable for adding new domains, but I wouldn’t want to be waiting around on a full list update

**Comment by eldervamp** [comment]
Wow, yes that did take a while to run a full scan..lol. Is there a way to add / import domains from a text file rather than adding / typing them one by one in the -d command? I really like how the script puts the domain and subdomains in order.

**Comment by lightswitch05** [comment]
I do not have any import features. However, you could just manually add all the domains to the list yourself and the next time you ran the script it would sort them for you. Just make sure they all have the `0.0.0.0` ip address. Also, when running the full list update, you can `ctrl +C` at any point and it will exit gracefully - saving any new domains it found while scanning.

**Comment by lightswitch05** [comment]
you can also supply multiple domains to the list at once:

    python3 update_hosts_file.py -d example1.com example2.com example3.com sub1.example1.com sub2.example1.com

As far as I know there isn't a limit - perhaps a command-line maximum args limit, but still a lot

**Comment by eldervamp** [comment]
Great. Added entries to the list and it organized them :). TY. Had some android app entries I added. Most of them facebook stuff..lol
