### ISSUE TITLE
other potential whitelist candidates

### ISSUE THREAD

**Issue by jawz101** [lightswitch05/hosts#76]
https://github.com/lightswitch05/hosts/blob/master/ads-and-tracking-whitelist.txt

I was just looking over your whitelist check and I was wondering if some of these might be practical for whitelisting (corporate mail servers and other typical internal infrastructure equipment, jenkins servers, customer documentation servers, career sites, login screens, etc.)

^(www\.)?academy\.
^(www\.)?admin\.
^(www\.)?billing\.
^(www\.)?blog\.
^(www\.)?careers\.
^(www\.)?cerberus\.
^(www\.)?chat\.
^(www\.)?cisco\.
^(www\.)?ciscowebex\.
^(www\.)?client-admin\.
^(www\.)?community\.
^(www\.)?console\.
^(www\.)?customer\.
^(www\.)?dashboard\.
^(www\.)?demo\.
^(www\.)?developer\.
^(www\.)?documentation\.
^(www\.)?documents\.
^(www\.)?email\.
^(www\.)?exchange\.
^(www\.)?feedback\.
^(www\.)?forum\.
^(www\.)?forums\.
^(www\.)?get\.
^(www\.)?honeypot\.
^(www\.)?imap\.
^(www\.)?intranet\.
^(www\.)?jenkins\.
^(www\.)?jobs\.
^(www\.)?knowledge\.
^(www\.)?learn\.
^(www\.)?learning\.
^(www\.)?livemail\.
^(www\.)?liveperson\.
^(www\.)?login\.
^(www\.)?mail1\.
^(www\.)?mail2\.
^(www\.)?mail3\.
^(www\.)?mail\.
^(www\.)?manage\.
^(www\.)?members\.
^(www\.)?nagios\.
^(www\.)?newsletter\.
^(www\.)?ocsp\.
^(www\.)?optout3\.
^(www\.)?outlook\.
^(www\.)?owa\.
^(www\.)?panel\.
^(www\.)?payments\.
^(www\.)?portal\.
^(www\.)?privacy\.
^(www\.)?recruit\.
^(www\.)?recruiting\.
^(www\.)?remote\.
^(www\.)?research\.
^(www\.)?signup\.
^(www\.)?spam\.
^(www\.)?staging\.
^(www\.)?store\.
^(www\.)?support\.
^(www\.)?trial\.
^(www\.)?try\.
^(www\.)?webex\.
^(www\.)?webmail\.
^(www\.)?welcome\.
^(www\.)?xmpp\.

**Comment by lightswitch05** [comment]
Thanks for this list, it looks good! There are a few I disagree with, but most look great, I'll get to it as soon as I can

**Comment by jawz101** [comment]
Yeah, I didn't know if some were questionable but I figured I'd throw them in there.  Which ones did you think about as not ones that you'd include?

for me I didn't know if they would use some of those names for things I'd want to block (xmpp is a messaging protocol.  research, dashboard, portal, admin, remote,store try, trial... all ambiguous that might point to things I'd block... i dunno.)

exchange I was thinking might point to an internal Microsoft exchange server.  OCSP is a matter of opinion I suppose

**Comment by lightswitch05** [comment]
@jawz101 I added most of them. I removed a few:

* mail: a lot of email tracking has that in the URL.
* staging: 4 different hosts have that in my base list which isn't even expanded. 
* chat: I hate those chat widgets and believe they also track
* get: seems too generic to me
* members: seems too generic to me
* panel: seems too generic to me

**Comment by dnmTX** [comment]
> * chat: I hate those chat widgets and believe they also track

💯 🥇 ❤️

**Comment by jawz101** [comment]
@dnmTX I agree.  I guess I was looking at it from the perspective of if it would block a customer service rep function.  It depends on what sort've domains are on @lightswitch05 's original list.  Perhaps it needs to be omitted.

**Comment by lightswitch05** [comment]
I understand where you are coming from. But on the other hand, I only block the root domain when I think it’s all junk and deserves to be blocked. I don’t have a lot of sympathy for people who can’t access their tracker admin panel because they themselves are trying to block trackers. If someone finds a blocked host that is causing issues, I’m happy to whitelist in an individual basis. Also, I do want to keep the list size down to a reasonable amount, so whitelisting is good. Anyways, that’s my thought process when adding these. I want to keep the list size down, but they are pretty much still all junk
