### ISSUE TITLE
Have problem seeing comment with dailystar.co.uk

### ISSUE THREAD

**Issue by kyrios21** [lightswitch05/hosts#78]
Try check with this URL
`https://www.dailystar.co.uk/showbiz-tv/hot-tv/764783/jeremy-kyle-the-kyle-files-knife-fight-london-jeremy-kyle-show`
I think we shall whitelist these in order to be able to **read** and **post** comment
`launcher.spot.im`
`spoxy-eb.spot.im`
`app-cdn.spot.im`
`images.spot.im` ---> required to see the avatar of commentator.

**Comment by lightswitch05** [comment]
Thanks @kyrios21 honestly I'm not sure I want to see comments on that site! 😆 But this does seem like legitimate functionality and the obvious tracker subdomains still get to remain blocked. I'm fine with moving these 4 subdomains into the aggressive list
