### ISSUE TITLE
We have problem with adblock detect at www.derbyshiretimes.co.uk

### ISSUE THREAD

**Issue by kyrios21** [lightswitch05/hosts#79]
Check at
`https://www.derbyshiretimes.co.uk/sport/football/real-madrid-president-florentino-perez-has-promised-returning-manager-zinedine-zidane-a-300m-transfer-kitty-and-the-rest-of-tuesday-s-top-rumours-1-9644170`
At 1st visit, you'll see the reminder of subsciption, close it (the reminder pop-up).
The 2nd visit (with refresh), you'll see banner (iframe) with adblock detected banner.
The fix is `jps.evolok.net`

![Snap13](https://user-images.githubusercontent.com/30654475/54220618-62c92780-4524-11e9-89c7-0f3685dc843a.jpg)

**Comment by kyrios21** [comment]
PS
You might be interested with these.
`cdn.playbuzz.com`
`prd-collector-anon.playbuzz.com`
And probably more

**Comment by lightswitch05** [comment]
I can't reproduce the ad blocker error, but the banner is annoying enough so I'm good with this addition. Thanks!

Also, [fanboy-annoyance](https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt) for uBlock Origin has all of `playbuzz.com` blocked. As far as I can tell its junk 'read also' type stuff with ads mixed in between so I just added all of it as well.
