### ISSUE TITLE
We have problem with adblock detect from news24.com

### ISSUE THREAD

**Issue by kyrios21** [lightswitch05/hosts#80]
Just checked with your latest hosts file, and with ABP turned off (Maxthon) and with UBO turned off (Firefox).
`https://www.news24.com/Tags/People/zinedine_zidane`
You'll see this :

![Snap6](https://user-images.githubusercontent.com/30654475/54271445-19281d80-45b4-11e9-9cec-3c752c7d0446.jpg)

The fix is `broadcastbed.com`
See yourself the code from `https://broadcastbed.com/v2/0/mkdA2P9fWLFULkKz2IdLblDTcRftdQV5Pwbrpdgz47DfHhvMTsOu0yt-LHhz2LWnRcElAsZU0snKoYeWw`

**Comment by lightswitch05** [comment]
It looks like this one is sufficiently covered by other lists already, so I'm going to pass on it

![image](https://user-images.githubusercontent.com/598803/54281207-9a10f600-456f-11e9-9ef0-3d09724f0e2d.png)
