### ISSUE TITLE
We have problem with adblock detect from news24.co.za

### ISSUE THREAD

**Issue by kyrios21** [lightswitch05/hosts#81]
Just checked with your latest hosts file, and with ABP turned off (Maxthon) and with UBO turned off (Firefox).
`https://www.sport24.co.za/Soccer/International/zidane-and-the-other-managers-who-could-not-stay-away-20190312`
You'll see this :

![Snap7](https://user-images.githubusercontent.com/30654475/54271955-314c6c80-45b5-11e9-9d8a-38f6b85fc5ac.jpg)

The fix is `jamexistence.com`

**Comment by lightswitch05** [comment]
Added 👍

**Comment by kyrios21** [comment]
Daniel,

The list from `ads-and-tracking.txt` shall be existed in `ads-and-tracking-extended.txt`, right?
Coz `southernx.nuggad.net` is listed at `ads-and-tracking.txt` but not in `ads-and-tracking-extended.txt`

**Comment by lightswitch05** [comment]
Great catch @kyrios21 - I'm not sure how that happened. Its fixed now by https://github.com/lightswitch05/hosts/commit/a43a208c411a72e1ced1a4c522e108a757d09863
