### ISSUE TITLE
[digitaltrends.com] adblock warning

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#82]
![Digital Trends](https://user-images.githubusercontent.com/34774426/54373842-f2b5c100-464b-11e9-9c03-49b65fe8bf2b.png)

Some adblockers might not be able to bypass it so blocking the domain one will be able at least to browse the website:
`0.0.0.0 fundingchoicesmessages.google.com`

**Comment by lightswitch05** [comment]
I couldn't reproduce in Firefox, but the hostname and screenshot are good enough for me. Added 👍

**Comment by dnmTX** [comment]
Well...i'm with chromium here and was able to bypass it(eventually) but probably was a good idea to reproduce it on your end,just in case there are some issues.Let's hope there won't be any.
Also,due to it's confirmed only by me,to keep record here see: https://github.com/AdguardTeam/AdguardForWindows/issues/2478#issuecomment-472775701

P.S. I guess if any problems,will go from there.
