### ISSUE TITLE
blocking bazaarvoice.com blocks customer product reviews

### ISSUE THREAD

**Issue by schecteracademicservices** [lightswitch05/hosts#84]
Blocking ugc.bazaarvoice.com blocks customer product reviews on basspro and other retail sites.. This seems fairly benign, and as I like being able to read customer reviews, I think it should be unblocked. 

And thanks for your hard work!

**Comment by lightswitch05** [comment]
@schecteracademicservices thanks for the feedback. There are a couple entries in my standard list, but looks like the majority of them are in the aggressive list. I'm going to move the couple entries in my standard list over to the aggressive one.

**Comment by lightswitch05** [comment]
Closed by https://github.com/lightswitch05/hosts/commit/9e73db9839739557174e9342d9c8c8c2e655b9ee
