### ISSUE TITLE
False positive in aggressive list: dns.google.com

### ISSUE THREAD

**Issue by mkb2091** [lightswitch05/hosts#85]
dns.google.com is used for dns-over-https, so I think that is probably a false positive

**Comment by lightswitch05** [comment]
Oh I didn’t realize I added this to the list. I do have it blocked at home since I do not trust google- but I see that’s not really the point of this list. I’ll remove it in my next update, thanks for the report!

**Comment by ler762** [comment]
> ... I see that’s not really the point of this list.

What is the point of the list?

Allowing DNS over HTTPS allows bypassing the hosts file, which certainly defeats my purpose for using this list.

my notes:
```
https://dns.google.com/resolve?name=github.com&type=A
... "Answer":[ {"name": "github.com.","type": 1,"TTL": 49,"data": "192.30.253.112"}]}
```

**Comment by lightswitch05** [comment]
Thanks for your comment @ler762. The point of the list is to block ads and trackers. Forcing your devices to use your local DNS server is an implementation detail that is outside the scope of the list.

However, I totally agree that the domain deserves to be blocked- I have it blocked on my home network. I have seen a list whose purpose was to block DoH services- but I’m unable to find it at the moment. Perhaps someone else knows where it is. If I see it again, i’ll post link.

**Comment by ler762** [comment]
@lightswitch05 forcing my devices to use my local dns isn't a problem, bypassing them (& the host file) by using dns over https is.

I'd rather not do https inspection (aka mitm) & I know I'm playing wack-a-mole by blocking specific doh servers, but it seems like it's that or https inspection.

> I have seen a list whose purpose was to block DoH services ... If I see it again, i’ll post link.

I would appreciate it.

**Comment by lightswitch05** [comment]
@ler763 checkout https://github.com/oneoffdallas/dohservers/blob/master/list.txt

I don’t think it’s the same list I saw before, but should serve your purpose

**Comment by ler762** [comment]
@lightswitch05 yes, exactly what I was looking for.  Thank you!
