### ISSUE TITLE
PetaPixel.com false positive

### ISSUE THREAD

**Issue by holdit** [lightswitch05/hosts#88]
I believe Peta Pixel, added a few days ago, is being blocked by mistake. It's a site/blog about photography, cameras, etc:

```
petapixel.com
cdn.petapixel.com
files.petapixel.com
www.petapixel.com
```

**Comment by lightswitch05** [comment]
Thanks @holdit ! I actually noticed it was a false positive and _thought_ I had reverted the change that added it. I guess I messed up the revert. Its removed now, thank you for bringing this to my attention!
