### ISSUE TITLE
Remove anvato.net domains (False positive)

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#89]
Please remove `w3.cdn.anvato.net` as well as all subdomains of `apis.anvato.net`. They are media streaming domains. Blocking those domain breaks this player: `https://www.wsbtv.com/live-stream` and I imagine many others.

You should add `config.analytics.anvato.net` and `collector.analytics.anvato.net` though.

**Comment by lightswitch05** [comment]
Thanks for the info @llacb47 - I've made the requested changes. It looks like those have been in there for a long time 😞. I greatly appreciate the feedback!

**Comment by llacb47** [comment]
Site is still broken - you forget to remove `tkx.apis.anvato.net`

**Comment by lightswitch05** [comment]
@llacb47 sorry about that - I've verified its all working now and added a couple new ones found on that site
