### ISSUE TITLE
vice-web-statics-cdn.vice.com false positive

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#91]
Hi,

please remove this line: `0.0.0.0 vice-web-statics-cdn.vice.com`

It causes breakage on Vice Media sites.

Test links:
```
https://www.vice.com/en_us/article/59yexk/princeton-study-session-replay-scripts-tracking-you
https://video.vice.com/en_us/video/joshua-oppenheimer/569956f4be3dc2bb32e266e2
https://garage.vice.com/en_us
```

**Comment by dnmTX** [comment]
Yeah,that is unfortunate.They using the same domain to deliver fonts,css etc. and for tracking as well.
The site is badly broken.indeed.

**Comment by lightswitch05** [comment]
* `https://www.vice.com/en_us/article/59yexk/princeton-study-session-replay-scripts-tracking-you`

that's an ironic article to link to :D - you are right about it being broken. I'll remove it.

**Comment by lightswitch05** [comment]
Done, thanks again for the feedback 👍
