### ISSUE TITLE
js.intercomcdn.com break rollbar.com UI

### ISSUE THREAD

**Issue by AriApar** [lightswitch05/hosts#92]
rollbar.com projects seem to be loading js files from `js.intercomcdn.com`, which causes the adblock list to break the site

**Comment by lightswitch05** [comment]
Hey @AriApar. rollbar.com and its subdomains are all blocked in the ads and tracking list:

```
0.0.0.0 rollbar.com
0.0.0.0 api.rollbar.com
0.0.0.0 api-alt.rollbar.com
0.0.0.0 cdn.rollbar.com
0.0.0.0 cemail.rollbar.com
0.0.0.0 changelog.rollbar.com
0.0.0.0 watson.telemetry.microsoft.comapi.rollbar.com
0.0.0.0 email.mail.rollbar.com
0.0.0.0 ping.rollbar.com
0.0.0.0 status.rollbar.com
0.0.0.0 www.rollbar.com
```

So I'm not particularly concerned about `js.intercomcdn.com` breaking it. If you come across a significant amount of other sites breaking for the same reason, I would be more interested in it

**Comment by AriApar** [comment]
Ah interesting, rollbar is a useful work tool so surprised to see it on the list. Fair enough, thanks for the info.

**Comment by lightswitch05** [comment]
Yeah, blocking these types of tools is a bit of a hot topic. The way I see it:

* 3rd parties that collect information on me that is not directly related to the functionality of the app/website should be blocked. Regardless of the current laws, I consider it my data and I do not consent to them collecting it.
* a lot of the error information is going to be what Ads & trackers I’m blocking from the site/app. This feedback can often be used against me to make changes to reduce the effectiveness of my blocking
* my understanding is that rollbar and other similar tools can be configured to send any data the developer wants to send- not just error information. This loops back to the first point- that’s my data and I don’t want 3rd parties to have it.

I’m a software developer and I totally recognize how these tools are useful for discovering broken things and fixing them. I really prefer self-hosted solutions, but I get it. However, they are tracking services. You might be interested in reading some of the #58 related tickets
