### ISSUE TITLE
cdn.turner.com false positives and breakage

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#93]
Hi,

please consider removing these domains from `tracking-aggressive-extended.txt`:

```
! needed for go.cnn.com
turnip.cdn.turner.com
tvem.cdn.turner.com
! needed for video player
pmd.cdn.turner.com
amd.cdn.turner.com
! needed for images on money.cnn.com (older articles)
i2.cdn.turner.com
```

Test breakage on these pages:
```
! Video player broken
https://www.cnn.com/2019/08/19/weather/greenland-nasa-climate-battle-intl/index.html
! Total breakage
https://go.cnn.com/
! Layout, images broken
https://money.cnn.com/2016/05/16/technology/gfast-internet-speeds/
```

Whitelisting these domains to unbreak the page layout and styles on the last test link also whitelists some trackers:

```
i.cdn.turner.com
z.cdn.turner.com
! Removing these domains will let trackers through... Examples:
! https://[i|z].cdn.turner.com/analytics/cnnngtv/jsmd-prod.js
! https://[i|z].cdn.turner.com/ads/adfuel/ais/1.3/cnn-ais.js
! https://[i|z].cdn.turner.com/ads/adfuel/adfuel-1.3.4.min.js
! https://[i|z].cdn.turner.com/ads/cnn/cnn_interactive_leaf.js

```

And consider adding `agility.cnn.com` due to Ensighten tracking script: `https://agility.cnn.com/turner/cnn-prod/Bootstrap.js`

**Comment by lightswitch05** [comment]
Thanks for this detailed ticket! I know blocking `turner.com` breaks things - which is why its in the aggressive list. But yeah, I think its probably too much. I'm removing it. I'm also adding the new agility subdomain you mention.

**Comment by lightswitch05** [comment]
I've made the requested changes. Please let me know if more are needed. Thanks for the great feedback

**Comment by llacb47** [comment]
I think I will just have to add some filters to uBlock Origin in order to fix the older sites that use `i.cdn.turner.com` to serve images and tracking.

```
@@||cdn.turner.com^$image,css,font,domain=cnn.com
||cdn.turner.com/*/1.gif$image,important
@@||cdn.turner.com^$script
||cdn.turner.com/ads/*$script,important
||cdn.turner.com/analytics/*$script,important
```
