### ISSUE TITLE
Please block these tracking hosts 

### ISSUE THREAD

**Issue by cloudyytechie** [lightswitch05/hosts#95]
Okay so I was monitoring network traffic and I found some trackers that haven’t been blocked datarouter.ol.epicgames.com and pipes-prod-glutton.public.aws.demonware.net and also prod.realtimevc.ros.rockstargames.com and prod.telemetry.ros.rockstargames.com

**Comment by cloudyytechie** [comment]
Okay thanks

**Comment by cloudyytechie** [comment]
I have them all blocked and nothing has broken I’ve had them blocked for a while and the epic games domain collects game analytics information

**Comment by cloudyytechie** [comment]
The games that produce them are gta 5 online call of dutyblack ops 4 and fortnite

**Comment by lightswitch05** [comment]
Those are hard for me to validate. Anyone else watching this repo able the verify the blocks do not break anything?

**Comment by anudeepND** [comment]
Blocking `prod.telemetry.ros.rockstargames.com`  will crash GTAOnline. For more info, https://gtaforums.com/topic/907162-crashing-after-new-updates/page/2/#comments if I remember correctly, this was mentioned somewhere in the Pi-hole forums too
