### ISSUE TITLE
Yandex Disk: false positive for `yadi.sk`

### ISSUE THREAD

**Issue by DRSDavidSoft** [lightswitch05/hosts#97]
Hey Daniel,

I noticed that in 3354108 you've added the **`yadi.sk`** to your list.

This domain name actually belongs to **[Yandex Disk](https://disk.yandex.com/)**.
Yandex Disk a legitimate cloud provider service from Russia; similar to what OneDrive, iCloud, Dropbox and Google Drive also provide.

Here's an example URL that is used by the [Armbian Linux](https://forum.armbian.com/topic/2419-armbian-for-amlogic-s905-and-s905x-ver-544/) project to host an image:
```
https://yadi.sk/d/pHxaRAs-tZiei/S905
```

From your [commit message](https://github.com/lightswitch05/hosts/commit/3354108b6da5c7c804edc0b5fcb9c87eb3600797), I understand that you received some junk mail that used their short url domain. However, the website itself is not dedicated to delivering any type of malicious content.

So, if possible, I'd like to ask to remove the `yadi.sk` domain from the `ads-and-tracking*.txt` lists, as a false positive.

Also, thank you for maintaining this excellent list of adservers and trackers! 😄

**Comment by lightswitch05** [comment]
Thank you for the detailed ticket @DRSDavidSoft! Having detailed and well-researched feedback makes requests like this very simple. Also, thank you for the kind words! I've removed the false-positive in https://github.com/lightswitch05/hosts/commit/a5a6a5402d8dc288fc955c45f4e8010eefe52d8f

cheers🍻
